### ISSUE TITLE
dart-lang.github.io/server: repatriate or drop these separately served pages

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#1029]
The following issue arose while working on renaming `/dart-vm` paths to `/server` (#965).

We have the following Firebase redirect rules:

```json
{ "source": "/server/**", "destination": "https://dart-lang.github.io/server", "type": 301 },
{ "source": "/server/app-engine**", "destination": "https://dart-lang.github.io/server/google-cloud-platform", "type": 301 },
{ "source": "/server/google-cloud-platform**", "destination": "https://dart-lang.github.io/server/google-cloud-platform", "type": 301 },
{ "source": "/server/tls-ssl.html", "destination": "https://dart-lang.github.io/server/tls-ssl.html", "type": 301 },
```

The first one is interfering with our `/dart-vm` to `/server` rename and so will be dropped.

https://dart-lang.github.io/server/ hosts some links and docs using Jekyll and GH pages (the repo is https://github.com/dart-lang/server). @kwalrath, @kevmoo: Shouldn't that content be on dartlang.org, or maybe simply dropped? It is likely outdated. In particular it uses to old Dart logo.

**Comment by kwalrath** [comment]
It's definitely outdated. @kevmoo, let's talk about this. If we need the history, @Sfshaza might remember.

**Comment by Sfshaza** [comment]
Oh, I certainly remember!

The point, when we redesigned www, was to move all server stuff off, because it only applies to a specific implementation of Dart. We wanted to create server.dartlang, or vm.dartlang, but the VM folks weren't interested.  So, with their knowledge and permission, we moved things over there. Such as Observatory docs, for example.

The idea was to place things under /dart-vm with the hope of moving all that info elsewhere, at some point. The www site should only talk about core Dart, not Dart implementations.
