### ISSUE TITLE
Improve formatting of `${...}`

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1108]
@mkustermann pointed out that code inside of `${...}` is formatted like the rest of the string. It'd be good to format it like real code. E.g. in www.dartlang.org/articles/dart-vm/io#file-system-access, the print statement in the first code snippet looks something like this:

![image](https://user-images.githubusercontent.com/2164483/44752803-02672100-aad1-11e8-819f-ffee5ceaa722.png)

That `await` code (if outside of the string) would look like this:

![image](https://user-images.githubusercontent.com/2164483/44752818-1448c400-aad1-11e8-88dd-aef15ed0435f.png)

This is probably a prettify issue, but it'd be really nice to fix it.

**Comment by smolck** [comment]
Maybe this could be fixed by adding some regex to [`src/_assets/js/vendor/code-prettify/lang-dart.js`](https://github.com/dart-lang/site-www/blob/master/src/_assets/js/vendor/code-prettify/lang-dart.js)?

For example, this regex[1][2] matches things like `$foo` or `${<Dart code>}`:
```
\$((\w+)|\{([^{}]+)\})
```
Could we add similar regex somewhere in `lang-dart.js` to detect string interpolation and highlight it like normal code?

[1]: I adapted from here: https://github.com/Dart-Code/Dart-Code/blob/06eaf66e9613b16e1401dd267c5597dff1524239/syntaxes/dart.json#L328. 
[2]: I know almost zero regex, but it works here: https://regexr.com/4m72j

**Comment by kwalrath** [comment]
I believe this would require a PR to https://github.com/google/code-prettify, but I could test the fix locally first.

@chalin how does this solution sound to you?

**Comment by chalin** [comment]
@smolck - the Dart Code reference is a good find!

@kwalrath - I agree that any updates should be submitted as a PR over https://github.com/google/code-prettify.

I see that https://github.com/google/code-prettify/pull/592 hasn't been merged yet. Could we ping someone to ensure that progress is made?

Oh, we've _already_ made local changes to vendor files -- e.g., #1624! Not what I prefer (since local changes like these run the risk of being overwritten), but it's good that I'm aware of it now. We probably should have also added a comment to the top of `vendor/code-prettify/lang-dart.js` to warn the reader/maintainer that the file contains a (hopefully temporary) patch.

**Comment by smolck** [comment]
@kwalrath @chalin Is submitting a PR to `code-prettify` for this (assuming it works) the route we want to go?

**Comment by kwalrath** [comment]
> @kwalrath @chalin Is submitting a PR to `code-prettify` for this (assuming it works) the route we want to go?

I think we'd want PRs both here and at code-prettify.

**Comment by parlough** [comment]
It looks like Rouge does this a little better, so going to close this in favor of https://github.com/dart-lang/site-www/issues/3846.

The final though goal though is to move to a Dart analyzer based system as tracked in https://github.com/dart-lang/site-www/issues/4163.
