### ISSUE TITLE
Link to stable .deb SDK points to old version

### ISSUE THREAD

**Issue by whesse** [dart-lang/site-www#1113]
The link on page https://www.dartlang.org/tools/sdk#install-a-debian-package
with text "Stable channel" points to "https://storage.googleapis.com/dart-archive/channels/stable/release/latest/linux_packages/dart_2.0.0-1_amd64.deb"

but the latest stable release is dart_2.0.3-1_amd64.deb.

**Comment by kwalrath** [comment]
Looking at https://github.com/dart-lang/sdk/releases, I don't see any stable releases after 2.0.0. Do we have any that aren't marked there? Or does debian have package #s that don't match the stable release?

We build the URL based on the latest dev and stable release #s. I'm not actually sure how we determine what those are; @chalin would know.

Implementation details:
The code that constructs the download URL is in https://github.com/dart-lang/site-shared/blob/master/src/tools/sdk/archive/assets/install.js:

```
  var download = 'https://storage.googleapis.com/dart-archive/channels/' + channel + '/release/latest/linux_packages/dart_' + version + '-1_amd64.deb';
```

So if 2.0.0 is the current stable version, then the URL you get is https://storage.googleapis.com/dart-archive/channels/stable/release/latest/linux_packages/dart_2.0.0-1_amd64.deb#debian-link-stable.

**Comment by chalin** [comment]
As Kathy has pointed out, the URL is constructed from information obtained from storage.googleapis.com. In particular, the version is fetched from https://storage.googleapis.com/dart-archive/channels/stable/release/latest/VERSION, which currently contains:

```json
{
  "date": "2018-08-03", 
  "version": "2.0.0", 
  "revision": "22eb4ef31aa3a317cf624a46ee07f81c751084f8"
}
```

So the install page is displaying the link that it should. Someone needs to update https://storage.googleapis.com/dart-archive/channels/stable/release/latest/VERSION.

Since this isn't an issue with the SDK install page, shall we close this issue @kwalrath?

**Comment by whesse** [comment]
Correct, this issue is invalid.  Closing.
