### ISSUE TITLE
Add tear-off, lambda, and closure to the language tour

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1158]
The language tour should at least briefly cover all the terms that Effective Dart mentions (especially those in guideline headings). The terms _tear-off_, _lambda_, and _closure_ are in the guideline [DON’T create a lambda when a tear-off will do.](https://www.dartlang.org/guides/language/effective-dart/usage#dont-create-a-lambda-when-a-tear-off-will-do)

**Comment by kwalrath** [comment]
The terms _lambda_ and _closure_ are mentioned in https://dart.dev/guides/language/language-tour#anonymous-functions. We still need to add _tear-off_, especially since we'll have constructor tear-offs soon.

**Comment by jamesderlin** [comment]
Lambda and closure also are more common terms, should be known to people with computer science backgrounds, and can be looked up on Wikipedia ([lambda (programming)](https://en.wikipedia.org/wiki/Lambda_(programming)), [closure (computer programming)](https://en.wikipedia.org/wiki/Closure_(computer_programming))).  In contrast, I have never seen the term "tear-off" before learning Dart.

**Comment by atsansone** [comment]
Lambdas and closures are covered in https://dart.dev/language/functions#anonymous-functions.

Constructor tear-offs will be covered in https://github.com/dart-lang/site-www/issues/3577. Closing this issue.

**Comment by jamesderlin** [comment]
> Constructor tear-offs will be covered in #3577. Closing this issue.

The tear-off aspect of this  issue was about tear-offs in general.  The term "tear-off" isn't defined anywhere in the Dart Language Tour, despite being mentioned in Effective Dart.  Issue #3577 is about *constructor* tear-offs, which is a special case because the tear-off for the unnamed constructor is `ClassName.new`.

If the intent is to repurpose #3577 to be about tear-offs in general, that's fine, but then that issue should be updated to make it clear that it's no longer specifically about constructor tear-offs.

**Comment by atsansone** [comment]
@jamesderlin : I did add tear-offs to the PR: https://github.com/dart-lang/site-www/pull/5850. Lambdas and closures were already there. Thanks for the prompt!
