### ISSUE TITLE
'Emulating Functions in Dart' page issue

### ISSUE THREAD

**Issue by feinstein** [dart-lang/site-www#1252]
Page URL: https://www.dartlang.org/articles/language/emulating-functions
Page source: https://github.com/dart-lang/site-www/tree/master/src/_articles/language/emulating-functions.md

Description:

The page says:

>However, there are cases where this ability can be quite useful.

But there aren't any examples, and for someone coming from a language without it, it's pretty hard to imagine when this would be useful.

**Comment by parlough** [comment]
This mention no longer exists due to the removal of the article. We now have a small mention [in the language tour](https://dart.dev/guides/language/language-tour#callable-classes) and I'm not sure it's a very encouraged construct.

With the removal of the article and this mention, I'm going to close this issue. Thanks for raising the suggestion!

**Comment by feinstein** [comment]
Why do you think it's not recommended in the current state of dart? Callable classes can be quite useful for abstracting use cases, with dependency injection. We can construct a class with different dependencies and just call it, having one object for each use case. This pattern is recommended by Google in the Android Jetpack Architecture.

**Comment by parlough** [comment]
That's fair, thanks for the example. I've created a new issue to track expansion of the language tour section covering callable classes, with a focus on the "why" as well as some other changes that need to be made: https://github.com/dart-lang/site-www/issues/4267
