### ISSUE TITLE
No Section about void in Language Tour

### ISSUE THREAD

**Issue by shubhamhackz** [dart-lang/site-www#1268]
`void` is a special type in dart which almost behaves differently as compared to any other language. There are many rules related to the `void` in dart which confuses programmers coming from java and others languages. This should be properly documented in the official docs as of now it is completely ignored.There should be a section containing all the use cases and behavior of `void`  in Language Tour.
The only things that I found linked to the official docs about `void` is this article on medium : 
https://medium.com/dartlang/dart-2-legacy-of-the-void-e7afb5f44df0

My Article on Medium : 
The curious case of void in dart :  https://medium.com/flutter-community/the-curious-case-of-void-in-dart-f0535705e529

**Comment by kwalrath** [comment]
Once we add `void` to the language tour, we should change the `void` entry in the [keyword table](https://dart.dev/guides/language/language-tour#keywords) to point to that discussion instead of to the medium article.

Btw, looking at the keyword table made me realize that the `set` keyword incorrectly pointed to the `Set` API ref. This is fixed in #2278.

While I'm thinking about important types... I've confirmed that the language tour discusses `Future<void>` and the top types `Object` & `dynamic`. However, it doesn't mention _top types_; maybe it should. I don't think we discuss the bottom type anywhere (`Null` currently, `Never` once null safety is in).

**Comment by kwalrath** [comment]
Related: #2699

**Comment by shubhamhackz** [comment]
@kwalrath I wrote an article two years back explaining behaviour of `void` keyword. Let me know if this could be useful.

**Comment by shubhamhackz** [comment]
@kwalrath  Any update on this?

**Comment by kwalrath** [comment]
We added a discussion of `void` in #2708. I think that's probably sufficient, for now.
