### ISSUE TITLE
Make TOC parsing work again

### ISSUE THREAD

**Issue by filiph** [dart-lang/site-www#1325]
With https://github.com/dart-lang/site-www/pull/1323/files#diff-d804b662f975a75cb8c7b56e73edacedR25, TOC parsing in Effective Dart is not automatic anymore.

We should fix this.

// cc @kwalrath

**Comment by kwalrath** [comment]
I noticed this again today. :(

**Comment by kwalrath** [comment]
It seems to work except for rules that have custom anchors. (Sometimes we'll tweak a rule's title, but we want to keep the URL the same.)

**Comment by chalin** [comment]
So is the TOC being updated manually now?

**Comment by chalin** [comment]
What seems to be happening is that the TOC generator is generating section title text containing Jekyll anchor syntax (e.g., `foo boo {#foo-bee-doo}`) and it fails to _use_ the Jekyll anchor syntax to create a proper anchor (continuing with the same example it would generate a TOC entry like `<a href='/guides/x/y/z#foo-boo'>foo boo {#foo-bee-doo}</a>` instead of `<a href='/...#foo-bee-doo'>foo boo</a>`. Is that correct?

(Btw, I noticed this only because I ran the `pre-push.sh` script.)

**Comment by kwalrath** [comment]
Yes, that sounds like what's happening.

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/site-www/pull/2956
