### ISSUE TITLE
Document spread collections

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1395]
We'll need to update the language tour and should probably change our analysis options to prefer spread collections, which is likely to affect some examples in the docs.

Related: dart-lang/linter#1410, dart-lang/language#164

**Comment by parlough** [comment]
Since https://github.com/dart-lang/site-www/commit/82cb19a9761c568ae796fda3305b58788bad2669 added documentation for the spread operator and we now use the `lints:recommended.yaml` set of linter rules which includes `prefer_spread_collections` for examples, I will close this issue as fixed :D

If there's any more specific improvements you'd like to see, feel free to reopen or create a new issue. Thanks!
