### ISSUE TITLE
'Pub Package Layout Conventions' page issue: LICENSE is REQUIRED

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#1447]
See https://github.com/dart-lang/pub/blob/master/lib/src/validator/license.dart

Not sure how we want to document this.

Must be one of `LICENSE`, `COPYING`, `UNLICENSE` with any extension and any case, it appears.

The docs make it seems like this is optional for publishing...tis not...

**Comment by jonasfj** [comment]
I suggest that we:
1. State that `LICENSE` is required, and,
2. Do not mention that the file could be named `COPYING` or `UNLICENSE`.

Some day we should probably make a specification for the packaging format. This specification should ideally not leave room for ambiguity, but it might have to feature an appendix documenting that legacy packages may contain `COPYING` or `UNLICENSE` instead of `LICENSE`.

**Comment by kwalrath** [comment]
Fixed by #1640.
