### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by rhuanbarros** [dart-lang/site-www#160]
URL: https://www.dartlang.org/googleapis
Expected page: Gmail Api Dart Reference

**Comment by Sfshaza** [comment]
@rhuanbarros, that's been moved here:  https://github.com/dart-lang/googleapis

This needs to be added to the redirects. Thx!

**Comment by kwalrath** [comment]
@rhuanbarros can you recall where you found that link?

**Comment by kwalrath** [comment]
@filiph I've added this to our spreadsheet.
@rhuanbarros Thanks very much for the report. It might take a couple of weeks before this redirect makes it out, but it'll happen eventually.

**Comment by anders-sandholm** [comment]
@mit-mit since he re-discovered this independently.

Looks like both https://developers.google.com/api-client-library/ and https://developers.google.com/discovery/libraries use it.

We also need to include a redirect from https://www.dartlang.org/googleapis/#a-web-application-example to  https://github.com/dart-lang/googleapis_examples

**Comment by Sfshaza** [comment]
Fixed.
