### ISSUE TITLE
'Dart documentation' page issue 

### ISSUE THREAD

**Issue by mar3y96** [dart-lang/site-www#1646]
Page URL: https://www.dartlang.org/guides/index
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: in Tools & techniques section , Command-line tools ,Dart SDK 
the arrow direction is wrong and it is active by default and this is wrong too

**Comment by kwalrath** [comment]
Actually, I intentionally made the **Dart SDK** and **Other command-line tools** sections open as soon as you open the **Command-line tools** section. (The arrows are correct, since they reflect the open state.) It seemed silly to require people to click one more time to get a list of command-line tools.

I'm going to close this issue, but I'll keep an eye out for whether it bothers other people. Thanks for the feedback!
