### ISSUE TITLE
Article on convertors and codecs missing

### ISSUE THREAD

**Issue by duncanmak** [dart-lang/site-www#1650]
https://dart.dev/articles/libraries/converters-and-codecs is current a dead page.

Maybe it should be resurrected.

Currently, there's a cache of the page (with the old page layout) here: http://web.archive.org/web/20190402212224/https://www.dartlang.org/articles/libraries/converters-and-codecs#how-to-write-efficient-conversions.

cc @sortie, he asked me to file an issue on IRC.

**Comment by kwalrath** [comment]
Fixed by #1657.

**Comment by sortie** [comment]
Thanks @kwalrath for fixing the issue and thanks @duncanmak for filing the issue. Glad to see it get fixed!

Do we know if there's any such other useful articles that were lost in the migration?

**Comment by kwalrath** [comment]
There were definitely other articles that we removed... The question is whether they had information that was still useful. In the past week, the top-25 404s have included the following (ex)articles:

/articles/dart-vm/native-extensions (still exists; https://github.com/dart-lang/site-www/issues/1671)
/articles/dart-vm/benchmarking (1/3 the # of 404s, compared to native-extensions)
/articles/language/beyond-async
/articles/language/mixins
/articles/broadcast-streams & /articles/libraries/broadcast-streams
/articles/language/await-async (1/5)
/articles/libraries/converters-and-codecs (exists as of #1657)
/articles/zones (exists as of #1634; needs a redirect)
/articles/emulating-functions & /articles/language/emulating-functions (1/6)
/articles/libraries/reflection-with-mirrors
/articles/improving-the-dom (1/15)

Of course, just because people were looking for an article doesn't mean that the article actually had the info people wanted/needed. But we can consider it to be an indication of interest in the topic.
