### ISSUE TITLE
Remove  https://v1-dartlang-org.firebaseapp.com

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1675]
We left this v1 site up when we first launched Dart 2, but it's no longer helpful to the great majority of Dart users, and it's stealing search juju from dart.dev.

**Comment by kwalrath** [comment]
We should probably leave it up and redirect to dart.dev.

/cc @johnpryan @domesticmouse

**Comment by kwalrath** [comment]
Decision: remove this site!

**Comment by filiph** [comment]
Fixed with https://github.com/dart-lang/site-www/commit/abfc7baabba7d480c37a72b71c78d56238e60a6b.

Includes deep redirects, e.g. https://v1-dartlang-org.firebaseapp.com/guides/libraries/create-library-packages redirects to the corresponding page on dart.dev.

All is HTTP 301, so "permanently moved". Tells search engines that they should update their index.

Also added the code to the 1.x branch, in case we need to tweak. https://github.com/dart-lang/site-www/tree/1.x
