### ISSUE TITLE
How to extend core methods?

### ISSUE THREAD

**Issue by ydwan** [dart-lang/site-www#1751]
Example:
'123456'.equals(str);
Not find 'equals' method in flutter.
I want add a method on class and not break too many code.

In c#, we can add 'static' on class.
static class String {static Boolean equals() {.........}}

**Comment by kwalrath** [comment]
Closing because we have no such feature right now. However…

Is [static extension methods](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md) the feature you want? It isn’t in the language yet, but has been accepted and has an [implementation plan](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/implementation-plan.md).

In general, github.com/dart-lang/language is the place to find information on requested features (issues) and language plans (accepted/working).

**Comment by ydwan** [comment]
Thanks! I got it~
