### ISSUE TITLE
Fix the portmanteau example

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1800]
The DartPad example under https://dart.dev/tutorials/web/fetch-data#using-getString-function is broken because of a problem loading data.

The fix might be as simple as changing dartlang.org to dart.dev (which we should search for globally, anyway), or it might be more involved.

**Comment by Arun8295** [comment]
Hi, I would like to take up this issue.

**Comment by Arun8295** [comment]
Modified the URL from dartlang.org to dart.dev and created new gist files 

https://gist.github.com/Arun8295/acb2e9d00b3b13e0c672157a4546a9d2
https://gist.github.com/Arun8295/e0ed44f41317f0e40c8bc823506af3ed

Tested the changes in dartpad by replacing my id in the URL with above gist ids.
https://dartpad.dev/experimental/embed-new-html.html?id=<<id>>

I need help to update this new gist URL instead of the existing one.

**Comment by kwalrath** [comment]
Thank you, @Arun8295! (I didn't even know you could test embedded DartPads that way... good sleuthing!)

I've forked your gists here:

https://gist.github.com/kwalrath/70bb4db7bea44663206e7a9c111f31d2
https://gist.github.com/kwalrath/256036008d252d07c9c9d72bd3b03867

All you need to do now is go to the source code for the page that embeds the DartPads (you can get to it by clicking the page icon at the top right, and then the pencil in GitHub) and substitute those numbers for the existing ones. (e.g. portmanteaux_simple should refer to 70bb4db7bea44663206e7a9c111f31d2 instead of the current number.)

**Comment by kwalrath** [comment]
#1971 completed the fix for this bug by incorporating these gists into the page.
