### ISSUE TITLE
Don't push the site if any required build jobs fail

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#1820]
I was surprised when the changes in https://github.com/dart-lang/site-www/pull/1815 got pushed to dart.dev even though the build was failing: https://travis-ci.org/dart-lang/site-www/builds/568602856.

This wasn't a big deal; I pushed despite the broken build because I knew the PR didn't cause the breakage.

But still, we should probably disable the push if any required job fails.

**Comment by kwalrath** [comment]
Related: #1821

**Comment by chalin** [comment]
> Don't push the site if any required build jobs fail

That how things used to be setup. I'm unsure what change might have caused that. Will have to investigate.

The build you refer to in the opening comment doesn't show any failed jobs.

**Comment by kwalrath** [comment]
Not exactly the same, but here's a build that probably should've failed (due to a bad link) but didn't:

https://travis-ci.org/dart-lang/site-www/builds/595659627

**Comment by parlough** [comment]
I believe that this has been fixed with the switch to GitHub Actions. You can see how `deploy` depends on the `test` jobs being successful here: https://github.com/dart-lang/site-www/blob/master/.github/workflows/build.yml#L85

An example commit to the main branch which had failures which prevented the deploy job: https://github.com/dart-lang/site-www/actions/runs/1046231941

So I will close this for now, but feel free to reopen if the behavior doesn't match what you desire.
