### ISSUE TITLE
@override has no effect on DartPad

### ISSUE THREAD

**Issue by andhieka** [dart-lang/site-www#1946]
The tutorial says 
> The @override annotation tells the analyzer that you are intentionally overriding a member. The analyzer raises an error if you've failed to perform the override properly.

However, omitting `@override` in DartPad, the code compiles fine and no warning / error is displayed. For example, I expect the following code to cause compilation error. However, it runs fine in DartPad.

```
class Bicycle {
  int cadence;
  int speed;
  int gear;

  Bicycle(this.cadence, this.speed, this.gear);
  
  String toString() => 'Bicycle: $speed mph ($cadence x $gear)';
}

void main(List<String> args) {
  final bike = new Bicycle(2, 0, 1);
  print(bike);
}
```

**Comment by chalin** [comment]
Hi. I believe that you are referring to [page 2 of the _Intro to Dart for Java Developers_ codelab](https://codelabs.flutter-io.cn/codelabs/from-java-to-dart/index.html#1).

The analyzer will not report any problems if you choose to write your code without `@override` annotations. Your `Bicycle` class has no `@override` annotations, that is why the analyser isn't reporting any issues.

Here is an excerpt from the tutorial:

> Add the following `toString()` method anywhere in the Bicycle class:
> ```dart
> @override
> String toString() => 'Bicycle: $speed mph';
> ```
> #### Observations
> - The `@override` annotation tells the analyzer that you are intentionally overriding a member. The analyzer raises an error if you've failed to perform the override properly.

The key part of that observation is the following: **"... if you've failed to perform the override properly"**. Since the signature of your `Bicycle.toString()` method is valid, no problem is reported.

Now change your method to something like this:

```dart
@override
String toString(int speed) => 'Bicycle: $speed mph';
```

Now the `Bicycle.toString()` method's signature doesn't match the signature of the method that it is overriding, and so the analyser reports an error:

> ![image](https://user-images.githubusercontent.com/4140793/65508935-53497480-de9f-11e9-977f-4c09e1e415fa.png)

I hope this helps.
