### ISSUE TITLE
More information in web tutorials (Connect dart with html)

### ISSUE THREAD

**Issue by wang-ories** [dart-lang/site-www#1966]
When editing the HTML source code in this tutorial, https://dart.dev/tutorials/web/low-level-html/connect-dart-html#create-html, the checkbox **Show web content** is not checked by default. The **HTML**, at the upper left of DartPad is not visible. 
**This can be an issue for new dev in Dartpad environment only.**
A little precision in this section can be more helpful.

**Comment by dhanushuUzumaki** [comment]
Hello @kwalrath Can I take this up? Will it be good to have **show web content** enabled by default? https://github.com/dart-lang/dart-pad/blob/0b4156655fc07d18b0ee4f45bfe2e7005ba80e92/web/index.html#L133

Regards,
Dhanushu A P

**Comment by wang-ories** [comment]
Someone already fixing this? I think we can just notify the user to verify that **Show web content** is checked. For those who are familiar with dartpad it is not an issue.

**Comment by kwalrath** [comment]
Sorry for the delay. Since @dhanushuUzumaki asked to handle this, I'll give him first crack.

I think we need to add a new step in the "Create a new Dart app" that explicitly tells the reader to make sure that **Show web content** is selected.

If there's a way to select it automatically, all the better, but I think it's good to make sure that they know that that checkbox needs to be selected.

**Comment by dhanushuUzumaki** [comment]
@kwalrath So I have to Add an explicit message to let the users know they have to enable show web content (https://github.com/dart-lang/site-www/blob/master/src/_tutorials/web/low-level-html/connect-dart-html.md#create-a-new-dart-app-create-dart-app) and also enable it by default. Please let me know if I am misinterpreting this.

Regards,
Dhanushu A P

**Comment by kwalrath** [comment]
That sounds right to me, @dhanushuUzumaki.
