### ISSUE TITLE
'Customizing static analysis' page issue

### ISSUE THREAD

**Issue by UnHumbleBen** [dart-lang/site-www#2138]
Page URL: https://dart.dev/guides/language/analysis-options
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/analysis-options.md

It is not clear what the text 
```
lint • Avoid empty statements • example.dart:11 • empty_statements
```
and
```
lint • Close instances of `dart.core.Sink` • example.dart:11 • close_sinks
```
and
```
error • A value of type 'Object' can't be assigned to a variable of type 'String' • invalid_assignment
```
in the black boxes signify. Are they commands? Outputs? Please provide a description.

**Comment by micpap25** [comment]
`lint` has been changed to `info` in these examples, making it explicit that these are the descriptions given by the analyzer. I think this can be closed.

**Comment by kwalrath** [comment]
We could be clearer, though — especially now that the lint boxes have turned into gray boxes, for some reason. The line # looks wrong in the lint messages, too.

Another problem is that these examples are so long that they push the description of what the page covers ("This document explains...") down beyond the first windowful. 

Maybe we could just have a screenshot of analytics output? Or we could keep the missing semicolon example (deleting the second example), and put the explanation of the analyzer's role in the intro. Something like this:

> For example, if an accidental semicolon makes its way into an `if` statement, the analyzer points to the semicolon and tells you to avoid empty statements:

**Comment by parlough** [comment]
Thanks for the issue and discussion!

I'll close this as fixed by https://github.com/dart-lang/site-www/commit/7377ac6f5f98ccd1e64c2a260e67488787000f99 as I've removed unnecessary information from the warnings and made it more explicit that they are warnings. I've also updated the examples and line numbers to match their expected behavior.

If there's another change you'd like to see on this page, feel free to comment on this issue or open a new one. Thanks again!
