### ISSUE TITLE
First sentence of  "Use proper return types when overriding methods" doesn't accurately explain the new type system rule

### ISSUE THREAD

**Issue by kharland** [dart-lang/site-www#215]
On [this](https://www.dartlang.org/guides/language/sound-dart) page, the first sentence in this section reads:
> The return type of a method in a subclass must be a __proper subtype of the return type of the method in the superclass__.

However, the example does not show that;  Alligator *is* a proper subtype of Animal.  I think what is really being communicated here is that there is some relationship between the superclass and its method types which must also be enforced for any subclass and its method types. 

e.g. the type for the getter `parent` is not actually allowed to be any subtype of the superclass `Animal` as the original sentence states, but it *is* required to be a proper subtype of the class `HoneyBadger` because the superclass's getter's type shares the same type-relation with respect to the superclass.

**Comment by lrhn** [comment]
I agree that the entire section is confusing, and probably wrong.

There is nothing *type-wise* wrong with overriding the `parent` getter to return `Alligator`. It's probably incorrect due to being bad modelling of reality, and there might be other methods depending on `parent` returning something of the same type as the object itself, but that's a contract breach, not a type problem (and it doesn't handle mules).

I must admit that I don't know exactly what "proper return types" means, but the writing is confusing because "proper subtype" does mean something *else* (a subtype that is not the type itself) and that is not the requirement - you can override a method with the *same* return type (which is not a "proper subtype").

All in all, I don't know what the section is trying to say.

**Comment by markuspeloquin** [comment]
The example should be that if Cat's parent() returned Cat, Lion's parent() cannot return Animal/HoneyBadger.

It wonder if there's any value in being able to express that a return type or argument type exactly matches the class it's defined on. You would probably also require overrides in every subclass, though.

**Comment by Sfshaza** [comment]
I believe this is fixed now. Please re-open if you think not.

https://www.dartlang.org/guides/language/sound-dart#use-proper-return-types-when-overriding-methods

**Comment by lrhn** [comment]
It still uses "proper subtype of" incorrectly. It should just be "subtype of", or preferably (following the strcuture for parameters below) "the same type or a subtype of".

**Comment by Sfshaza** [comment]
Thanks for catching that, @lhrn.

Please review: https://github.com/dart-lang/site-www/pull/242
