### ISSUE TITLE
'Asynchronous programming: futures, async, await' page issue

### ISSUE THREAD

**Issue by CheoWalker** [dart-lang/site-www#2198]
Page URL: https://dart.dev/codelabs/async-await.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/codelabs/async-await.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
It mention code examples that are not found on the page.

**Comment by kwalrath** [comment]
@CheoWalker could you tell us which code examples it mentions that aren't on the page? Having strings we can search for will help us know how to fix this bug. Thanks!

**Comment by CheoWalker** [comment]
None of the examples are on the page, just empty code pads.

**Comment by kwalrath** [comment]
Ouch, that sounds like a browser issue. Are you using a browser like Brave that doesn't permit cookies? There's troubleshooting info here: https://dart.dev/tools/dartpad/troubleshoot

**Comment by CheoWalker** [comment]
Latest version of Chrome.

 

The following example shows the wrong way to use an asynchronous function (fetchUserOrder()). Later you’ll fix the example using async and await. Before running this example, try to spot the issue – what do you think the output will be? Is string you can target.

**Comment by kwalrath** [comment]
Could you please send us a screenshot and the contents of the JavaScript console?

**Comment by CheoWalker** [comment]
Here is what I am seeing, I notice the same issue on Flutter.dev as well. 
![Annotation 2020-01-07 140811](https://user-images.githubusercontent.com/4996125/71921634-405d6600-3157-11ea-8089-e6de4a850c48.jpg)

**Comment by kwalrath** [comment]
"Failed to read the 'localStorage' property" is an indication that you have cookies turned off. Can you enable cookies in Chrome? The troubleshooting instructions have a link to a page on turning the cookies on (which you'll need to do for dart.dev & flutter.dev): https://support.google.com/chrome/answer/95647

DartPad depends on local storage, so it doesn't work if cookies are disabled. https://github.com/dart-lang/dart-pad/issues/1237 is an issue for improving the UI when this happens.

I'm going to close this issue, since it's a DartPad problem, but I'll see if we can make the dart-pad bug higher than a P3.

**Comment by CheoWalker** [comment]
Thanks, now I need to figure out my cookies were turned off for dartpad.dev.
