### ISSUE TITLE
Mention initializing final variables using factory constructors

### ISSUE THREAD

**Issue by rkj** [dart-lang/site-www#2202]
https://dart.dev/guides/language/language-tour#factory-constructors

About only time I have used factory constructor is to have a class with final fields, but need some logic in the constructor to initialize them that cannot be expressed in initializer list.

The current documentation for factory constructor mention that it's for cases when implementing a constructor that doesn’t always create a new instance of its class which doesn't cover this use case and is slightly misleading for new users (in my opinion). I had to be hinted initially to use the factory constructor to initialize finals, and also giving code review it also doesn't get through all the time

**Comment by stupendoussuperpowers** [comment]
I'd like to work on this. Can someone guide me to the Language Tour Docs? @kwalrath @rkj

**Comment by kwalrath** [comment]
You're very welcome to give it a try! You can get a link to the source file for the language tour (or any other doc page on dart.dev) at the top right of the page.

**Comment by stupendoussuperpowers** [comment]
Before I submit a PR, just to confirm that the changes I am making align with those wanted in this thread, would a `fromJson` constructor be an adequate example of using factory constructors to initialise variables with custom logic? I ask because as a beginner myself, that's the most frequent use-case for a factory constructor.

`factory Logger.fromJson(Map<dynamic, dynamic> json) {  
     return Logger(  
         name: json['name'],  
     );  
}`
