### ISSUE TITLE
Example doesnt include script src to javascript

### ISSUE THREAD

**Issue by mayberryflavorbox** [dart-lang/site-www#2238]
I tried to use this example and it didn't work.
Meaning - i took the html, css and dart code and put it in my own local project.

https://dart.dev/tutorials/web/fetch-data

It seems to be missing  this at the END of the html file.

  <script src="main.dart.js"></script>

**Comment by kwalrath** [comment]
Ah, yes, the example works in DartPad (as you can see by the embedded DartPad in that page), but that's because DartPad takes care of details like including the script tag.

We should probably link to the directions at https://dart.dev/tutorials/web/get-started and (somewhere) summarize how DartPad code differs from real app code.

**Comment by kwalrath** [comment]
Kind of related: we should update the web tutorial page at https://dart.dev/tutorials/web to acknowledge Flutter's web support (https://flutter.dev/web).
