### ISSUE TITLE
'Iterable collections' page issue – runtimeType comparison in equality? Very weird...

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#2241]
Page URL: https://dart.dev/codelabs/iterables.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/codelabs/iterables.md

See https://stackoverflow.com/q/59952521/39827

It seems **very** weird to have a comparison of `runtimeType` for the equality check.

CC @munificent @lrhn RE best practices

**Comment by lrhn** [comment]
The "best practice" here is disputed territory.

My personal opinion is that you should *never* use `runtimeType` for anything except interacting with `dart:mirrors`.

The *goal* here is to avoid situations where `point == colorPoint` gives true, but `colorPoint == point` gives false.
The consequence is that `point == mockPoint` or `carthesianPoint == polarPoint` are also false, even if they represent the exact same (x,y) position and are interchangeable in all situations,
and the workaround is to make `MockPoint.runtimeType` return `Point`. And then you notice that adding an override of `runtimeType` to any class increases dart2js output size.

We are not the only ones with this problem. Java has exactly the same issue. What Josh Bloch wrote in Effective Java was:
> "So what's the solution? It turns out that this is a fundamental problem of equivalence relations in object-oriented languages. There is simply no way to extend an instantiable class and add an aspect while preserving the equals contract. There is, however, a fine workaround. Follow the advice of Item 14, 'Favor composition over inheritance.' Instead of having ColorPoint extend Point, give ColorPoint a private Point field and a public view method (Item 4) that returns the point at the same position as this color point:"

In C#, the problem is solved by overloading and making `==` not virtual. Operators are static and resolved against both operand types, so `point == colorPoint` will find the best solution among the static `==` operators declared on `Point` and `ColorPoint` which allows `(Point, ColorPoint)` as arguments, so `ColorPoint` can define a `==(Point p, ColorPoint cp)` operator if it wants to, otherwise it will fall back on `Point`'s `==(Point, Point)` operator.
(I like that. C# operators are cool!)

Some people think the `runtimeType` check fixed more issues than it introduces, and in some settings they might be right. It's not a *recommended* approach though.

In any case, the codelab should not do *both* the `is` check and the `runtimeType` check.
I'd prefer if it didn't do the `runtimeType` check.

**Comment by kwalrath** [comment]
Thanks, @kevmoo & @lrhn
