### ISSUE TITLE
404 on dart.dev/performance - has this page ever existed? 

### ISSUE THREAD

**Issue by devinrhode2** [dart-lang/site-www#2276]
I'm not sure if this page has ever existed: http://dart.dev/performance 

This page links to dart.dev/performance: https://news.dartlang.org/2013/12/ecma-forms-tc52-for-dart-standardization.html?m=1

Doesn't actually exist in wayback machine: https://web.archive.org/web/20200601000000*/Dart.dev/performance (the few instances show the 404 page) 

Have not checked the git history of this repo yet

**Comment by kwalrath** [comment]
It existed a very long time ago, back when we used another repo. e.g. https://web.archive.org/web/20130115070042/http://dartlang.org/performance. But I think the specific benchmarks we used weren't terribly relevant to most Dart users, so we took down the page. (See #661 for more info.)

People still try to find it, though. In the last 30 days, it was the 9th most common 404 on dart.dev. Over the entire existence of dart.dev (which was created in May 2019), it's been the 8th most common 404.

Maybe we could add the page back and, for now, point to Flutter performance docs (e.g. https://flutter.dev/docs/perf/rendering/ui-performance), since that covers the majority of our users.

@mit-mit is there any other help we could give people?

**Comment by mit-mit** [comment]
Creating a new /performance page would be a good ideas, but I think we'd need to write some new content for it: general Dart language performance considerations, profile tips etc.

**Comment by kwalrath** [comment]
@mit-mit who'd be a good source for that info?

**Comment by mit-mit** [comment]
Someone from the VM team, I think

**Comment by parlough** [comment]
@mraleph I know you mentioned creating some performance/benchmarking content relatively recently, did any of that come to fruition? Would be useful to use as a reference while working on an updated page.

**Comment by mraleph** [comment]
@parlough I have written this: https://mrale.ph/blog/2021/01/21/microbenchmarking-dart-part-1.html

I have few other things I want to write about but sadly I am very stretched. I would be happy to collaborate with you if you are planning to write a new page.

**Comment by parlough** [comment]
Closing in favor of https://github.com/dart-lang/site-www/issues/4351
