### ISSUE TITLE
/articles/styles.css is ignored

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#228]
Files such as src/_articles/libraries/zones.md that import /articles/styles.css DON'T actually import that file. I suspect that the following YAML is ignored:

```
header:
  css: ["/articles/styles.css"]
```

The workaround would be to put the CSS in the actual file. Much better would be to get `header.css` actually working.

**Comment by chalin** [comment]
I also just came across this problem while working on another page.

The source of the problem is that the page frontmatter YAML doesn't have the shape expected by the `head.html` Liquid code:

https://github.com/dart-lang/site-www/blob/216f446721ba6d2f6b9c60398fa7ced6a3706b9d/src/_includes/head.html#L44-L46

This Liquid code is probably based on the JS script include code:

https://github.com/dart-lang/site-www/blob/216f446721ba6d2f6b9c60398fa7ced6a3706b9d/src/_includes/head.html#L57-L59

which expects page `js` entries to have `defer` and `url` fields. We don't have the need to defer page-specific CSS, so each CSS entry can just be the URL to the CSS file.
