### ISSUE TITLE
Clarify when to use Part directives

### ISSUE THREAD

**Issue by felangel** [dart-lang/site-www#2371]
Can you please clarify what is meant by:

> Note: You may have heard of the part directive, which allows you to split a library into multiple Dart files. We recommend that you avoid using part and create mini libraries instead.

[https://dart.dev/guides/libraries/create-library-packages#organizing-a-library-package](https://dart.dev/guides/libraries/create-library-packages#organizing-a-library-package) 

It’s a bit unclear if part usage is discouraged in general or just in the context of library creation and if so it would be nice to elaborate on the rationale. Happy to open a PR to improve the docs once this has been clarified. Thanks!

**Comment by kwalrath** [comment]
My understanding is that `part` was an early language feature that fell out of common use, except in automatically generated code. Also, the relatively new extension feature can be used in some places where `part` used to be necessary.

Does that sound right, @kevmoo or @munificent? How can we clarify our guidance?

**Comment by kevmoo** [comment]
I don't think there is a lot of overlap between extension members and parts.

My suggested guidance: parts are useful for code generation or cases here
libraries have to be big and should be broken into files.

...but it's pretty rare when a library has to be big. There are many ways
to split things up...

**Comment by munificent** [comment]
I agree with Kevin. Maybe say:

> Note: You may have heard of the part directive, which allows you to split a library into multiple Dart files. Part files are useful for incorporating generated code into a library, but we otherwise recommend that you don't use them.

**Comment by felangel** [comment]
Thanks @kevmoo and @munificent for the clarification! Is there some justification for avoiding parts outside of code generation? I feel there are cases where parts are still very useful. Take the following scenario for example:

```dart
class Foo {...}

class Bar {...}

class MyClass extends Base<Foo, Bar>{...}
```

We can define `Foo` and `Bar` alongside `MyClass` which is fine but might lead to a somewhat bloated file.

I find parts are useful for this sort of scenario because they allow me to separate the implementations of these individual components while still representing them as parts of the whole `MyClass`.

```dart
part 'foo.dart';
part 'bar.dart';

class MyClass extends Base<Foo, Bar> {...}
```

Is there anything "wrong" with this approach? Thanks 🙏

**Comment by jorgecoca** [comment]
The case that @felangel described is what is being used in the [flutter_bloc IDE extensions](https://marketplace.visualstudio.com/items?itemName=FelixAngelov.bloc), and I personally like it a lot, since it makes the integration so much easier, and we do not need a barrel file just for the bloc (+ events and states).

**Comment by munificent** [comment]
The main problems is that those part files:

* Share the same private scope as the library and all other parts.
* Can't contain their own imports.

So you don't get the benefits of being able to reason about each file independently. They are deeply intertwined. It only really lets you break your file into smaller files *textually* but not *conceptually*. In fact, it can end up *more* confusing because the separate files lead you to think things are more encapsulated than they actually are.

Because of that, our experience is that for most users parts don't carry their weight as a feature.

**Comment by atsansone** [comment]
@munificent : Is this still a going concern?

**Comment by munificent** [comment]
I think [this comment](https://github.com/dart-lang/site-www/issues/2371#issuecomment-620261086) is still decent guidance. We don't really want users hand authoring part files. They're much better off using separate libraries and using `export` to compose them. But part files are widely used for generated code.

**Comment by minseok-jeong-gn** [comment]
For 2024 my use,
Just use part for code generation others none.
