### ISSUE TITLE
Remove unnecessary mentions of Observatory

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2429]
I found uses in two files:

```
$ fgrep -Rli observatory src
src/tools/dart-devtools.md
src/tools/dart-vm.md
```

The dart-devtools mention appears to still be valid, for now (it's output), but I should check whether the output is the same and whether there's a bug filed for that. The dart-vm mention should go, in favor of Dart DevTools, I think.

**Comment by parlough** [comment]
I'm going to consider this particular issue fixed by https://github.com/dart-lang/site-www/commit/599fc0813d2d52f7b463253e11d288baeea77d25 which removed the observatory mentions from the `dart-vm` page.

The remaining observatory mention is within the `dart-devtools` page and with the latest dev releases is still valid.
