### ISSUE TITLE
'Fixing common type problems' page issue

### ISSUE THREAD

**Issue by dark-chocolate** [dart-lang/site-www#2439]
Page URL: https://dart.dev/guides/language/sound-problems
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/sound-problems.md

### Description of issue:

Quoting the example of [Invalid casts](https://dart.dev/guides/language/sound-problems#invalid-casts)

```
assumeStrings(List<Object> objects) {
  List<String> strings = objects; // Runtime downcast check
  String string = strings[0]; // Expect a String value
}
```

If you pass `List<String>` to` assumeStrings()` method, it fails at runtime. 

```
assumeStrings(['1', '2']); // runtime error
```

But documentation says 

> The assignment to strings is downcasting the List<Object> to List<String> implicitly (as if you wrote as List<String>), so if the value you pass in objects at runtime is a List<String>, then the cast succeeds.

**Comment by dev-aentgs** [comment]
@dark-chocolate ,
When you specify list literal without `<String>`, the type is considered as dynamic.
`Uncaught Error: TypeError: Instance of 'JSArray<dynamic>': type 'JSArray<dynamic>' is not a subtype of type 'List<String>'`

Try this `assumeStrings(<String>['1','2']);`

**Comment by dark-chocolate** [comment]
@dev-aentgs 

Yes,` assumeStrings(<String>['1','2']);` worked.

But I don't understand one thing, when creating a list variable, it works but when directly using it in parameters, it fails. 

```
final list = ['1', '2']; // inferred as List<String>
assumeStrings(list); // works
```

**Comment by dev-aentgs** [comment]
@dark-chocolate ,
Not sure but I think the reason is that Dart type inference needs some context; either `initialization` or `explicit cast` to determine the correct `type` at runtime. 

Reading through [effective dart](https://dart.dev/guides/language/effective-dart/design#avoid-redundant-type-arguments-on-generic-invocations) it states 
> 
`var things = Set();`
Here, since the variable has no type annotation, there isn’t enough context to determine what kind of Set to create, so the type argument should be provided explicitly.
`var things = Set<String>();`
>
