### ISSUE TITLE
Requesting example of Strong Mode type inference with Maps

### ISSUE THREAD

**Issue by sethladd** [dart-lang/site-www#257]
_From @sethladd on March 17, 2017 16:2_

I checked out https://www.dartlang.org/guides/language/sound-dart#type-inference and I was hoping to find more examples of inference with collections and generics.

For example, how would I rewrite this code in strong mode? `Map<String, dynamic> arguments = { 'argA': 'hello', 'argB': 42 };`

and:

```
 Map<String, dynamic> message = {
      'method': 'someMethod',
      'args': <Map<String, dynamic>>[arguments],
    };
```

and:

```
List<dynamic> arguments = methodCall['args'];
```

Can I use var in all those cases, and get the same variable type as what's explicitly annotated?

_Copied from original issue: dart-lang/site-webdev#467_

**Comment by sethladd** [comment]
_From @chalin on March 17, 2017 16:22_

Hi Seth. Did you really intend to open this issue here over webdev? Or was it meant for `site-www`?

cc @kwalrath

**Comment by sethladd** [comment]
oops! sorry. I meant site-www. I'll move it. Thanks!

**Comment by sethladd** [comment]
cc @Sfshaza @leafpetersen

**Comment by Sfshaza** [comment]
@munificent

**Comment by munificent** [comment]
```dart
Map<String, dynamic> arguments = { 'argA': 'hello', 'argB': 42 };
```

If you use `var` here, then the map literal infers its type from the elements. The keys are both strings. Since the values have different types (string and int), you get the least upper bound of those, which is Object. So the map has type Map<String, Object> and then `arguments` gets the same type by inferring it from its initializer.

```dart
Map<String, dynamic> message = {
  'method': 'someMethod',
  'args': <Map<String, dynamic>>[arguments],
};
```

Same deal as above. The map has type Map<String, Object> and `message` will have that same type of you use `var`.

```dart
List<dynamic> arguments = methodCall['args'];
```

This depends on what the type of `methodCall` and its subscript operator is.
