### ISSUE TITLE
'The Dart type system' page issue

### ISSUE THREAD

**Issue by dark-chocolate** [dart-lang/site-www#2590]
Page URL: https://dart.dev/guides/language/type-system
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/type-system.md

**Description of issue:**

Referencing the code provided [here](https://dart.dev/guides/language/type-system#generic-type-assignment)

```
List<Cat> myCats = List<Animal>();
```
>This assignment passes static analysis, but it creates an implicit cast. It is equivalent to:

```
List<Cat> myCats = List<Animal>() as List<Cat>;
```
> The code may fail at runtime.

According to my limited understanding of Dart, both the codes will always fail at runtime. So, either we should show a compile time error when assigning a `List<Animal>` to `List<Cat>` (which is nicely handled by Dart 2.9 when enabling NNBD experiment) or the language could be written as `The code fails at runtime`. But the former is preferred.

**Comment by kwalrath** [comment]
This might be something that worked in 1.X and even early 2.X, but not any more. @mit-mit who'd be a good person to ask?

**Comment by mit-mit** [comment]
cc @lrhn

**Comment by lrhn** [comment]
With null safety, it's going to be an all-out error fest!
```dart
List<Cat> myCats = List<Animal>();
```
It'd be an implicit downcast (which will indeed always fail at runtime). 
Implicit downcasts are going away, so it'd bea compile-time error. 
Would be, if you ignore that the `List` constructor is going away with null safety, so it'll fail to compile even before it gets to type checking.

So, for pre-null safety, the text should be something like "The code always fails at runtime. Because of Dart's reified generics, an instance of  `List<Animal>` is not a `List<Cat>`, not even if it contains only cats (or nothing)."

Post null-safety, the entire page should probably be rewritten.
