### ISSUE TITLE
Fix commented-out error messages in "Fixing common type problems"

### ISSUE THREAD

**Issue by RaenonX** [dart-lang/site-www#2618]
See #2619 and comments below for details.

Original comment:

> [Render errors] Starting from this section
> 
> https://dart.dev/guides/language/sound-problems#unexpected-collection-element-type

**Comment by kwalrath** [comment]
Yikes. Thanks for letting us know, @RaenonX!

**Comment by kwalrath** [comment]
The problem happened sometime between July 28 & August 31, probably due to #2575 (or possibly #2591).

I'm going to make a quick workaround, but we should take a longer look at this page and perhaps bring it back to [what it was July 28](https://web.archive.org/web/20200728213004/https://dart.dev/guides/language/sound-problems).
