### ISSUE TITLE
Document common issues wrt null safety migration/mixed-mode

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2642]
Depending on how people will find/research these issues, this doc could be in one of two places:

* https://dart.dev/tools/diagnostic-messages (if people will find these issues only via static analysis).
* a new page that's similar to [Fixing common type problems](https://dart.dev/guides/language/sound-problems). diagnostic-messages would still have some info, but would link to this new page so that we don't document the fixes twice.

We might do some combination, with a new page covering planning and tools, and diagnostic-messages covering specific cases that are caught by static analysis. If we create a new page, we'll need a list of use cases, with before-and-after examples, to structure this page around.

Related: #2628, https://github.com/dart-lang/sdk/issues/43452

/cc @bwilkerson @stereotype441

**Comment by stereotype441** [comment]
Here's a concrete example of this (based on https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/image_provider.dart).  @kwalrath let me know if this is the kind of information you're looking for.  It's a real world example, with all the complexity that real world examples tend to entail, so feel free to adapt/simplify this example as needed.

Prior to migration the code looked like this:
```dart
  /// Fetches the image from the asset bundle, decodes it, and returns a
  /// corresponding [ImageInfo] object.
  ///
  /// This function is used by [load].
  @protected
  Future<ui.Codec> _loadAsync(AssetBundleImageKey key, DecoderCallback decode) async {
    ByteData data;
    // Hot reload/restart could change whether an asset bundle or key in a
    // bundle are available, or if it is a network backed bundle.
    try {
      data = await key.bundle.load(key.name);
    } on FlutterError {
      PaintingBinding.instance.imageCache.evict(key);
      rethrow;
    }
    if (data == null) { // (1)
      PaintingBinding.instance.imageCache.evict(key);
      throw StateError('Unable to read data');
    }
    return await decode(data.buffer.asUint8List()); // (2)
  }
```

`key.bundle.load` is a method belonging to the Flutter framework that never returns `null`.  However, it might be overridden by a user-provided method, and that method might return null.  So Flutter has a defensive check at (1) to make sure that if that happens, (a) the key gets evicted from the image cache, and (b) the user gets a useful error message.  If they didn't have this defensive code, an exception would be thrown when `data` is accessed at (2), but it would be a less useful error message, and the key wouldn't be properly evicted from the image cache.

When migrating this code, the Flutter folks gave `key.bundle.load` a non-nullable return type, because it's never supposed to return `null`.  And they migrated the `_loadAsync` method like so:
```dart
  /// Fetches the image from the asset bundle, decodes it, and returns a
  /// corresponding [ImageInfo] object.
  ///
  /// This function is used by [load].
  @protected
  Future<ui.Codec> _loadAsync(AssetBundleImageKey key, DecoderCallback decode) async {
    ByteData? data;
    // Hot reload/restart could change whether an asset bundle or key in a
    // bundle are available, or if it is a network backed bundle.
    try {
      data = await key.bundle.load(key.name);
    } on FlutterError {
      PaintingBinding.instance!.imageCache!.evict(key);
      rethrow;
    }
    if (data == null) { // (1)
      PaintingBinding.instance!.imageCache!.evict(key);
      throw StateError('Unable to read data');
    }
    return await decode(data.buffer.asUint8List()); // (2)
  }
```

However, this created a problem.  Since `key.bundle.load` has a non-nullable return type, flow analysis reasons that when execution reaches (1), `data` will be non-null, so the body of the `if` statement is dead code; accordingly, the analyzer gives a hint.  Currently it gives a `dead_code` hint, but we're going to change it to something else so that the hint message can point the user to this mixed-mode unsoundness issue (https://github.com/dart-lang/sdk/issues/43452).  We might also change it to a warning rather than a hint.

Now, the analyzer says the body of the `if` statement is dead.  But is it really dead?  What if the user provides their own `key.bundle.load` method and it returns `null`?  If the user's code has null safety enabled, then that can't happen, because a method returning a non-nullable type can't be overridden by a method returning a nullable type.  But if the user's code *doesn't* have null safety enabled yet, there's nothing to stop their method from returning `null`.

We think it's really bad if the developer of a framework or package (like Flutter) thinks that a certain code path is impossible due to null safety, but it's actually possible if one of *their* users doesn't have null safety enabled.  So when the compiler compiles the above code, it actually treats it as though it were written like this (or at least, it will as soon as https://dart-review.googlesource.com/c/sdk/+/162004 lands):

```dart
  /// Fetches the image from the asset bundle, decodes it, and returns a
  /// corresponding [ImageInfo] object.
  ///
  /// This function is used by [load].
  @protected
  Future<ui.Codec> _loadAsync(AssetBundleImageKey key, DecoderCallback decode) async {
    ByteData? data;
    // Hot reload/restart could change whether an asset bundle or key in a
    // bundle are available, or if it is a network backed bundle.
    try {
      data = await key.bundle.load(key.name);
    } on FlutterError {
      PaintingBinding.instance!.imageCache!.evict(key);
      rethrow;
    }
    if (data == null) { // (1)
      throw UnsoundnessError(); // *** ADDED BY THE COMPILER ***
      PaintingBinding.instance!.imageCache!.evict(key);
      throw StateError('Unable to read data');
    }
    return await decode(data.buffer.asUint8List()); // (2)
  }
```
In general, adding the `throw` statement is good for both the Flutter developers and Flutter users.  For the Flutter developers, it's good because it means the analyzer isn't lying to them; it says the code is dead, and it really is dead (thanks to the inserted `throw`).  For Flutter users, it's good because it means that if they override Flutter code in a way that breaks its null safety assumptions, they'll get an exception.  (Note that the name `UnsoundnessError` may change; we haven't really had a chance to discuss what it should be called or what the exception message should be).

For most users, what we want to recommend is, if you have dead code after you migrated, look at that code and decide whether it's doing something essential, or whether it's just defending against accidental nulls.  If it's doing something essential, then you made a mistake in your migration, marking something as non-nullable when it's actually nullable, so you'll have to go fix that.  If it's just defending against accidental nulls, then probably you just want to delete it, because the whole idea of null safety is that you shouldn't have to worry about defending against accidental nulls anymore.  So for this example, the user would just drop the `if` statement entirely, and be left with:

```dart
  /// Fetches the image from the asset bundle, decodes it, and returns a
  /// corresponding [ImageInfo] object.
  ///
  /// This function is used by [load].
  @protected
  Future<ui.Codec> _loadAsync(AssetBundleImageKey key, DecoderCallback decode) async {
    ByteData? data;
    // Hot reload/restart could change whether an asset bundle or key in a
    // bundle are available, or if it is a network backed bundle.
    try {
      data = await key.bundle.load(key.name);
    } on FlutterError {
      PaintingBinding.instance!.imageCache!.evict(key);
      rethrow;
    }
    return await decode(data.buffer.asUint8List()); // (2)
  }
```

We think this is going to be good enough for most users.  Even though the defensive code is gone, there's not a terribly large difference in behavior.  In this case, the exception doesn't happen until slightly later (at (2)), and it's a slightly less useful exception, and the key doesn't get evicted from the image cache anymore.

But the developers of Flutter (and other heavily used packages and frameworks) are going to want another option.  They're going to want a way to keep their defensive code for the benefit of their users who haven't started using null safety yet.  For them, what we're going to recommend doing is adding an `as dynamic` to the `if` statement, like so:
```dart
  /// Fetches the image from the asset bundle, decodes it, and returns a
  /// corresponding [ImageInfo] object.
  ///
  /// This function is used by [load].
  @protected
  Future<ui.Codec> _loadAsync(AssetBundleImageKey key, DecoderCallback decode) async {
    ByteData? data;
    // Hot reload/restart could change whether an asset bundle or key in a
    // bundle are available, or if it is a network backed bundle.
    try {
      data = await key.bundle.load(key.name);
    } on FlutterError {
      PaintingBinding.instance!.imageCache!.evict(key);
      rethrow;
    }
    if ((data as dynamic) == null) { // (1)
      PaintingBinding.instance!.imageCache!.evict(key);
      throw StateError('Unable to read data');
    }
    return await decode(data.buffer.asUint8List()); // (2)
  }
```

Adding `as dynamic` hides the fact that `data` is non-nullable from flow analysis, so flow analysis no longer notices that it's dead code.  That means that the warning goes away, and the compiler stops inserting a `throw` statement.  So the Flutter developers get to keep their defensive code for the benefit of users that haven't started using null safety yet.

In the future, when we get to Dart 3.0 and null safety is required for all code, the defensive code will truly be dead and the Flutter developers will want to get rid of it.  When that happens, we intend to add a lint that will detect the `if ((data as dynamic) == null)` pattern, so that Flutter developers can find cases like this and remove them.

Ok! That's a long detailed example involving an `== null` check.  There are three other cases that could probably use discussion:
- `is` checks
- `??` and `??=` operations
- `?.` and `?..` operations

I'll dig around and try to find some real-world examples of those.  If I can't find any, we might have to make something up.

**Comment by kwalrath** [comment]
That _is_ longer than I'd normally include in a doc page, but I suspect we can use it as the basis of a simpler example. I'm looking forward to the examples of the other 3 cases. Thanks, @stereotype441!

**Comment by stereotype441** [comment]
Hmm, I'm having a lot of trouble finding examples in the other categories!  AFAICT, *all* of the instances of this issue in Flutter use `== null` or `!= null` checks.  I broadened my search to other packages that have been migrated so far, and again found nothing.

The only place where I've found examples that didn't involve `== null` or `!= null` checks is in the Dart SDK itself, and they're not very informative.  For example, this function from `sdk/lib/_internal/js_dev_runtime/private/native_typed_data.dart`:
```dart
void _invalidPosition(int position, int length, String name) {
  if (position is! int) {
    throw ArgumentError.value(position, name, 'Invalid list position');
  } else {
    throw RangeError.range(position, 0, length, name);
  }
}
```

The story is pretty much identical to the Flutter example I gave above, except that for some bizarre reason the code is using `if (position is! int)` to trigger the defensive code rather than `if (position == null)`.  Why?  I don't know.  @lrhn speculated (when looking at some similar code elsewhere in the SDK) that the check was inherited from the Dart 1.x days, when Dart's type system wasn't sound, so checking `if (position is! int)` was better because it caught all cases of passing a non-integer value to the function, not just nulls.  But since Dart 2.0, there's been no real benefit to using an `is` check to guard against null rather than an `== null` check, so it seems silly to go out of our way to document this scenario today.

All of the other examples in the SDK seem to be the same story.  So with *zero* realistic examples of this situation arising for anything other than `== null` and `!= null` comparisons, I'm going to go out on a limb and say that our documentation should just address `== null` and `!= null` comparisons.  I suppose if we wanted to cover our bases really thoroughly we could always have a paragraph at the bottom that says "similar issues can arise with `is` tests, `??`, `??=`, `?.` and `?..`", but I suspect that would confuse more users than it helped.  @kwalrath @leafpetersen @bwilkerson what do y'all think?

**Comment by leafpetersen** [comment]
My general take on this is that while we may want some "advanced mode" docs for true power users, for most people a very simple example and a very simple explanation is warranted.  Specifically, I think we should say something like the following, which would be linked to from certain warnings around dead code/unnecessary casts, and is used to document the exception that is thrown by the inserted reachability guards.

```
The Dart tools will issue warnings in code when you put null checks and a few other kinds of checks [footnote link here to small list of constructs?] that can never be needed in a null safe program.  [Small example here].  Since the variable in [reference to example] is declared non-nullable, it can never be `null` at runtime, and so the check here [reference to example] can never succeed in a fully null safe program.  However, because Dart supports running programs that are a mix of null safe and non-null safe code, a non-null safe part of the program can cause a `null` to appear where it would otherwise be impossible in a fully null safe program.  To guard against this, Dart will insert an assertion after checks like the one in [reference example here] or the cases below which will throw an exception if a null has snuck in from non null-safe code.  If you are seeing the [Insert name of exception here], this is because a null has been passed from non null safe code to one of these locations.  If for some reasons you feel that it is important to catch and handle a null value in such a location (even though in fully null safe code this check will be unnecessary), you can use the patterns described here [link to short description of patterns].
```

WDYT?

**Comment by kwalrath** [comment]
(I edited Leaf's comment so it was easier to read in the GitHub UI.)

Agreed, a simple example is probably what we want. We can point to more complex examples if necessary.

/cc @RedBrogdon, who's coordinating null safety example work

**Comment by leafpetersen** [comment]
FYI - We're currently pushing on an alternative approach that eliminates most of the user facing complexity described here, so this issue may be greatly downscoped.  Essentially, we will add an implicit `default` case with a `throw` to switches over non-nullable types which don't already have a default, and we will add an implicit `throw` after expression statements of type `Never` (e.g. calls to a function which claims to never return).

**Comment by stereotype441** [comment]
Ok, we've landed the updated approach.  Considering my example above:
```dart
  /// Fetches the image from the asset bundle, decodes it, and returns a
  /// corresponding [ImageInfo] object.
  ///
  /// This function is used by [load].
  @protected
  Future<ui.Codec> _loadAsync(AssetBundleImageKey key, DecoderCallback decode) async {
    ByteData? data;
    // Hot reload/restart could change whether an asset bundle or key in a
    // bundle are available, or if it is a network backed bundle.
    try {
      data = await key.bundle.load(key.name);
    } on FlutterError {
      PaintingBinding.instance!.imageCache!.evict(key);
      rethrow;
    }
    if (data == null) { // (1)
      PaintingBinding.instance!.imageCache!.evict(key);
      throw StateError('Unable to read data');
    }
    return await decode(data.buffer.asUint8List()); // (2)
  }
```
What we've decided is that flow analysis no longer considers code to be unreachable due to an "impossible" null check.  So even though `data` is definitely assigned a value whose type is non-nullable `ByteData`, and that *seems* like it should mean that `data == null` can never evaluate to `true` at (1), flow analysis knows that actually, it still *can*, because the `key.bundle.load` might be implemented in unmigrated code.  So the code inside the `if` statement at (1) isn't considered dead code.  This is nice because it means that users can migrate their null-safe code in an intuitive way, and it has the behavior they want.

There will be a warning in the migration tool at (1) telling them that in strong mode, this `if` test is redundant, and a similar hint in the analyzer once the code is migrated.  I suppose it's possible that we still might want to link that hint to some user-facing documentation explaining about mixed mode unsoundness, but honestly I'm not sure if it's worth it.  The behavior is now so much closer to what the user intuitively wants* that we can probably just leave things alone.

(*And I'm not just speculating about what the user intuitively wants; this is how the Flutter folks have preferred to migrate their code.)

**Comment by kwalrath** [comment]
I've marked this as blocked since we don't know if we need it.

**Comment by parlough** [comment]
Taking a look at the discourse here and the current fleshed out state of the analyzer diagnostics and their related documentation, as well as the lack of further concern since null safety was released, I feel we can maybe close this issue.

If we still do want to add a small note or warning about migration somewhere, I appreciate @lrhn's suggestion of creating and using a consistent function across your codebase to handle this situation: https://github.com/dart-lang/sdk/issues/46907#issuecomment-900119629

His suggested function could also be expanded to accept an optional function for any extra behavior the caller may need.
