### ISSUE TITLE
"RVM is not a function..." when running `source ./tool/env-set.sh`

### ISSUE THREAD

**Issue by munificent** [dart-lang/site-www#2685]
I'm trying to build and run the site locally on my Mac. I'm running Catalina, which changes the default shell to zsh. When I run the instructions in the README.md, I get:

```
~/dev/site-www → source ./tool/env-set.sh
Setting environment variables from tool/env-set.sh
v12.18.4 is already installed.
Now using node v12.18.4 (npm v6.14.6)
RVM current: ruby-2.4.3
Running: rvm use ruby-2.6.5

RVM is not a function, selecting rubies with 'rvm use ...' will not work.

You need to change your terminal emulator preferences to allow login shell.
Sometimes it is required to use `/bin/bash --login` as the command.
Please visit https://rvm.io/integration/gnome-terminal/ for an example.

Ruby --version: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
INFO: git config push.recurseSubmodules is set to check.
INFO: git config status.submodulesummary is set to 1.
```

I've tried poking around in the various shell scripts, but I'm way out of my league there. It does seem like I can work around it by running the suggested:

```
/bin/bash --login
```

And then doing everything inside that bash session. But that feels a little weird? Maybe we should just update the docs to specify that?

**Comment by kwalrath** [comment]
@johnpryan what do you think we should do?

**Comment by johnpryan** [comment]
Running `/bin/bash --login` will process `~/.bashrc`, `~/.bash_profile`, or `~/.profile`, which will set up NVM and RVM if you have them installed:

```
# $HOME/.profile

# RVM
export PATH="$PATH:$HOME/.rvm/bin"
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
```

For reasons unknown, I can't run `bin/bash --login`, I need to manually run `/bin/bash` and `source ~/.profile` to load NVM and RVM.

We might want to add the `/bin/bash --login` or `/bin/bash && source ~/.YOUR_PROFILE_FILE_WITH_RVM_AND_NVM` to the README.

Longer-term, we might consider using Docker, which is simpler to use but uses more resources.

**Comment by kwalrath** [comment]
Whatever we do, it should work for flutter/website, too... and I think their requirements are worse than ours, due to a (rvm?) version mismatch with flutter/flutter. Docker is sounding better and better.

/cc @sfshaza2

**Comment by sfshaza2** [comment]
That's probably true.. I'm on Catalina but am still using Bash.

**Comment by chalin** [comment]
Hi all. We faced this issue a while back (_Either support zsh or clarify that only bash is supported_ #2080) and the decision made back then was:

> We can't justify supporting zsh at this time, but we should clarify that the scripts expect bash.

There is a note in the README stating that the instructions work for bash and that YMMV with other shells.

> ... It does seem like I can work around it by running the suggested:
> 
> ```
> /bin/bash --login
> ```
> 
> And then doing everything inside that bash session. But that feels a little weird? Maybe we should just update the docs to specify that?

Mentioning the need to run `/bin/bash --login` certainly seems reasonable.

I did look into making the build scripts zsh compatible last year, and IIRC the main issue we had hit back then was due to the redefinition of `travis-fold`. (Also, IIRC I had found a zsh workaround for that, but dropped it given the decision to stick with bash. So my _feeling_ is that we aren't far from being able to support zsh.)

> Whatever we do, it should work for flutter/website, too... and I think their requirements are worse than ours, due to a (rvm?) version mismatch with flutter/flutter. Docker is sounding better and better.

Sounds like flutter/website is overdue for a Ruby version upgrade? (And maybe site-www too?) Most times, upgrading Ruby is fairly painless, but other times (when gems have major version upgrades that aren't necessarily backwards compatible) not 😄 🤷‍♂️ .

**Comment by munificent** [comment]
Maybe a silly question because I don't have much context, but... is there a reason an almost-entirely static-generated site requires Node, Ruby, Dart, Bash, and Firebase? Could the build stack be simplified?

**Comment by chalin** [comment]
> ... almost-entirely static-generated site requires Node, Ruby, Dart, Bash, and Firebase? Could the build stack be simplified?

Well, ...

- Jekyll needs Ruby
- The site is hosted on Firebase, hence the need for the corresponding Node packages
- Some of the site updates scripts (e.g., TOC, code-excerpt sync) are written in Dart
- We need to support at least one shell / environment. Bash was the obvious choice until recently.

A word about Docker, since Kathy mentioned it earlier. Flutter/website was switched over to Docker, but we never quite figured out how to allow non-Googlers (like me :) to easily apply deltas (on a per remote-PR-build-job basis) or make any changes to the container config, so use of Docker was abandoned -- since at the time I was doing some nontrivial updates to the site infrastructure. Docker seemed like an overkill to me, but that was just an initial impression (disclaimer: I haven't worked with Docker very much).

All that being said, if one of you would like to try making the setup work with zsh, I can offer some pointers. I can also give it a try myself some time in this quarter. I don't think that it should be too much effort, but you know how these things turn out sometimes :).

**Comment by kwalrath** [comment]
Closing in favor of #2917.
