### ISSUE TITLE
Update diagnostic messages

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#2731]
How-to instructions here: https://github.com/dart-lang/site-www/issues/1949#issuecomment-535257768

**Comment by parlough** [comment]
I'm assuming this issue was for a specific point that the diagnostic messages page was out of date like https://github.com/dart-lang/site-www/issues/1892 was. 

So I'll close this in favor of the issue to automate the update process. I've also included the most recent changes in https://github.com/dart-lang/site-www/pull/3496
