### ISSUE TITLE
Document preference of placement of consts

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/site-www#2762]
Would it be useful to make Effective Dart opinionated on the placement of constants?

@cskau-g and I identified two types of common constants:

1. Non-reusable constants
2. Reusable constants

Non-reusable constants are often separated out from a function, but only used in that function. Moving the constant outside the function creates a smaller function body. However, it makes the constant available to all the functions in the class or module. (Or if not starting with `_` to everything that imports the module.)

* Should we prefer nesting the constants in the function body or not?
* And if not nested in the function body, should the constant stay close to its use in the file, or move to the top of the scope it is available in?

For reusable constants:

* Should the constant definition stay close to its (initial) uses or be moved to the top of the scope (class or module)?

Prior art: [Google C++ style guide](https://google.github.io/styleguide/cppguide.html#Declaration_Order)

> Within each section, prefer grouping similar kinds of declarations together, and prefer the following order: types (including typedef, using, and nested structs and classes), constants, factory functions, constructors and assignment operators, destructor, all other methods, data members.

In the C++ style guide constants come after typedefs but before any other code (at least within classes).

**Comment by kwalrath** [comment]
@munificent what do you say?

**Comment by munificent** [comment]
We have generally stayed away from mandating an ordering in "Effective Dart" because it gets complicated really quickly. Should a getter be next to its backing field, or with other getters? Should private members be together regardless of what kind they are, or should members be grouped by kind first and then privacy? Are static members separated from instance members? Overrides? Abstract members?

We've generally felt that any particular ordering doesn't matter that much (people heavily rely on their editor/IDE for navigation) and, when it does matter, its best to give class maintainers some freedom to order things in a way that feels natural.

As far as constants go, I think the general software engineering principle of minimizing the scope of an entity applies. "Effective Dart" doesn't try to be an all-encompassing list of software engineering guidelines, because then it would be huge.
