### ISSUE TITLE
Clarify docs: "Switch statements in Dart are intended for limited circumstances, such as in interpreters or scanners"

### ISSUE THREAD

**Issue by DanTup** [dart-lang/site-www#2830]
This came up [on reddit](https://www.reddit.com/r/dartlang/comments/kovzd3/why_switch_statements_in_dart_are_intended_for/). The [language tour says about switch statements](https://dart.dev/guides/language/language-tour#switch-and-case):

> **Note:** Switch statements in Dart are intended for limited circumstances, such as in interpreters or scanners.

It's not very clear what this means. Should they be avoided? If so, what is the actual reason (and could it be explained on the site)? What's special about interpreters/scanners that doesn't apply to general code?

I looked at the history to see if there are any clues, but it seems like this text was in first commit for the migration of the site 5 years ago.

**Comment by kwalrath** [comment]
I don't recall the history of this, but a little sleuthing shows that I made the change (as a set of post-1.0 language changes) and Gilad Bracha reviewed it: https://chromiumcodereview.appspot.com/757003003.

@lrhn or @leafpetersen can you provide any guidance?

**Comment by lrhn** [comment]
Gilad did not like switch statements. I think that's the entirety of the story.
The phrase also occurs in the language specification:
> ```latex
> \commentary{
> The \SWITCH{} statement should only be used in
> very limited situations (e.g., interpreters or scanners).
> }
> ```

I understand that switch statements are often considered "dirty" in object oriented language (you should just have a method on the object and call that instead, internal dispatch instead of external switching). That does require a class per object you want to recognize, which can be quite heavyweight.
I also think Dart is more multiparadigmatic than just object oriented, and switches (often through pattern matching) are very much used in functional programming.

All in all, I'd just remove the sentence. It is quite possible to misuse switch statements for something where proper object oriented programming is better, but it's possible to misuse any language feature &mdash; and I gladly do so! We don't generally try to make people avoid a feature unless we actually want that feature to change or go away.
We have switch statements, we're not going to remove them, and we might actually improve them (perhaps with pattern matching). We should treat them as a first class language feature, not a second-class citizens.

**Comment by kwalrath** [comment]
Thanks, @lrhn and @DanTup!

**Comment by DanTup** [comment]
Great, thanks!
