### ISSUE TITLE
Remove travis_fold to support ZSH

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/site-www#2917]
Once we are migrated from Travis CI to Actions, we can remove any `travis_fold` statements from the codebase and update the README.

The reason travis_fold doesn't work in ZSH is that `env-set.sh` attempts to export a shim using `export -f`, which ZSH [doesn't support](https://superuser.com/questions/1515680/export-f-equivalent-in-zsh):

```sh
  if ! __type_t travis_fold > /dev/null; then
    # In case this is being run locally. Turn travis_fold into a noop.
    travis_fold() { true; }
  fi
  export -f travis_fold > /dev/null
```

cc: @athomas

**Comment by kwalrath** [comment]
Travis -> GHA work is happening in #2921

**Comment by johnpryan** [comment]
It looks like once that is merged, we can update the README to indicate that ZSH is supported.

**Comment by kwalrath** [comment]
Still some occurrences, but I think that's only because flutter/website hasn't been switched to GHA yet.

```
$ fgrep -Rl travis_fold tool
tool/install.sh
tool/shared/install.sh
tool/shared/before-install.sh
tool/shared/env-set.sh
tool/shared/install-dart-sdk.sh
```

**Comment by athomas** [comment]
Yes, some of those scripts very much emulate "Travis stages" and I didn't carry that over into GitHub Actions. I did that partly because they tend to rely on exporting variables from one script to the next which would've needed extra work and because they were shared with other repos still using Travis. With the migration of the flutter website, some might not be needed anymore (especially if we'd switch over to a dockerfile-based approach).

**Comment by kevmoo** [comment]
Gah! I'm hitting this now. Makes me very sad.

We're migrated to actions now, right?
