### ISSUE TITLE
Clarify guideline for when to define a getter

### ISSUE THREAD

**Issue by munificent** [dart-lang/site-www#298]
It's not clear if the bullet list for [the guideline](https://www.dartlang.org/guides/language/effective-dart/design#do-use-getters-for-operations-that-conceptually-access-properties) is meant to completely define which members are "conceptual properties" or whether it only comes into play *after* the user has decided the member is one.

The intent was to be the former, but the text doesn't state that, and I don't think the bullet list is complete enough for that to be true. In particular, according to the rules, `toString()` should be a getter. We should probably add another bullet or two stating that things like conversions or members where you want the reader to focus on the work done to produce the value more than the value itself can still be methods.

**Comment by lrhn** [comment]
Agree that it could be explained better.

It's hard to define when something is "a property" of an object. Direct access to instance fields is simple, but potentially too specific (if I store flags in an int, revealing the int would break abstraction, you want individual boolean properties). That's where the "logically" comes in, even if it isn't explained either.
If a class represents a logical concept, properties are the questions you can ask about that object: 
>  How long is the list? What is the fifth element? Is it empty?

That doesn't include questions like "What is the string representation of the list?" because that introduces a new *concept*, the "string representation", and that is the concept you are querying, not the list. A string representation of a list has some properties too, and it's not the same as a string representation of an integer - they are both strings, but they are also different concepts (concepts are not the same as classes, we have relative URIs and absolute URIs both represented by the class `Uri`, different concepts, same class).
So, it's all about "is this a property of the concept represented by this class"?

So the `toString` is indeed a "conversion", to a string representation. The string representation is not logically a property of the object.
Similarly, wrappers like `List.asMap()` is generally treated as conversions (I'm not absolutely sure I agree in all cases, but that's the convention).
