### ISSUE TITLE
Support images for social sharing

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#305]
As the discussion in https://github.com/dart-lang/site-webdev/pull/759 points out, the `snippet_img` isn't used. I suspect the same is true for site-www.

**Comment by kwalrath** [comment]
Not only is it not used in www, but we've lost the image files for the couple of files that
do specify snippet images.

```
$ fgrep -r snippet_img *
src/community/who-uses-dart.md:snippet_img: images/who-uses-dart.png
src/resources/synonyms/index.md:snippet_img: images/dart-synonym-screenshot.png
$ grep who-uses-dart.png publish/community/*
$ find . -name who-uses-dart.png
$
```

**Comment by Sfshaza** [comment]
Oops

**Comment by chalin** [comment]
A few notes:
- Originally when @filiph added support for Open Graph meta data a year ago (via https://github.com/dart-lang/site-www/commit/a51a6c31a287775134deb794ccf7d061f2fd2486) the default image was the [[x] Dart](https://www.dartlang.org/assets/logo-61576b6c2423c80422c986036ead4a7fc64c70edd7639c6171eba19e992c87d9.svg) logo. 

  Currently it is https://www.dartlang.org/samples/images/frontpage-sample.png, but that doesn't seem like the best choice since it ends up looking like this in a post:
  > ![screen shot 2017-07-08 at 11 28 00 am](https://user-images.githubusercontent.com/4140793/27986734-e9dfeac4-63d0-11e7-9013-bc04c55bd866.png)

- The Get Started page has its own `og:image` that makes a post of this page look like the following, which isn't too bad an image, but its content is small:
  > ![screen shot 2017-07-08 at 11 32 14 am](https://user-images.githubusercontent.com/4140793/27986752-2bd3a286-63d1-11e7-9622-e28229c36050.png)

- The `community/who-uses-dart.md` page used to be bound to [this image](https://github.com/dart-lang/site-www/blob/208e7990cb1a72b900ed22ea0db164ba5120cab2/src/_assets/images/who-uses-dart.png) (which was deleted by @filiph in https://github.com/dart-lang/site-www/commit/a51a6c31a287775134deb794ccf7d061f2fd2486). I'm assuming that we don't want to recover this image.
  > ![who-uses-dart.png](https://github.com/dart-lang/site-www/blob/208e7990cb1a72b900ed22ea0db164ba5120cab2/src/_assets/images/who-uses-dart.png?raw=true)

**Comment by filiph** [comment]
Sorry for the late reply. I just want to confirm that we want that who uses dart image to stay deleted. Most of those things are irrelevant and superseded by much more interesting users. If we have time, let's create a new one, but then we need to make sure to revisit it at least once a year.

**Comment by chalin** [comment]
@filiph - Thanks. Are you referring to the general image, the page specific images, or possibly both.  I can help create new images if you let me know what you want (or have a base from which I can start).

**Comment by filiph** [comment]
I meant specifically the ["who uses Dart" image](https://raw.githubusercontent.com/dart-lang/site-www/208e7990cb1a72b900ed22ea0db164ba5120cab2/src/_assets/images/who-uses-dart.png).

**Comment by kwalrath** [comment]
I think we can hold off on replacing that image, for now.

**Comment by chalin** [comment]
Ok
