### ISSUE TITLE
'Migrating to null safety' page issue

### ISSUE THREAD

**Issue by yangfu132** [dart-lang/site-www#3091]
Page URL: https://dart.dev/null-safety/migration-guide.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/null-safety/migration-guide.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

“Apply migration” is not available in Chrome , Chrome version is 89.0.4389.90, MacOSX.

**Comment by parlough** [comment]
Just to verify, you don't see the "apply migration" button in the upper right of the migration tool?

**Comment by parlough** [comment]
If your application has any available migrations, the button will show up as clickable otherwise it will be disabled. Also if you've made changes or modified suggestions, you'll need to click "Rerun from sources" to re-enable the button.

Let us know if you have any other issues and if you experience functional issues with the migration tool consider opening an issue [for the Dart SDK](https://github.com/dart-lang/sdk/issues).

Thanks!
