### ISSUE TITLE
after following the instructions, cannot find dart path

### ISSUE THREAD

**Issue by Ahmed-Adel-Ismail-Talabat** [dart-lang/site-www#3114]
Page URL: https://dart.dev/get-dart.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/get-dart.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

after following the instructions, dart is downloaded, but cannot find it on the machine

**Comment by micpap25** [comment]
This issue is not directly related to the Dart Documentation, but rather deals with the program you are using to download Dart. Refer to the docs for Chocolatey or Homebrew if you're on Windows / Mac respectively. 

Regardless, not being able to find the installation shouldn't prevent you from using Dart.

**Comment by kwalrath** [comment]
Thanks for answering, @micpap25.

@Ahmed-Adel-Ismail-Talabat, I'd suggest getting help from one of the [community forums](https://dart.dev/community#join-the-conversation), like StackOverflow. Once you figure out the solution, if you have specific suggestions for the docs, we'd love an issue/PR with a link to whatever resource helped you.

(We generally avoid documenting other tools or OS-specific instructions that aren't specific to Dart, but we do want to help people find the information they need.)
