### ISSUE TITLE
Mac -> macOS

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3137]
Per the discussion in #2892.

**Comment by bharat-biradar** [comment]
@kwalrath I have opened a PR for this issue.

**Comment by parlough** [comment]
@bharat-biradar The [Debugging Dart web apps](https://dart.dev/web/debugging) page which can be found in [debugging.md](https://github.com/dart-lang/site-www/blob/master/src/web/debugging.md) still has a few `Mac` references instead of `macOS`. 

Would you like to update those in a new PR? I'd be happy to review it for you :)

**Comment by bharat-biradar** [comment]
@parlough Yes I will.

**Comment by bharat-biradar** [comment]
@parlough Anything else I can help with.

**Comment by parlough** [comment]
@bharat-biradar I think that's all for this issue, thank you very much! If you'd like, feel free to work on any other other issue that interests you. The [help wanted issues](https://github.com/dart-lang/site-www/labels/help%20wanted) can be a good place to start.

Feel free to tag me if you ever need help or clarifications :)
