### ISSUE TITLE
Codelabs - iterable collections, the function name filterUnder21 is incorrect

### ISSUE THREAD

**Issue by shellong** [dart-lang/site-www#3183]
**Issue location**
Exercise: Filtering elements from a list
https://dart.dev/codelabs/iterables#exercise-filtering-elements-from-a-list

**Issue description**
The codelab function name is **filterUnder21**, but the codelab instruction and the proposed solution suggests to return all users of age 21 or more.

**Comment by parlough** [comment]
Thanks for the report @shellong!

I'm thinking the intention was to imply filtering _out_ users under 21, but I can see how this can be confusing. Particularly since Java and JavaScript both provide a `filter` method that works similarly to Dart's `where` method.

I'll give some thought on the best way to improve clarity here, but I'm open to ideas! Perhaps renaming the method to `filterOutUnder21` or match the `findShortNamed` method and use `findOver21`.

**Comment by shellong** [comment]
Hey @parlough,
Thank you for a quick reply!
I like your suggestion renaming it to findOver21, though this name doesn't reflect people at the age of 21.
FilterOutUnder21 sounds more accurate.
The third option could be findUSLegalAlcoholConsumers 🍺 
Thanks :)
