### ISSUE TITLE
The async/await DartPad example does not run

### ISSUE THREAD

**Issue by Jstuff36** [dart-lang/site-www#3210]
This [link](https://dartpad.dev/fae22cffa7b184b4d27cd96dd633a5af?null_safety=true) does not run because it opens with two errors. The link exist on step 7, [Congratulations](https://codelabs.developers.google.com/codelabs/from-java-to-dart/#6), of the Into to Dart Developers codelab.

**Comment by parlough** [comment]
Hey @Jstuff36, thanks for pointing this out! The issues are related to null safety so we must not have updated this DartPad's gist since before the 2.12 release.

There's a few ways to fix the issues, but minimally to access the `output` span, we could use the conditional member access operator. So change the following from:

```dart
output.text = estimate.toStringAsFixed(5);
```

to:

```dart
output?.text = estimate.toStringAsFixed(5);
````
Then change the generateRandom's optional `seed` positional parameter to nullable. You could give it a default value, but the `Random` constructor also accepts a nullable seed. So change the parameter type from `int` to `int?`:

```dart
Iterable<Point> generateRandom([int seed]) sync* {
```

to:

```dart
Iterable<Point> generateRandom([int? seed]) sync* {
```

I put an example of these minimal changes here:
https://gist.github.com/parlough/98efb34052d23440834540741fa7dff7

Thanks again for the report! We'll work on updating this sample :)

**Comment by kwalrath** [comment]
I've made Parker's changes. Thanks, @parlough & @Jstuff36!
