### ISSUE TITLE
simplify sidenav

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#327]
Might we want to reorganize the site-www sidenav to better match the webdev sidenav. Here are snapshots:

site-www (current) | site-webdev | site-www (proposed)
-- | -- | --
![screen shot 2017-07-13 at 1 38 06 pm](https://user-images.githubusercontent.com/4140793/28179635-8af65526-67d0-11e7-8194-e9c5a1eb8df5.png) |  ![screen shot 2017-07-13 at 1 07 04 pm](https://user-images.githubusercontent.com/4140793/28178381-41ef7668-67cc-11e7-813e-1594f7013ddd.png) | ![screen shot 2017-07-13 at 1 35 01 pm](https://user-images.githubusercontent.com/4140793/28179545-4ceea9f4-67d0-11e7-9cf9-a9d49038d862.png)

This is in part a followup to the discussions of #324.

cc @filiph @kwalrath @Sfshaza

**Comment by chalin** [comment]
We might even want to give more emphasis to PLATFORMS and place it _before_ TESTING.

**Comment by kwalrath** [comment]
Mostly LGTM. We need to change Dart VM to Server (because Flutter uses the VM and we lost an argument about naming it Standalone :). I agree that PLATFORMS should be before TESTING.

The RESOURCES list for both sites is too long to scan easily. It's OK for now, but we should thing about another way to present these links. Maybe create 2 or 3 groups and don't have a separate group just for TESTING.

I thought about changing *About* to *Overview*, for consistency, but I think packages/products like AngularDart and AngularDart Components warrant an *About* page. *Overview* feel right for more generic terms like Language and Libraries.
