### ISSUE TITLE
Dart Documentation and Flutter API are down

### ISSUE THREAD

**Issue by l-white** [dart-lang/site-www#3313]
503 errors are produced

**Comment by l-white** [comment]
The dart docs and Flutter API are back up! Thanks, all.

**Comment by Sonal-1601** [comment]
Yes, It's working now. Thanks!

**Comment by parlough** [comment]
Hey everyone, thanks for your patience. I'm glad to see the issue was resolved and both the Dart and Flutter documentation are again available.

For more context, around this time, Firebase Hosting, which these websites use for static hosting had an outage, described [here on the Firebase Status Dashboard](https://status.firebase.google.com/incidents/CwDdn12D5GF6nXewEvUu). It was resolved in a little over an hour.

I will close this issue but let us know if you experience any further issues, thanks again!
