### ISSUE TITLE
Documentarion of Bool Class don't have operators '!' and '!='

### ISSUE THREAD

**Issue by robertoalvesneto** [dart-lang/site-www#3331]
At https://api.dart.dev/stable/2.13.3/dart-core/bool-class.html the operators '!' and '!=' are not defined, just only '&', '==', '^' and '|'.

**Comment by parlough** [comment]
Hey @robertoalvesneto! I think this is a byproduct of `!=` not being a separate user-defined operator and instead simply being implemented as `e1 != e2` being `!(e1 == e2)`. As for `!` not being defined as part of the dartdoc, I believe this is because it is also not a user defined operator and is a special case for boolean expressions where "The expression `!e` is treated as `e ? false : true`.

That is not to say there wouldn't be benefit from documenting these as part of the generated dartdocs, but they may need to be implemented as special cases by dartdoc(not sure). Since this repository is simply for the [dart.dev](https://dart.dev) website, if you want to see this implemented, perhaps you will have better luck discussing these possibilities further in the [dartdoc repository](https://github.com/dart-lang/dartdoc). 

Let me know if you have any other questions, thanks!

**Comment by robertoalvesneto** [comment]
sorry to comment on the wrong repository and thanks for the explanation!
