### ISSUE TITLE
Intro to Dart for Java Developers "Create A Simple Dart Class" is missing a line of code in main()

### ISSUE THREAD

**Issue by Sammanay** [dart-lang/site-www#3382]
In main(), there has to be a print(bike) line in order to see the contents of the bike. While this was not a problem to me, it can confuse newer learners.

**Comment by parlough** [comment]
Hey @Sammanay, thanks for opening the issue!

If I'm understanding correctly, you're talking about the `main` method in the first code block not including a print statement?

As far as I can tell, this is intentional as the previous statement mentions "Also remove the contents from main(), as shown in the following code snippet". This is because the DartPad fills in an unrelated, default method. Then a few sections later in the **Instantiate and print a Bicycle instance** section, it is explained to the user how to instantiate an instance of `Bicycle` and print it out in the main method. With more followup to implement a custom `toString` method.

This is done to separate the explanation of defining `Bicycle` from creating, implementing, and using it, so learners can understand each piece individually. The code sample in the first block isn't yet functional without a constructor to initialize the fields, so they need to proceed with the following steps anyway.

Am I correctly understanding the section(s) you're talking about? If so, do you think there's anything particular we could modify to make this more clear?

**Comment by kwalrath** [comment]
Closing due to lack of response, but I'd be happy to reopen this.
