### ISSUE TITLE
How to make the result of strong-mode (implicit-casts/implicit-dynamic) analysis as warning, instead of error?

### ISSUE THREAD

**Issue by wigl** [dart-lang/site-www#3395]
My project has been developed for almost a year, and I didn’t use stricter static checks at the beginning, which resulted in a lot of bugs.
Now I want to add strong-mode (implicit-casts/implicit-dynamic) to analysis_options.yaml, But after that, 5k errors were displayed!
![image](https://user-images.githubusercontent.com/12051109/125794485-65d1f282-56d7-42f6-80f1-f11f00fd13ef.png)

I can't modify them all at once. Can I display this error as warning? In this way, I will pay attention to this warning in future development, and the historical code not need modified temporarily.
thanks.

**Comment by parlough** [comment]
Hey @wigl, I know you closed the issue, but I'm curious were you able to figure out a solution?

I gave it some thought and I think the best you can do is include another `analysis_options.yaml` file within a sub-directory where you don't enable the strong-mode features.

```yaml
analyzer:
  strong-mode:
    implicit-casts: true
```

You can technically modify diagnostics to be warnings but since multiple diagnostics result from enabling these language options, that'll be harder to keep track of and you may disable important errors.

**Comment by wigl** [comment]
I haven't solved this problem. It was closed because a new [issue](https://github.com/dart-lang/sdk/issues/46624) was created in [dart-lang/sdk](https://github.com/dart-lang/sdk).

There are some problems with adding `analysis_options.yaml` in sub-directory:
1. We also need to add `pubspec.yaml` in the subdirectory, otherwise the analyzer will not execute.
2. If `pubspec.yaml` is added, the sub-directory will as a package.

**Comment by parlough** [comment]
I'm going to close this in favor of https://github.com/dart-lang/site-www/issues/3371 which requests documenting customizing analysis options in a sub-directory.
