### ISSUE TITLE
[PAGE ISSUE]: 'Futures and error handling'

### ISSUE THREAD

**Issue by FR15** [dart-lang/site-www#3526]
### Page URL

https://dart.dev/guides/libraries/futures-error-handling

### Page source

https://github.com/dart-lang/site-www/tree/master/src/_guides/libraries/futures-error-handling.md

### Describe the problem

the 'Errors in the middle of a long chain' section , the catchError should return String type, not int.

**Comment by parlough** [comment]
Hey @FR15, thanks for opening the issue.

I think as long as the returned type matches the return type of `processValue`, this should be fine in terms of proper static typing. Since `processValue` is not defined, nor the focus of this example, I can see where the confusion can arise.

We should either return a string to be consistent and make the example more focused or make it more clear that `processValue` what it is. 

I'm working on some other changes to the page, so I'll re-open this issue to track improvements here as well. Thanks again!
