### ISSUE TITLE
[PAGE ISSUE]: 'A tour of the Dart language'

### ISSUE THREAD

**Issue by codisfy** [dart-lang/site-www#3597]
### Page URL

https://dart.dev/guides/language/language-tour

### Page source

https://github.com/dart-lang/site-www/tree/master/src/_guides/language/language-tour.md

### Describe the problem

On the following example: 
```dart
var list = [1, 2, 3];
```
A note about list states

>  Note: Dart infers that list has type List<int>. If you try to add non-integer objects to this list, the analyzer or runtime raises an error. For more information, read about type inference.

But if I run the code on https://dart.dev/#try-dart like 

```dart
var list = [1, 2, 'asdf'];
void main() {
  print(list);
}
```

It doesn't give any error suggesting that the Note needs to be either updated or explained well.

**Comment by parlough** [comment]
Hey @codisfy, thanks for opening an issue. Let me start by explaining what is going on here.

So Dart is inferring the type based off the nearest shared type of the items in the list literal. In the included case, since all of its elements have the type `int`, `list` is inferred to have type `List<int>` hence not being able to add non-integer objects after creation.

```dart
var list = [1, 2, 3];
void main() {
  list.add('Not an integer'); // This is what would not work since a String is not an int
  print(list);
}
```

In your example, since a String literal is included in the list literal, `list` is inferred to have type `List<Object>` because `Object` is the parent type both `int` and `String` share. So now you can add any item which is a subclass of `Object`.

```
var list = [1, 2, 'asdf'];
void main() {
  list.add(3.0); // Even adding a double here is fine
  print(list);
}
```

If you are running this code in DartPad or an IDE you can click on the `list` variable to see its type.

I agree that this note could cause more confusion though, so perhaps we can expand on the current explanation. Perhaps, specifying that by adding we mean after creation. Thanks again for the issue and let me know if you would like any further clarification.

**Comment by codisfy** [comment]
@parlough perfect explanation. Makes much more sense now.
Thanks a lot.
