### ISSUE TITLE
[Effective Dart] Add function definition to glossary

### ISSUE THREAD

**Issue by dramos07** [dart-lang/site-www#3602]
### Page URL

https://dart.dev/guides/language/effective-dart/design#avoid-starting-a-method-name-with-get

### Describe the problem

The current guidance for [avoiding starting a method with `get`](https://dart.dev/guides/language/effective-dart/design#avoid-starting-a-method-name-with-get) should also include functions since it also applies to that just like [avoid-describing-the-parameters-in-the-functions-or-methods-name](http://go/effective-dart/design#avoid-describing-the-parameters-in-the-functions-or-methods-name)

### Expected fix

Any language for `method` should be replaced with `function or method`

**Comment by parlough** [comment]
Thanks for bringing this up @dramos07, I think it makes sense for this Effective Dart suggestion to apply to normal functions as well. 

@munificent Do you think it's fine to adjust this wording to "function or method" like some of the preceding rules?

**Comment by Veercodeprog** [comment]
anyone working on this?
assign me please

**Comment by Veercodeprog** [comment]
do i have to change the method name in multiple files or any particular one?

**Comment by parlough** [comment]
Hi @Veercodeprog, what this issue is mentioning is not about changing any method names. It's instead modifying a [code design suggestion](https://dart.dev/guides/language/effective-dart/design#avoid-starting-a-method-name-with-get) from [here](https://github.com/dart-lang/site-www/blob/master/src/_guides/language/effective-dart/design.md#avoid-starting-a-method-name-with-get) to apply to normal functions as well instead of just methods in terms of its name and description. Similar to how the rule, [CONSIDER an imperative verb phrase for a function or method if you want to draw attention to the work it performs](https://dart.dev/guides/language/effective-dart/design#consider-an-imperative-verb-phrase-for-a-function-or-method-if-you-want-to-draw-attention-to-the-work-it-performs), mentions both functions and methods.

**Comment by Veercodeprog** [comment]
ok got it
we can add something like with some reference example
AVOID starting a method  or function name with get.

**Comment by munificent** [comment]
I don't want readers to have to read "function or method" every single time a callable thing is mentioned. How about we add a section to the [glossary](https://dart.dev/guides/language/effective-dart#glossary) that says that unless noted otherwise, "function" refers to top-level functions, local functions, static methods, and instance methods. Then we can change the guidelines to consistently just use "function".

**Comment by parlough** [comment]
That consistency and simplification sounds great to me! Function should be understood without even looking at the glossary in most cases, so that seems like a good direction. @kwalrath What do you think?

**Comment by kwalrath** [comment]
> That consistency and simplification sounds great to me! Function should be understood without even looking at the glossary in most cases, so that seems like a good direction. @kwalrath What do you think?

I like it.

**Comment by Veercodeprog** [comment]
hi @parlough @kwalrath @munificent ,hope you are all doing good
let me know what changes we need  ,i can work on it

**Comment by Veercodeprog** [comment]
with your guidance ,i want to work on this repo further
