### ISSUE TITLE
Add security policy exception for dartpad.dev

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/site-www#3629]
### Describe the problem

Loading dart.dev from a DartPad snippet using url_launcher causes a CORS issue: https://github.com/dart-lang/dart-pad/issues/2038. 

### Expected fix

Could we add an exception to the security policies that were added in https://github.com/dart-lang/site-www/pull/3540?

### Additional context

- https://github.com/dart-lang/dart-pad/issues/2038
- https://github.com/flutter/website/issues/6381

**Comment by parlough** [comment]
I've been trying to test various solutions to these problems, but I'm having trouble identifying a great one. 

I believe the primary CORS policy issue occurred before my changes, at least after reverting that and testing it. Since [`access-control-allow-origin`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) cannot be set for multiple origins without checking each origin on the server, it seems the only option would be to allow access to all resources for all origins. Since dart.dev is just public, static content I don't think this would be an issue, but I'm not sure that's the direction we want to go.

As for the issues resulting from the document being sandboxed, I'm not 100% sure but I believe that may be an issue on the DartPad or url_launcher end as launching pub.dev with the gist you included also results in similar errors on that end. 

I don't have a lot of experience here so I'm open to input and suggestions :)

**Comment by kwalrath** [comment]
Oh, just saw this. So... #3638 is only a partial fix?

**Comment by parlough** [comment]
Yeah there's multiple issues at play here. The primary one being the CORS one relating to access-control-allow-origin. 

That PR follows guidelines to switch to a newer style while adding support for DartPad as an ancestor but these other issues prevent any noticeable benefit.

**Comment by parlough** [comment]
The affecting policies were removed with the website infrastructure update and `url_launcher` is no longer supported on the DartPad end. Closing this for now, but if we add further policies, we'll make sure there are exceptions for DartPad :)
