### ISSUE TITLE
Indention in the style guide

### ISSUE THREAD

**Issue by vanillajonathan** [dart-lang/site-www#3651]
### What information is missing?

The style guide does not mention what indention to use (spaces or tabs) and how many to use.

### How would you like us to fix this problem?

Add what kind of spacing to use. Example "Use two spaces for indention".

**Comment by kwalrath** [comment]
This, although it might seem strange, is intentional. As https://dart.dev/guides/language/effective-dart/style#do-format-your-code-using-dart-format says, "the official whitespace-handling rules for Dart are whatever `dart format` produces."

That guideline also points to https://github.com/dart-lang/dart_style/wiki/Formatting-Rules, which has details about the formatting rules that `dart format` applies.

**Comment by kwalrath** [comment]
Closing, but we do appreciate you noting that it seemed to be missing. Does the Formatting-Rules link have what you wanted?

**Comment by vanillajonathan** [comment]
Most other languages seem to have a style guide which declares what indention to use. I believe not including that in the style guide is bad as it leads a fragmented community with codes of different styles.

**Comment by kwalrath** [comment]
Iirc, we followed the lead of Go, which says "let the machine take care of most formatting issues." https://golang.org/doc/effective_go#formatting.

**Comment by vanillajonathan** [comment]
Go is explicit about using tabs tho, and when using tab its natural to increase the indention by one more tab for each indention.

> We use tabs for indentation and gofmt emits them by default. Use spaces only if you must.
