### ISSUE TITLE
Hey, i found something wrong in dart's list algorithm.

### ISSUE THREAD

**Issue by cansati** [dart-lang/site-www#3745]
```dart
List anEmpSkills = [];
List asd = [];
List empData = [[1,1],[1,1,1]];
  
  
for (var employee in empData) {
  anEmpSkills.clear();
  for (var skill in employee) {
    anEmpSkills.add(skill);
  }
  asd.add(anEmpSkills);
}
print(asd);
```

When you run this code, the output of list asd has to be [[1,1],[1,1,1]] but it becomes [[1,1,1][1,1,1]] unfortunately. Hope it's useful for community.

Regards

**Comment by parlough** [comment]
Hi @cansati, thanks for opening an issue.

Taking a look at your code, this behavior is expected. You add a **reference** to the list stored in `anEmpSkills` to `asd` twice. Even though you clear the list, the references still point to the same list, so when you print `asd` it will contain two references to the same list (which will therefore have the same contents).

If you want to achieve the behavior you desired where you get two different lists, you can create a new list instead of clearing it:

```dart
List anEmpSkills = [];
List asd = [];
List empData = [[1,1],[1,1,1]];

for (var employee in empData) {
  anEmpSkills = [];
  for (var skill in employee) {
    anEmpSkills.add(skill);
  }
  asd.add(anEmpSkills);
}
print(asd);
```

Does that help explain what you're seeing? Let me know if you have any other questions or concerns. The Dart language tour's [section on Variables](https://dart.dev/guides/language/language-tour#variables) may help you understand this concept a bit more as well. Thanks again!

**Comment by parlough** [comment]
I'm going to close this for as there doesn't seem to be an issue and this repository is for the dart.dev website. If you have any more concerns or would like further clarification, feel free to respond here and let me know. Thanks again!
