### ISSUE TITLE
dart.dev/robots.txt excludes all robots

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#3755]
### Describe the problem

https://dart.dev/robots.txt is blocking most of the site content, as if it were a staging site. Looking at dart-lang/site-shared/pull/50, I'm guessing that we've made a change that prevents robots.txt from being overwritten to be more permissive.

@kevmoo found this issue; I don't know how long it's existed.

**Comment by kwalrath** [comment]
We think this might have stopped working as of https://github.com/dart-lang/site-www/pull/3726. That PR was merged 12/14, which was a week before we started getting autogenerated emails with the subject "New Coverage issue detected for site dart.dev".

**Comment by kevmoo** [comment]
> We think this might have stopped working as of #3726. That PR was merged 12/14, which was a week before we started getting autogenerated emails with the subject "New Coverage issue detected for site dart.dev".

Yup! We no longer use `deploy.sh` – which has the bit that says `--robots ok`

**Comment by kevmoo** [comment]
So we should blame @mit-mit for this 🙃

**Comment by mit-mit** [comment]
Wait, what -- changing the deploy command reconfigured the robots.txt?

**Comment by parlough** [comment]
The old deploy script (called from [here](https://github.com/dart-lang/site-www/pull/3726/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L124)) accepted a parameter to [change](https://github.com/dart-lang/site-shared/blob/master/tool/deploy.sh#L60) the `robots.txt`. Since we passed "ok" into the deploy.sh command [`_setRobotsOk`](https://github.com/dart-lang/site-shared/blob/master/tool/_robots.sh#L60) was eventually called, overriding the default restrictive `robots.txt`.

Sorry I didn't notice this earlier when reviewing the new deploy method. The old deploy logic is rather opaque and I never took a close look. The upcoming infrastructure improvements should streamline it.
