### ISSUE TITLE
Confusing code snippet on the first page

### ISSUE THREAD

**Issue by cybernavid** [dart-lang/site-www#378]
On the first page (https://www.dartlang.org/) there is a code snippet to calculate Pi. The code misses function call ".take(500)" on the line with "await for (var estimate in computePi()) {".

This is confusing as there is no program termination code.

If you open the code in DartPad, it has the "take(500)" call.

**Comment by kwalrath** [comment]
Good catch! Thanks very much for reporting this.

**Comment by filiph** [comment]
Thanks for reporting. 

The original idea was to have the code on the page a) cleaner, b) command-line-y (run until `Ctrl-C`, gradually increasing the precision of Pi). So the omission was intentional.

But if it's confusing (and it retrospect, it is), then let's definitely put the `take(500)` call there. And I see @kwalrath has already done it. Thanks!
