### ISSUE TITLE
[PAGE ISSUE]: 'Dart cheatsheet codelab'

### ISSUE THREAD

**Issue by olechafm** [dart-lang/site-www#3865]
### Page URL

https://dart.dev/codelabs/dart-cheatsheet#conditional-property-access

### Page source

https://github.com/dart-lang/site-www/tree/main/src/codelabs/dart-cheatsheet.md

### Describe the problem

`(myObject != null) ? myObject.someProperty : null`

shouldn't that be 

`(myObject.someProperty  != null) ? myObject.someProperty : null`

**Comment by danagbemava-nc** [comment]
Hi @olechafm, `(myObject != null) ? myObject.someProperty : null` is the correct expression to be used for this case. 
The assumption is that `myObject` might be null so that is where the null check needs to be. You first need to check if the object itself is null before you can access the property. 

Closing as this is the correct code. 

Feel free to open any more issues if you do find something that might be unclear. 

Thank you
