### ISSUE TITLE
"CONSIDER copying a nullable field..." recommendation should be clearer

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/site-www#3874]
### Page URL

https://dart.dev/guides/language/effective-dart/usage#consider-copying-a-nullable-field-to-a-local-variable-to-enable-type-promotion

### Page source

https://github.com/dart-lang/site-www/tree/main/src/_guides/language/effective-dart/usage.md

### Describe the problem

The "CONSIDER copying a nullable field to a local variable to enable type promotion." recommendation uses the term "copy" in the recommendation title and in several places in the explanation. "Copy" often has a different meaning (a different object that compares equal), so the usage is potentially misleading.

At least one person on StackOverflow has been confused by this, and convincing them that no object was being copied unfortunately took more effort than it should have.

### Expected fix

I think that the recommendation should be adjusted to instead use "assign" or "alias" instead of "copy" everywhere to make it clear that the referenced object is not being copied and that the member variable and the local variable both refer to the same object.

I also would recommend using `final` for the local variable to disallow writing back to the field accidentally.

**Comment by parlough** [comment]
I can definitely see where the confusion can come in, thanks for the explanation and detailed context @jamesderlin.

In [Fixing type promotion issues](https://dart.dev/tools/non-promotion-reasons) we are pretty direct and say "Create a local variable that holds the value of X", but I can see some word like "aliases" instead of "hold" working well.

@munificent Do you have any thoughts on how we can clarify the wording here?

**Comment by munificent** [comment]
Yeah, I agree. "Copy" is totally the wrong word to use here. I like "assign":

> CONSIDER assigning a nullable field to a local variable to enable type promotion.
