### ISSUE TITLE
Flutter web great example?

### ISSUE THREAD

**Issue by Renesanse** [dart-lang/site-www#3936]
### What information is missing?

A lot of developers confused in web development by using flutter web. what about to show a cool example for community?

### How would you like us to fix this problem?

rewrite to flutter web

**Comment by domesticmouse** [comment]
I suspect this request should be moved to the [flutter/website issue tracker](https://github.com/flutter/website/issues).

**Comment by parlough** [comment]
Hi @Renesanse, thanks for opening an issue. 

To clarify, would you like to see more Flutter web examples or the dart.dev site implemented with Flutter?

For Flutter web examples, you could check out [Flutter samples](https://flutter.github.io/samples/#?platform=web) for some good examples for web or the [Flutter photobooth](https://github.com/flutter/photobooth) for a popular example. If you're looking for more examples to be created, it would best to best to direct that to the [flutter/website](https://github.com/flutter/website/issues) end :)

As for implementing the dart.dev website in Flutter, that's probably not something that would be explored extensively currently. It would be a cool experiment to expose the content in an alternative Flutter app, since it is mostly Markdown. If anyone wanted to work on that, I would be happy to help where possible on the site-www content end. 

Thanks again!
