### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by theRealProHacker** [dart-lang/site-www#3946]
### Page URL

https://api.dart.dev/stable/2.16.2/dart-io/FileSystemEntity/isAbsolute.html

### Describe the problem

> On Windows, a path is absolute if it starts with \\ (two backslashes or representing a UNC path) or with a drive letter between a and z (upper or lower case) followed by :\ or :/. The makes, for example, \file.ext a non-absolute path because it depends on the current drive letter.

### Expected fix

Should be

> On Windows, a path is absolute if it starts with \\ (two backslashes or representing a UNC path) or with a drive letter between a and z (upper or lower case) followed by :\ or :/. This makes, for example, \file.ext a non-absolute path because it depends on the current drive letter.

### Additional context

I would have loved to fix this myself, but IMO the source code isn't very clearly structured for a stranger.

**Comment by parlough** [comment]
Thanks for catching this and opening an issue. 

I'll go ahead and keep this open so I can trick fixing it (since I can't move it), but for reference, API documentation changes are tracked in the [SDK Repository](https://github.com/dart-lang/sdk/issues). I'll likely submit a fix tomorrow.

Thanks again :)

**Comment by parlough** [comment]
I created a CL with a fix for this against the SDK [here](https://dart-review.googlesource.com/c/sdk/+/239180). Thanks again for reporting the issue!
