### ISSUE TITLE
Document package features

### ISSUE THREAD

**Issue by nex3** [dart-lang/site-www#399]
Pub is introducing a new feature called "package features" that should be documented with the rest of pub's documentation. It's described in [this internal doc](https://docs.google.com/document/d/1KgXfwv4cBHIr_RquuPeIMEN_Df7Jav1eaiFfxPEk6EY/edit#), and I'm happy to answer questions or review any documentation PRs.

**Comment by kwalrath** [comment]
Some notes:
* More info in https://github.com/dart-lang/pub/issues/1593
* Committed in https://github.com/dart-lang/pub/commit/b12ea571487d54f6dbd102be20660343c0efd1e8.
* Likely users: Package authors, especially those who are writing cross-platform packages or who are concerned with their dependency footprint. (Flutter & Angular have use cases.)

**Comment by parlough** [comment]
Closing as not planned due to the never released functionality being removed from pub in https://github.com/dart-lang/pub/pull/3305. 

For those reading this, if you would like to discuss the feature or alternatives, you may want to open an issue on the [pub repository](https://github.com/dart-lang/pub).
