### ISSUE TITLE
[PAGE ISSUE]: 'A tour of the Dart language'

### ISSUE THREAD

**Issue by Daniel-Yonkov** [dart-lang/site-www#4099]
### Page URL

https://dart.dev/guides/language/language-tour

### Page source

https://github.com/dart-lang/site-www/tree/main/src/_guides/language/language-tour.md

### Describe the problem

The example confined within the **Numbers** section regarding the int type is using exponents as part of the integer literals. in CLI applications, they are considered as double and throws an Error during runtime
```dart
Error: A value of type 'double' can't be assigned to a variable of type 'int'.
  int exponent = 8e5;
```

### Expected fix

This example could be amended by either removing the exponential definition inside the **int** section or moving it to the **double** literals.
Another approach would be to use the method `toInt()`
```dart
var exponent = 8e5.toInt();
``` 

### Additional context

The execution context is in CLI.
Have not verified the result in web interface (casted to javascript)

**Comment by parlough** [comment]
Thanks for catching this! Exponents result in a double and since the section is about literals, we should likely just remove the exponent literal from the integer section.

_Here is a related commit clarifying this behavior in the spec: https://github.com/dart-lang/sdk/commit/debbf6822376aa660e289f7e28e379ea9c56ed47_

**Comment by Daniel-Yonkov** [comment]
Reference #4100

**Comment by parlough** [comment]
Fixed by https://github.com/dart-lang/site-www/commit/84b828dce371663109df74b9b9845a48bbeb6314

Thanks again!
