### ISSUE TITLE
[PAGE ISSUE]: Add quick fix to linter rules page

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#4143]
### Page URL

https://dart.dev/tools/linter-rules.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tools/linter-rules.md

### Describe the problem

We don't document what quick fixes are or what linter rules have quick fixes.

### Expected fix

- [ ] Add a new section which documents what quick fixes are
- [ ] Update the generator to highlight which rules have quick fixes and link to the quick fix documentation from there

**Comment by bwilkerson** [comment]
That makes sense for lints, but I'll note that quick fixes are also available for non-lint diagnostics. Would we also want to associate quick fixes with non-lint diagnostics?

Also, note that the documentation for lints might be moving to the [Diagnostic Messages](https://dart.dev/tools/diagnostic-messages) page. There has been some discussion about the future of this page if we make that change. I expect that it will still exist in some form, but what's probably needed more than just a flat list of descriptions is some documentation that would help users find rules that might be appropriate for them, such as categories of lints, possibly with summaries, and with links to the full documentation.

In any case, it sounds like we want to make some changes in this general area and it would be good to have the bigger picture in order to know what we're working toward.

**Comment by bwilkerson** [comment]
And I'd strongly recommend that we think about ways to keep this data up-to-date, such as by generating it based on the code so that as we add fixes for lints we get the documentation updated appropriately. (Other ideas are welcome.)
