### ISSUE TITLE
[PAGE ISSUE]: 'Dart DevTools'

### ISSUE THREAD

**Issue by arkeri** [dart-lang/site-www#4150]
### Page URL

https://dart.dev/tools/dart-devtools.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tools/dart-devtools.md

### Describe the problem

VS code Devtools Network Page shows nothing. It opens and remains blank. It doesn't show any sort of detail as to why and it doesn't show any error. 

I'm on an M1 mac but I'm uncertain whether that is the problem. 

### Expected fix

Being able to at least view the problem or fixing it entirely would make a huge difference because I absolutely need this feature to debug an authorization error we're dealing with.

**Comment by parlough** [comment]
Hey @arkeri, thanks so much for opening an issue. Unfortunately, this is the issue tracker for the dart.dev website.

Can you try using the standalone devtools instead of the one embedded into VS Code? If that works, consider opening an issue on [Dart for VS Code repository](https://github.com/Dart-Code/Dart-Code) with information about your setup, including if other pages are working, perhaps a screenshot, and if you are using Flutter, the output of `flutter doctor`.

If it doesn't work in standalone devtools either, consider [opening an issue](https://github.com/flutter/devtools/issues/new) on the [devtools repository](https://github.com/flutter/devtools) with the same information.

I'm not sure what it looks like for you, but I believe the network page should start mostly empty, until you click "Record network traffic" and then "Stop".

Let me know if you need any further help, thanks!
