### ISSUE TITLE
[Suggestion]: 'Effective Dart: Design' - We should recommend always annotating with `dynamic`.

### ISSUE THREAD

**Issue by natebosch** [dart-lang/site-www#4192]
### Page URL

https://dart.dev/guides/language/effective-dart/design#do-annotate-with-dynamic-instead-of-letting-inference-fail

### Page source

https://github.com/dart-lang/site-www/tree/main/src/_guides/language/effective-dart/design.md

### Describe the problem

Currently we only recommend an explicit `dynamic` type annotation when inference fails, and we say

> Note that it’s OK to omit the type when Dart successfully infers dynamic.

The practices I see have shifted further away from using `dynamic`, and it makes sense to highlight more where it is showing up in usage. All `dynamic` should be, and look, intentional. I think we should change the phrasing to drop the section about inference filling in with dynamic. Most use cases should prefer `Object?` over `dynamic`.

### Expected fix

Drop the text starting with "Note that it’s OK" Replace with

> Prefer to annotate with `Object?` to allow arguments of any type. When `dynamic` is necessary, make it explicit by annotating with `dynamic`, even if inference would correctly fill it in.

**Comment by natebosch** [comment]
I might even go a step further, and recommend type annotating with `Object?` instead of letting inference fill in `dynamic`, and reserving `dynamic` for the cases where you specifically need dynamic invocations in the body.

**Comment by parlough** [comment]
\cc @munificent

**Comment by munificent** [comment]
I'm not sold on this. If an API returns a value of type `dynamic`, I *don't* want users taking the result of that and storing it in a variable explicitly annotated `dynamic`. Because if that API ever changes to return a useful type, now their annotation is throwing away that more precise type.

I agree that we want people using `dynamic` less, but I think the place to do that is upstream. If you don't want `dynamic` flowing through inference into other variables, instead of shutting it up by annotating the variable (redundantly, with `dynamic`), it's better to fix it upstream so that `dynamic` doesn't flow through inference in the first place.

**Comment by natebosch** [comment]
> Because if that API ever changes to return a useful type, now their annotation is throwing away that more precise type.

I'd be curious to see how often this change plays out, compared to how often folks are using a `dynamic` they don't want, but aren't aware of.

We could use our other strictness initiatives continue to push away `dynamic` if we want to be conservative in Effective Dart and wait for it to be more clearly descriptive of practice. I think we'd be doing a service to readers here if we consistently advise to avoid `dynamic`, and make it visible when it can't be avoided.

**Comment by atsansone** [comment]
@munificent : Based on your guidance, I'm closing this issue.
