### ISSUE TITLE
[PAGE ISSUE]: 'C interop using dart:ffi' has a bad link

### ISSUE THREAD

**Issue by gregoryT5** [dart-lang/site-www#4207]
### Page URL

https://dart.dev/guides/libraries/c-interop

### Page source

https://github.com/dart-lang/site-www/tree/main/src/_guides/libraries/c-interop.md

### Describe the problem

The "Flutter dart:ffi page" link on the C interop page under [Bundling and Loading C Libraries](https://dart.dev/guides/libraries/c-interop#bundling-and-loading-c-libraries) is dead.  It is currently pointed at https://docs.flutter.dev/development/platform-integration/c-interop which yields a 404.

### Expected fix

Update link to the intended page.

**Comment by MaryaBelanger** [comment]
There are 3 different c-interop pages on flutter.dev: [ios](https://docs.flutter.dev/development/platform-integration/ios/c-interop), [mac](https://docs.flutter.dev/development/platform-integration/macos/c-interop), and [android](https://docs.flutter.dev/development/platform-integration/android/c-interop), but no home page for c-interop as concept.

Besides rearranging the content on flutter.dev (which might be a good idea because the background info at the top of each of the three pages is replicated), I think the solution is to change the line in question to: 
Flutter `dart:ffi` page: [ios](https://docs.flutter.dev/development/platform-integration/ios/c-interop), [mac](https://docs.flutter.dev/development/platform-integration/macos/c-interop), and [android](https://docs.flutter.dev/development/platform-integration/android/c-interop)

**Comment by gregoryT5** [comment]
That sounds good, thanks @MaryaBelanger!  That approach also makes it clearer that there aren't c-interop documentation pages for desktop linux or windows yet 😄
