### ISSUE TITLE
Mention `noSuchMethod` for interface change breaking implementing class?

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4261]
### Page URL

https://dart.dev/guides/language/effective-dart/design#avoid-implementing-a-class-that-isnt-intended-to-be-an-interface

### Page source

https://github.com/dart-lang/site-www/tree/main/src/_guides/language/effective-dart/design.md

### Describe the problem

Not really a problem, just a question. The section _AVOID implementing a class that isn’t intended to be an interface_ is making a point about how changes to the original class's interface can break an implementing class, so don't implement classes that aren't intended to be implemented. 

I get that the practice should be discouraged, but as an aside, shouldn't we mention or point to `noSuchMethod` as a workaround? Like here:

> For example, adding a new member to a class is usually a safe, non-breaking change. But if you are implementing that class’s interface, now your class has a static error because it lacks an implementation of that new method.

I don't fully understand the topic, but isn't `noSuchMethod`'s purpose to be a catch-all for members of the implemented class that aren't explicitly declared by the implementing class? I.e., a direct solution for the "break" described here.

### Expected fix

Maybe an example of using `noSuchMethod` to at least not break your code, or point to another page that covers [`noSuchMethod`](https://dart.dev/guides/language/language-tour#nosuchmethod). Or just a comment here if someone could explain why I'm off about this :)

### Additional context

I can take care of the actual page update if someone else can confirm the idea

**Comment by MaryaBelanger** [comment]
@munificent looks like you wrote the section (albeit a while ago!), any thoughts?

**Comment by parlough** [comment]
Thanks for raising the questions, it's an interesting point to consider. It definitely makes sense that the implementer could implement `noSuchMethod` like you mentioned, but my concern is that it then results in those static errors not showing up, resulting in the developer potentially not recognizing any problems until that code path is hit during runtime. 

Definitely is a workaround for the mentioned breaking change, but since this is "Effective Dart" (which aims to help users build robust code), I'm not sure it's a good idea to potentially point them in that direction. The best choice is still to avoid this situation.

Would like to hear @munificent's thoughts though.

**Comment by MaryaBelanger** [comment]
@parlough I like your point about it being the “Effective Dart” page; it’s not very effective to provide workarounds to best practices we’re trying to encourage. 

I think i misunderstood noSuchMethod’s purpose to specifically be for this reason (overriding fields _in implementing classes_, because that’s the context in which I first learned about it), but [looking at its own explanation](https://dart.dev/guides/language/language-tour#nosuchmethod), that use case isn’t even mentioned so I guess it’s not such a direct correlation to the “avoid” situation

**Comment by munificent** [comment]
> I don't fully understand the topic, but isn't `noSuchMethod`'s purpose to be a catch-all for members of the implemented class that aren't explicitly declared by the implementing class? I.e., a direct solution for the "break" described here.

Sort of. It turns a compile-time error into a runtime error. That often makes things *worse*. For example, let's say you're using an API like:

```dart
class Fish {
  void swim() { ... }
  void eat() { ... }
}
```

And you define:

```dart
class AquaticGoat implements Fish {
  void swim() { print('Goat paddles around.'); }
  void eat() { print('Goat eats seagrass.'); }

  dynamic noSuchMethod(Invocation invocation) => null;
}
```

If Fish is later changed to:

```dart
class Fish {
  void swim() { ... }
  void eat() { ... }
  void splashAround() { ... }
}
```

Then `AquaticGoat` does keep compiling because of its `noSuchMethod()`. But the *body* of that doesn't actually have anything like:

```dart
class AquaticGoat implements Fish {
  void swim() { print('Goat paddles around.'); }
  void eat() { print('Goat eats seagrass.'); }

  dynamic noSuchMethod(Invocation invocation) {
    if (invocation.memberName == #swimAround) {
      print('Goat splashes around.');
    }
  }
}
```

So even though my class keeps compiling, it doesn't actually *work* if you were to call `splashAround()` on it. You need to implement some behavior first. The nice thing about *not* implementing `noSuchMethod()` is that the compiler will tell you which methods you need to remember to implement. Once you have `noSuchMethod()` defined, it has no way of knowing if you missed one.

In general, our users tend to prefer errors getting reported at compile-time so they can fix them early instead of crashing at runtime. But this comes at the expense of sometimes making it harder to evolve an API without causing new compile errors in users of the API. This is a big part of why versioning is so central to the package manager: it gives users a way to *not* use a new version of API with changes that would cause compile errors until they're ready to opt in and fix them.

**Comment by MaryaBelanger** [comment]
Thanks @munificent and @parlough! I opened this while checking for potential changes relating to https://github.com/dart-lang/site-www/issues/4263 and understand it better now, so I'll close it. Really appreciate the detailed explanations!
