### ISSUE TITLE
[2.19] New `create` `exclusive` parameter docs

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4266]
## This is an _evaluation_ ticket

Evaluating the _possible_ need for doc updates due to dart-lang/sdk#49647

### Summary

New parameter `exclusive` for (what I'm assuming is a fairly ubiquitous) method, `File.create` (and `createSync`).
The new parameter is for optionally failing on `create` if the file (name?) already exists

### Evaluation

- [Async samples page](https://dart.dev/samples#async) has an example using `file.create`:
    ```
    Future<void> createDescriptions(Iterable<String> objects) async {
      for (final object in objects) {
        try {
          var file = File('$object.txt');
          if (await file.exists()) {
            var modified = await file.lastModified();
            print(
              'File for $object already exists. It was modified on $modified.');
            continue;
          }
          await file.create();
          await file.writeAsString('Start describing $object in this file.');
        } on IOException catch (e) {
          print('Cannot create description for $object: $e');
        }
      }
    }
    ```
    Is the premise of the example (using `try` to create a file incase it already exists) even relevant anymore since `exclusive` handles the same use case? 

- The exception message is ["Cannot create file"](https://github.com/dart-lang/sdk/commit/33846f3678bc795f5ee2dbe54d314c0d00e18c2b#diff-251478751e5b8d02a41ea4262fcd123577e0deda58b61421b8949fb792b761ffL255)
  - This message is probably used in response to a lot of thrown exceptions, but wouldn't it be more helpful if it covered "why" it can't be created?
  - Maybe not, since the user would presumably know if they set `exclusive` to `true` or not?

### References

- The API docs are updated for flutter and dart (not rolled out yet)
  - Here: https://dart-review.googlesource.com/c/sdk/+/255482/7/sdk/lib/io/file.dart#224

**Comment by parlough** [comment]
As for the async example, it's focus is not really on the try-catch aspect, that's just there since there may be an error when creating a file, as other errors are possible. I suppose the `await file.exists()` part could be replaced by specifying a `exclusive: false` parameter to `create` but that removes the opportunity to print out the last modified time in that situation. Either way, it seems the point of the example, showcasing a small use-case of `async-await`, still stands.

For the exception message, I believe it does also include the underlying OS error, like in the example of the file already existing and setting `exclusive: true` you get something like "OS Error: File exists". Perhaps could still be improved and/or made the focus of the error message rather than in parentheses though:

```
FileSystemException: Cannot create file, path = 'test.txt' (OS Error: File exists, errno = 17)
```

Also, you may know already, but just incase. For your comments about the docs not being rolled out yet, you can access pre-release API docs, which follow the `main` branch(called `be`), `dev`, or `beta`.

For example, here is the `dev` branch docs of the updated `create` function which has the updated docs:
https://api.dart.dev/dev/dart-io/File/create.html

**Comment by MaryaBelanger** [comment]
Reviewed one last time, also per @parlough's comment, nothing to do here! Closing
