### ISSUE TITLE
[PAGE ISSUE]: 'Troubleshooting pub'

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/site-www#4281]
### Page URL

https://dart.dev/tools/pub/troubleshoot

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tools/pub/troubleshoot.md

### Describe the problem

This page needs to be updated to reference the new location of the pub `credentials.json` file. I believe the location is now OS dependent

- `~/Library/Application Support/dart/pub-credentials.json` on the mac
- ~/.config/dart/pub-credentials.json` in linux
- I'm not sure where on windows

**Comment by parlough** [comment]
Thanks for pointing this out, not sure how I missed this one.

Here are the full details from the SDK changelog:

Credentials are no longer stored in the pub-cache, but in a platform dependent config directory:
* On Linux `$XDG_CONFIG_HOME/dart/pub-credentials.json` if `$XDG_CONFIG_HOME` is defined, otherwise `$HOME/.config/dart/pub-credentials.json`
* On Mac OS: `$HOME/Library/Application Support/dart/pub-credentials.json`
* On Windows: `%APPDATA%/dart/pub-credentials.json`
