### ISSUE TITLE
[PAGE ISSUE]: 'The Dart type system'

### ISSUE THREAD

**Issue by iLoveDocs** [dart-lang/site-www#4288]
### Page URL

https://dart.dev/guides/language/type-system

### Page source

https://github.com/dart-lang/site-www/tree/main/src/_guides/language/type-system.md

### Describe the problem

In the last paragraph of [Generic type assignment](https://dart.dev/guides/language/type-system#generic-type-assignment) 

There's a line

> To make this code pass static analysis, use an explicit cast, which might fail at runtime.
> `List<Cat> myCats = <Animal>[] as List<Cat>;`

Even if you provide `Cat` in the list of `Animal`, the code will still fail at runtime. So, there is no such thing as 
> might fail at runtime

### Expected fix

We need to either change the following sentence. 
> which might fail at runtime

or provide a solution of using casting, like: 

```dart
List<Cat> myCats = (<Animal>[]).cast(); // or List.from or List.castFrom
```

**Comment by parlough** [comment]
Hey @iLoveDocs, thanks for opening an issue. I believe this section is saying how this cast enables the code to pass static analysis but this type of explicit cast (not this specific situation) may fail at runtime, rather than about how to avoid potential runtime errors.

Perhaps we could be more explicit it's talking about this general case?

**Comment by iLoveDocs** [comment]
@parlough 

Yes, I understand the context but I think your this line makes more sense than the the current line in the docs: 

> but this type of explicit cast may fail at runtime
