### ISSUE TITLE
[2.19] Remove ignore: `undefined_method` for all 2.19 code excerpts

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4394]
I've been adding `undefined_method` to the `// ignore_for_file: ` lines of all the code excerpts I've been writing in preparation of 2.19. 

I'm assuming the best thing to do would be to remove these once 2.19 is stable so anyone editing them in the future can't accidentally add an actually undefined method to any of the code excerpts or tests.

**Comment by parlough** [comment]
I think if you're documenting future releases, unless the change needs to get in before 2.19 lands, it may be fine to just not ignore the error and let the build fail, as it could cause us to miss issues now or in the future.

If you want to get the change in before 2.19, I think it should be fine to comment out the code excerpt for now.

Especially if you have tests or other code, the build will likely still fail anyway due to missing results.

**Comment by MaryaBelanger** [comment]
Fixing PRs merged into [v2.19](https://github.com/dart-lang/site-www/tree/v2.19)
