### ISSUE TITLE
Change 'error prone` link in 'Concurrency in Dart > How isolates work' to data race definition

### ISSUE THREAD

**Issue by mmcdon20** [dart-lang/site-www#4408]
### Page URL

https://dart.dev/guides/language/concurrency#how-isolates-work

### Page source

https://github.com/dart-lang/site-www/blob/main/src/language/concurrency/index.md

### Describe the problem

In this section:

> Most modern devices have multi-core CPUs. To take advantage of all those cores, developers sometimes use shared-memory threads running concurrently. However, shared-state concurrency is [error prone](https://en.wikipedia.org/wiki/Race_condition#In_software) and can lead to complicated code.

I think it would make more sense here for "error prone" to link to an explanation about _data races_ not _race conditions_. 

Not sharing state between isolates prevents _data races_ from happening since _data races_ by definition require shared state in order to occur.

You can still have _race conditions_ even without shared state, and isolates do not eliminate _race conditions_.

### Expected fix

Link to an explanation about _data races_ instead of _race conditions_.

**Comment by atsansone** [comment]
@munificent : Do you have anything to add to this issue? Your help would be appreciated.

**Comment by munificent** [comment]
Oof, I'm not the best person to ask about concurrency stuff, sorry.

**Comment by stereotype441** [comment]
I can definitely see where @mmcdon20 is coming from. Technically speaking, the use of isolates doesn't prevent the user's code from experiencing race conditions, it just prevents data races.

However, the link we are currently using at that point in the docs, https://en.wikipedia.org/wiki/Race_condition#In_software, is particularly nice because it goes to a section of the wikipedia page that explains race conditions in clear terms that don't require a lot of computer science background to understand, and the examples in that section are, in fact, examples of data races. So I don't actually think people will be too confused by this link.

Whereas, for example, if we changed the link to https://en.wikipedia.org/wiki/Race_condition#Data_race, that section begins with:

> Not all regard data races as a subset of race conditions.[[5]](https://en.wikipedia.org/wiki/Race_condition#cite_note-5) The precise definition of data race is specific to the formal concurrency model being used, but typically...

Which I suspect would be intimidating, as well as less informative, to the average programmer. I personally think that most users who click on the link would get far more benefit from the general explanation at https://en.wikipedia.org/wiki/Race_condition#In_software (i.e. leave the link as is).

If anyone knows of a good link that's more clearly focused on data races than https://en.wikipedia.org/wiki/Race_condition#In_software, while still being accessible to the average programmer, I'd certainly be open to changing the link, but IMHO the link we have is pretty good and I'm inclined to stick with it.

**Comment by mmcdon20** [comment]
Maybe focusing so much on the link itself is giving the wrong idea.

I just think the documentation would benefit from being more clear on this topic. 

As @stereotype441 points out

> the use of isolates doesn't prevent the user's code from experiencing race conditions, it just prevents data races.

I just want this point to be communicated clearly in the docs. 

---

For comparison, the [rust language documentation](https://doc.rust-lang.org/nomicon/races.html) clearly explains how data races and race conditions apply to rust. It states that (safe) rust prevents data races, but not race conditions, and defines what these terms mean. Dart Isolates are similar to rust in this respect, so I think this is a good example for comparison.

**Comment by atsansone** [comment]
@mmcdon20 , @stereotype441 : I think adding that bit that @stereotype441 wrote would help a lot. I also found [this link](https://www.avanderlee.com/swift/race-condition-vs-data-race/#:~:text=A%20race%20condition%20occurs%20when,of%20a%20piece%20of%20code.&text=A%20data%20race%20occurs%20when,thread%20is%20writing%20to%20it.) that I think explains the concept better.

Thoughts?
