### ISSUE TITLE
[PAGE ISSUE]: 'Configuring pub environment variables'

### ISSUE THREAD

**Issue by teodor-appd** [dart-lang/site-www#4421]
### Page URL

https://dart.dev/tools/pub/environment-variables.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tools/pub/environment-variables.md

### Describe the problem

Where can we set these environment variables so that they will be **always** available when we run e.g., `flutter pub get`. I'm referring to when someone might miss exporting the env manually; we'll need some pre-build hook that allows us to ship the variable.

**Comment by parlough** [comment]
Thanks for opening an issue! Do you mean how to specify them so they persist across terminal sessions or do you mean share them for everyone running the commands in the project?

For the first case, specifying how to set environment variables is something we've mostly not documented as it is different across operating systems and versions, as well as between different shells occasionally, plus it's not really specific to Dart. Perhaps we could include a page discussing some common methods of doing so and link to it from here as well as any other necessary locations if there's enough of a desire.

As for the second case, pub environment variables are meant to be per user rather than tied to a project as each developer each may want to specify their own cache location or need to use their own mirror depending on their location.

**Comment by teodor-appd** [comment]
Hi @parlough, thanks for the prompt response. I am referring to the second scenario, setting project-level env variables. 

It will be handy for my team to have a project-level env variable to enforce downloading dependencies from our intranet. The current solution involves specifying the `hosted:` parameter for each dependency inside pubspec.yaml, which leads to a lot of duplication (although we saved the proxy URL to a variable and reused it).

```yaml
dependencies:
  flutter:
    sdk: flutter
  provider:
    hosted: *artifactory_proxy_url
    version: ^6.0.1
  flutter_picker:
    hosted: *artifactory_proxy_url
    version: ^2.0.2
  ...
```

The `.env` file would work if we found a method to make `flutter pub get` obey it, and `source`-ing is another manual step that all contributors to the project will not implement. Any automated project-level solutions to this? There's a long-awaited "pre-build" hook waiting to be created on the Dart side, as I've seen in other git issues – there's where a `source` solution would work.

**Comment by parlough** [comment]
Thanks for the explanation @teodor-appd! Yeah, I'm not sure there's an automatic solution specific to Dart or Pub currently,  but I think [this pub issue](https://github.com/dart-lang/pub/issues/3518) covers the situation you mentioned. I recommend adding your use case and support to that issue so it's on the Pub team's radar. This allows them to perhaps better prioritize implementing a solution. 

Once the Pub team adds or suggests a solution, we will definitely document it on the site!
