### ISSUE TITLE
[2.19] Document new 'dart pub add' source and constraint syntax

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#4514]
### Page URL

https://dart.dev/tools/pub/cmd/pub-add.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tools/pub/cmd/pub-add.md

### Describe the problem

Pub has a new syntax in 2.19 that allows for adding multiple packages in one command with more customization:

- Each package can be suffixed with its own (yaml-formatted) descriptor as it would be written in `pubspec.yaml`
- `dev:` is a now prefix to the package instead of a top level option
- Potentially other changes?

Implementation reference: https://github.com/dart-lang/pub/pull/3571

### Expected fix

We should document this new syntax and have some examples. The inline yaml syntax for constraints could have it's own header on the page.

Currently the `dart pub add --help` includes a bunch of examples but it's super long and hard to visually parse in a terminal, so we should consider linking to a good location on the website instead once properly documented.

### Additional context

\cc @MaryaBelanger This doesn't feel necessary to document before 2.19 release since users can simply use multiple commands for now, but I wanted to make sure it was on your radar.

\cc @sigurdm

**Comment by MaryaBelanger** [comment]
@parlough Thanks, yeah I just noticed this in the changelog a week or so ago. 

I do really want to keep the docs up to parity with releases, however minor the development, but it's probably too late to get this in beforehand... What I'm more concerned about though is this falling _really_ far behind. I've already shifted focus to the next release and will be solely occupied with that until... May? Would it become a detriment to users to leave it un-updated _that_ long?

**Comment by parlough** [comment]
@MaryaBelanger The command-line help already documents it rather thoroughly, so it's not a huge detriment. Plus I believe everything is achievable using the flag based commands already.

I might have time in a month to work on this if you could review :)

My understanding the is the constraint syntax is mostly a representation of what is in the pubspec ([Dependency sources](https://dart.dev/tools/pub/dependencies#dependency-sources)), so there might not be _too_ much extra to document anyway.

**Comment by MaryaBelanger** [comment]
While we're looking at this, do you think any of the other pub developments recently added to the changelog require addressing? They're the ones from t[his highlighted bullet](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#pub:~:text=dart%20pub%20add%20foo%3A%3Cconstraint%3E), down. The points about `publish` seem like they're probably too specific of functionalities to have a place in dart.dev, thoughts @parlough ?

**Comment by MaryaBelanger** [comment]
> Currently the `dart pub add --help` includes a bunch of examples but it's super long and hard to visually parse in a terminal, 

Can you show me what you're talking about? When I run that this is what I get

```
Add dependencies to pubspec.yaml.

Usage: dart pub add <package>[:<constraint>] [<package2>[:<constraint2>]...] [options]
-h, --help               Print this usage information.
-d, --dev                Adds to the development dependencies instead.
    --git-url            Git URL of the package
    --git-ref            Git branch or commit to be retrieved
    --git-path           Path of git package in repository
    --hosted-url         URL of package host server
    --path               Add package from local path
    --sdk=<[flutter]>    add package from SDK source
                         [flutter]
    --[no-]offline       Use cached packages instead of accessing the network.
-n, --dry-run            Report what dependencies would change but don't change any.
    --[no-]precompile    Build executables in immediate dependencies.
-C, --directory=<dir>    Run this in the directory <dir>.

Run "dart help" to see global options.
See https://dart.dev/tools/pub/cmd/pub-add for detailed documentation.
```

**Comment by MaryaBelanger** [comment]
Ok, after looking at the new `add.dart` diff (deleted a comment/question I asked the ether before I looked at it 🙃), my understanding is (+notes for me to take care of this):

- the new yaml syntax is the de facto syntax now
  - the very first line on the page showing the add syntax needs to change
- make sure to emphasize at the top that you can add multiple packages
- `add foo:<constraint>` existing dependency updates (used to fail) - put that somewhere.
- a lot of options are replaced by the new yaml syntax
  - `add.dart` lines 90-122 basically sums this up
  - I'll remove those options from the page
- I'll add a "yaml descriptor" section above the "options" section and make sure everything I remove from options has it's new yaml equivalent covered there
  - `add.dart` lines 478-504 have bunch of examples
  - the pub add help.txt includes every example... will copy that content onto the `add` page incase the pub team wants to remove it from the cli
- I will add a version note saying this changed in 2.19
  - even though the change isn't breaking, it seems like this is how we want it to be done now, so I do not think it's worth it to keep the old syntax 
  - but as i was writing the last bullet, I thought a little _"previously --git-url/etc"_ for each one might be nice
- “To add a dev dependency…” part right before "Options" section has to change to “dev:” syntax
  - can also do the _previously `--dev`_ thing here
  - make sure to mention you can add dev dependencies at the same time as normal ones with `dev:`

Other thoughts:
- I took a _quick_ look at this page and don't think anything needs to change despite the change to how you add dev dependencies, because there's nothing about cli tools there. I'll look closer one more time

**Comment by parlough** [comment]
Since documentation and tutorials tend to use the old syntax extensively in steps adding dependencies, I do think there is a large value in keeping the old options documented for a transition period, until more tutorials and usages are updated, on Dart/Flutter sites but also externally. Since the old options works on both older and newer versions too, I imagine for a while some new usages in tutorials will still prefer that too. We can just make it clear the old functionality is deprecated and the new yaml syntax is preferred. This ends up helping users who haven't updated yet but also those viewing tutorials and videos (which can't be updated). 

I think one release is probably enough for keeping these around, particularly since Dart 3 is next.

**Comment by MaryaBelanger** [comment]
I noticed an inconsistency (maybe? or maybe both syntaxes are allowed?) between the API doc examples and the examples in the help text, [commented here](https://github.com/dart-lang/pub/pull/3571/files#r1087174205)
