### ISSUE TITLE
use `Isolate.spawn()` instead of `Isolate.run()` in sample send_and_receive

### ISSUE THREAD

**Issue by JiongBull** [dart-lang/site-www#4721]
As section [Sending multiple messages between isolates](https://dart.dev/guides/language/concurrency#sending-multiple-messages-between-isolates) mentions that there is a [sample](https://github.com/dart-lang/samples/blob/master/isolates/bin/send_and_receive.dart) about using `Isolate.spawn()` instead of `Isolate.run()`, but i can't see any difference with previous code snippets.

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/4413502/224212393-28873e6a-f382-4df1-b3a1-61fed96c8b12.png">

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/4413502/224213042-d2471557-4914-4fcf-9127-ff8ff173569d.png">

**Comment by MaryaBelanger** [comment]
Aha, looks like the sample was updated to use Isolate.run after all. The old way of executing it, with `spawn` instead of `run`, can be seen here in the first commit of the sample: https://github.com/dart-lang/samples/blob/676c9af9052285438142c6b32f497e542402573b/isolates/bin/send_and_receive.dart

@JiongBull Sorry about the confusion and thanks for pointing it out! I'll update the page on the site to fix that.
