### ISSUE TITLE
Avoid using super parameters before they are introduced on 'Constructors' page

### ISSUE THREAD

**Issue by Druvid** [dart-lang/site-www#4731]
### Page URL

https://dart.dev/language/constructors#invoking-a-non-default-superclass-constructor

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/constructors.md

### Describe the problem

A super parameter is used in the example code at line 12 in section _Invoking a non-default superclass constructor_, but this is not introduced until the next section _Super parameters_. This causes confusion for anyone not familiar with super parameters.

### Expected fix

Change line 12 from
`Employee.fromJson(super.data) : super.fromJson() {`
to
`Employee.fromJson(Map data) : super.fromJson(data) {`

or add text explaining that super parameters are introduced in the next section.

**Comment by shaikahmadnawaz** [comment]
@parlough shall I work on this based on above changes?

**Comment by parlough** [comment]
Thanks for reporting this @Druvid, it definitely makes since to just not use super parameters in this case.

@shaikahmadnawaz If you'd like to, sure! Note that you would need to edit more than the Markdown file. We use a [code excerpt tool](https://github.com/dart-lang/site-shared/blob/main/doc/code-excerpts.md) that pulls the code from an actual Dart file to enable testing. In this case you can find the code at: https://github.com/dart-lang/site-www/blob/main/examples/misc/lib/language_tour/classes/employee.dart#L21-L24

We also have the [`use_super_parameters`](https://dart.dev/tools/linter-rules#use_super_parameters) lint enabled, so you will need to disable it at the top of the Dart file, so it isn't triggered on us not using it here.

Once you finish those step, you can manually update the [version of the code in Markdown](https://github.com/dart-lang/site-www/blob/main/src/language/constructors.md?plain=1#L140-L141) manually to match the change. There is a way to update it automatically, but it's probably not worth setting up for this smaller change.

If you work on this, let me know if you need any help. Thanks!

**Comment by shaikahmadnawaz** [comment]
> 

Thank you for the information and for giving me the green light to make the changes. I will work on updating the code as per your instructions and disable the `use_super_parameters` lint. I will also update the Markdown file to match the change. I appreciate your offer to help and will reach out if I need any further assistance. Thanks again!

**Comment by natebosch** [comment]
This was fixed by @atsansone in the last update for that page.

The current link to the section under discussion: https://dart.dev/language/constructors#non-default-superclass-constructors
This section does not use super parameters.

The first place on the page where we use the super parameter syntax today is in the super parameters section https://dart.dev/language/constructors#super-parameters

**Comment by natebosch** [comment]
Ah, I missed a usage because cmd-f doesn't surface them in the same order as the page's visual layout.

**Comment by natebosch** [comment]
I think the proposed fix from the first comment still makes sense.

```dart
Employee.fromJson(Map data) : super.fromJson(data)
```
