### ISSUE TITLE
[PAGE ISSUE]: 'Community and support'

### ISSUE THREAD

**Issue by alishermutalov** [dart-lang/site-www#4806]
### Page URL

https://dart.dev/community

### Page source

https://github.com/dart-lang/site-www/tree/main/src/community/index.md

### Describe the problem

If you give another keyword to a data type as a variable name, it will be accepted as a variable and will not consider that data type in the next lines! for example:

```
int String=5;
print(String);
```

output: 5

```
int String=5;
String myVariable="anyText";
print(String);
```

output: Error ...

### Expected fix

An error should be given if an arbitrary data type is given as a variable

**Comment by parlough** [comment]
Thanks for opening an issue. I think this is challenging since you can name a type and variable mostly anything and errors would be introduced in unrelated code just by adding a new type, introducing a large source for potential breakages.

These issues are avoided by naming standards outlined in [Effective Dart: Style](https://dart.dev/guides/language/effective-dart/style) guidelines and supported by different [linter rules](https://dart.dev/tools/linter-rules). Here are some ones specifically related to this:

| Effective Dart Guideline | Linter Rule |
|--------|--------|
| [DO name types using `UpperCamelCase`](https://dart.dev/guides/language/effective-dart/style#do-name-types-using-uppercamelcase) | [`camel_case_types`](https://dart.dev/tools/linter-rules#camel_case_types) |
| [DO name extensions using `UpperCamelCase`](https://dart.dev/guides/language/effective-dart/style#do-name-extensions-using-uppercamelcase) | [`camel_case_extensions`](https://dart.dev/tools/linter-rules#camel_case_extensions) |
| [DO name other identifiers using `lowerCamelCase`](https://dart.dev/guides/language/effective-dart/style#do-name-other-identifiers-using-lowercamelcase) | [`non_constant_identifier_names`](https://dart.dev/tools/linter-rules#non_constant_identifier_names) | 
| [PREFER using `lowerCamelCase` for constant names](https://dart.dev/guides/language/effective-dart/style#prefer-using-lowercamelcase-for-constant-names) | [`constant_identifier_names`](https://dart.dev/tools/linter-rules#constant_identifier_names) | 

These and other related linter rules that help you avoid this issue are included in the `core` and `recommended` sets of the [`lints` package](https://pub.dev/packages/lints) provided by Dart team. It's highly recommended at at least [enable](https://pub.dev/packages/lints#how-to-enable-these-lints) these lints when working on Dart projects and it will help you avoid this and other potential issues.

Let me know if that doesn't solve your concerns. If you'd like to see changes to the language, consider opening an issue on the [dart-lang/language repository](https://github.com/dart-lang/language). Thanks!
