### ISSUE TITLE
[PAGE ISSUE]: 'Enumerated types'

### ISSUE THREAD

**Issue by gisborne** [dart-lang/site-www#4814]
### Page URL

https://dart.dev/language/enum.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/enum.md

### Describe the problem

Isn't the code sample wrong? I don't think any of these should be _required_:
```
enum Vehicle implements Comparable<Vehicle> {
  car(tires: 4, passengers: 5, carbonPerKilometer: 400),
  bus(tires: 6, passengers: 50, carbonPerKilometer: 800),
  bicycle(tires: 2, passengers: 1, carbonPerKilometer: 0);

  const Vehicle({
    required this.tires,
    required this.passengers,
    required this.carbonPerKilometer,
  });
```
I would want to be able to do: `final robin = Vehicle.car(tires: 3)` and leave out passengers etc.

**Comment by danagbemava-nc** [comment]
Hi @gisborne, the code sample is indeed correct. 

You can't invoke an enum like you would a class or a method. 

Please see https://dart.dev/language/enum#declaring-enhanced-enums for the requirements for declaring enhanced enums

It seems like a class would be better suited to what you want to achieve. 

I'll be closing this since there's no issue with the example. 

Thank you
