### ISSUE TITLE
Automated release testing

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#50]
_From @srawlins on September 2, 2014 20:22_

We should employ some simple sanity tests for releases. Things like:
1. no broken links (including assets: images, js, css) (simple wget with grep script)
2. simple codelab verification with webdriver (webdriver; < 100 lines Ruby script + 1 line in Gemfile OR... some such Dart equivalent + a pubspec.yaml file)
3. maybe markdown formatting tests if jekyll or markdown breaks sometimes? i.e. backticks should be converted to `<code>` (simple curl script + grep, or a more robust Ruby or Dart script)

_Copied from original issue: dart-lang/www.dartlang.org#992_

**Comment by kwalrath** [comment]
_From @sethladd on September 2, 2014 20:36_

Yay! Approved. :)

**Comment by chalin** [comment]
I'd say that this has been addressed. Travis runs 3 jobs: one checks the example code formatting, the other runs example code tests, and the final job builds the site and checks for broken links (though we don't fail the job if any are found).

Based on our experiences on site-webdev, there is room to improve the link checking, but otherwise, I'd say that this item is resolved. @kwalrath, WDYT?
