### ISSUE TITLE
[3.1] Check site against changelog

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#5055]
A few minor changes in the next release. Need to search the site for any mentions of the affected libraries in the [3.1.0 section of the CHANGELOG.](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#310)

Edit: Evaluation

- [x] [#52344](https://github.com/dart-lang/sdk/issues/52334) should be looked at as part of (left over from 3.0): #4730
  - #5075  
- [x] [#52801](https://github.com/dart-lang/sdk/issues/52801) change type in [Library Tour example](https://dart.dev/guides/libraries/library-tour#:~:text=List%3Cint%3E%20encoded%20%3D%20utf8.encode)
  - #5115  
- [x] [#39796](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#dartcore): no changes
- [x] [dart:io](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#dartio): no changes
- [x] [dart:isolate](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#dartisolate): no changes
- [x] [jsinterop](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#dartjs_interop-1): no changes
- [x] [package:js](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#packagejs): no changes

**Comment by parlough** [comment]
@liamappelbe I'm not really familiar, but if it sticks, does your 3.1 callback work address any of the limitations in [Callbacks and multithreading limitations](https://dart.dev/guides/libraries/objective-c-interop#callbacks-and-multithreading-limitations) on the Objective-C and Swift interop page? Or would the page benefit from mentions of the new functionality?

**Comment by liamappelbe** [comment]
@parlough Async callbacks have landed in 3.1, under the [`NativeCallable.listener`](https://github.com/dart-lang/sdk/blob/main/sdk/lib/ffi/ffi.dart#L182) API. The goal is to address those multithreading limitations, but I'll need to add support for these callbacks in ffigen first. Since ffigen is not tied to SDK releases, we can update those docs when that support lands.

But it's probably worth mentioning `NativeCallable.listener` if there's anywhere in the docs that mentions `Pointer.fromFunction`. They're not specific to ObjC interop.

**Comment by parlough** [comment]
Thanks for the explanation! I'll be on the lookout for the ffigen changes then :) 

As for `Pointer.fromFunction`, we don't mention it currently, as our ffi docs are still rather limited, so we should be good (excluding docs we still need to add either way).
