### ISSUE TITLE
Update example with filename in 'Concurrency in Dart' page

### ISSUE THREAD

**Issue by jshji252** [dart-lang/site-www#5063]
### Page URL

https://dart.dev/language/concurrency/

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/concurrency/index.md

### Describe the problem

Hello Team Dart!

I am learning Dart now, and I think I _might have_ encountered a bug in one of the examples (`filename` is used without being declared?), specifically the code below:
```dart
void main() {
  // Read some data.
  final fileData = _readFileSync();
  final jsonData = jsonDecode(fileData);

  // Use that data.
  print('Number of JSON keys: ${jsonData.length}');
}

String _readFileSync() {
  final file = File(filename); // POSSIBLE BUG?  What is filename?
  final contents = file.readAsStringSync();
  return contents.trim();
}
```

### Expected fix

If it is indeed a bug, I think it should be:

```dart
void main() {
  // Read some data.
  final fileData = _readFileSync("my-cool-file.json");
  final jsonData = jsonDecode(fileData);

  // Use that data.
  print('Number of JSON keys: ${jsonData.length}');
}

String _readFileSync(filename) {
  final file = File(filename);
  final contents = file.readAsStringSync();
  return contents.trim();
}
```

### Additional context

The same code is used in both sync and async examples, so if it is a bug, changes should be made in both places.

If it is NOT a bug, can you help me understand ?! :)

Thank you!

**Comment by atsansone** [comment]
@RedBrogdon : Has this contributor correctly identified a bug?

**Comment by RedBrogdon** [comment]
It's not a _bug_ exactly, but it's a code snippet that's missing a line of code. If you take a look at this file you can see the entire example, which includes the declaration for `filename`:

https://github.com/dart-lang/site-www/blob/main/examples/concurrency/lib/sync_number_of_keys.dart

The `// docregion` comment that defines the beginning of the excerpt shown in the markdown comes after that declaration, which is why it's not showing up on the website.

So this is a good catch by @jshji252, and the solution looks simple: move the `docregion` comment from line 6 to line 4, re-run `tool/refresh-code-excerpts.sh` to update the markdown, and send the changes in a PR.

**Comment by RedBrogdon** [comment]
Tony, I'll assign this back to you and you can figure out who'll do the actual work. I can do the update if everyone else is busy.

(or @jshji252, if you're interested, take a run at it! 😄)

**Comment by jshji252** [comment]
Oh wow cool! I didn't know that is how these snippets are generated, so cool.

Yeah I absolutely want to do it! I have been looking for an opportunity to contribute to a cool project so I'll give it a go!

**Comment by jshji252** [comment]
Hi @RedBrogdon , I gave it a go, but it's my first time so I am not 100% sure if I did everything correctly (the fix itself was extremely simple though haha).

Thank you :) !
