### ISSUE TITLE
Consider adding an example of records in 'Constructors'

### ISSUE THREAD

**Issue by Yousofalqadire** [dart-lang/site-www#5067]
### Page URL

https://dart.dev/language/constructors.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/constructors.md

### Describe the problem

we need an example describing how to use Record dataType with class 
and I make this example using dartPad :

```dart
void main() {

  User user = User(data:(id:2,name:'ali',roles:['admin','member']));
  print(user.data);
  print(user.data.roles.first);
}

class User{
 final ({int id,String name,List<String> roles}) data;
  User({required this.data});
}
```
output : 
```dart
(id: 2, name: ali, roles: [admin, member])
admin
```

**Comment by parlough** [comment]
Hi @Yousofalqadire, thanks for opening an issue!

I'm curious what you are looking from for an example in the case of constructors. Was there something specific you weren't sure how to do?

Records are like any other data type here and will be used in the same way as other places such as in normal functions. Beyond that, I imagine in most cases it doesn't make sense to store a record directly as a field, since a class already can contain fields of its own, and data like `id`, `name`, and `roles` can just be direct fields on the class.

Let us know what you think. If there's something in a particular that's not clear, we'd love to improve the documentation. Thanks again!

**Comment by atsansone** [comment]
No response from requestor in 10 months. Closing this issue. You are welcome to reopen it.
