### ISSUE TITLE
Incorrect parameter reference on `drawImageScaledFromSource` documentation

### ISSUE THREAD

**Issue by davidCcD** [dart-lang/site-www#5138]
https://api.dart.dev/stable/3.1.0/dart-html/CanvasRenderingContext2D/drawImageScaledFromSource.html

### Describe the problem

About html_dart2js.dart, line 2854 to 2855:
(line 2854)   * The image is a region of [source] that is [sourceWidth] wide and
(line 2855)   * [**destHeight**] tall with top left corner at ([sourceX], [sourceY]).

Am I misunderstand? Shouldn't it [**sourceHeight**] ?

**Comment by parlough** [comment]
Hi, thanks for opening an issue!

You are right, it does look like it should be `[sourceHeight]`. 

I'm going to move this issue to the [`dart-lang/sdk`](https://github.com/dart-lang/sdk) repository where the SDK API and docs are maintained.

**Comment by parlough** [comment]
Thanks again for the report! Fixed by https://github.com/dart-lang/sdk/commit/a0d8796c9441024640c6f81ffbf466cd3555627a. 

It won't be reflected in the stable API docs until the next minor release though. It is already reflected on the bleeding edge docs though: https://api.dart.dev/be/dart-html/CanvasRenderingContext2D/drawImageScaledFromSource.html
