### ISSUE TITLE
[PAGE ISSUE]: 'Community and support'

### ISSUE THREAD

**Issue by akashmaestros077** [dart-lang/site-www#5219]
### Page URL

https://dart.dev/community/

### Page source

https://github.com/dart-lang/site-www/tree/main/src/community/index.md

### Describe the problem

===== CRASH =====
ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=00007FF9EC9390B0
Aborting reentrant request for stack trace.
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.

**Comment by danagbemava-nc** [comment]
Hi @akashmaestros077, it seems you're running into a compiler crash. Similar issues have been reported on the dart-sdk repo. https://github.com/dart-lang/sdk/issues?q=is:issue+is:open+sort:updated-desc+%221073741819%22+ You may file a new issue so that it can be properly addressed. 

Closing from here as this repo is for website issues only. 

Thank you
