### ISSUE TITLE
Fix syntax in 'Extension methods' example

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#5306]
### Page URL

https://dart.dev/language/extension-methods.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/extension-methods.md

### Describe the problem

In the "[implementing extension methods](https://dart.dev/language/extension-methods#implementing-extension-methods)" section, why does the syntax show a question mark on the extension name?

```
extension <extension name>? on <type> {
  (<member definition>)*
}
```

I don't know all the grammar of describing language syntax, but to me it looks like the `?` is a non-optional part of the syntax, which obviously isn't the case. 

Does it represent something, like `<extension name>` could be nullable? In that case shouldn't it be on `<type>` and also represented as optional? e.g. `<extension name> on <type><?>`

### Expected fix

Just a question, I'd like to know what it means. 

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by parlough** [comment]
It is intended to show that `<extension name>` is optional. We don't introduce any formal grammar notation/syntax in the docs nor can we expect people to know it, so I guess this representation leans on the understanding readers might have of regular expressions for the `?` and `*`, as well as us using `<argument>` across the site.

Since this isn't intended to be a reference doc and we don't formally explain the syntax, maybe we should drop it?
