### ISSUE TITLE
[PAGE ISSUE]: 'Effective Dart'

### ISSUE THREAD

**Issue by NGHIAVN1** [dart-lang/site-www#5378]
### Page URL

https://dart.dev/effective-dart/

### Page source

https://github.com/dart-lang/site-www/tree/main/src/effective-dart/index.md

### Describe the problem

Get more introduction flutter dart

### I would like to fix this problem.

- [X] I will try and fix this problem on dart.dev.

**Comment by huycozy** [comment]
Hi @NGHIAVN1 
This request looks more like a Topic request than a Page issue. I would suggest you open a new [Topic request issue](https://github.com/dart-lang/site-www/issues/new?assignees=&labels=co.request%2Cfrom.user&projects=&template=2_topic_request.yml) and fill all information indicated in the issue template so that we can verify this properly. Thanks!
