### ISSUE TITLE
Edit Performance guarantees of patterns in switch statements & switch expressions on 'Patterns' page

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/site-www#5403]
### Page URL

https://dart.dev/language/patterns.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/language/patterns.md

### Describe the problem

Consider the following:

```dart
void foo(
  final int i,
) {
  final a = switch(i) {
    0 => 0,
    1 => 1,
    2 => 2,
    > 2 && < 5 => 3,
    // ...
    _ => 4,
  };
}
```

Imagine a situation where the `// ...` is replaced with many more cases and complicated patterns.

I think there's an important question that the pattern docs don't seem to answer: what's the execution strategy here? Are all cases evaluated one by one, and the next case is only considered if all previous cases have failed (that is, `_ => 4` can take `O(n)` time where `n` is the amount of entries in the switch expression)? Or should, e.g., the following idiom be used if constant time matching (independent of the amount of patterns) is required?

```dart
  final b = const <int, int>{
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 3,
    // ...
  }[i] ?? 4;
```

### Expected fix

Consider providing guidelines about the performance implications of switch statements and switch expressions.

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by parlough** [comment]
@munificent Could you provide some thoughts on the questions above and what would make sense to document?

\cc  @MaryaBelanger

**Comment by munificent** [comment]
> Are all cases evaluated one by one, and the next case is only considered if all previous cases have failed (that is, `_ => 4` can take `O(n)` time where `n` is the amount of entries in the switch expression)?

In principle, yes, a switch with pattern cases (which as of Dart 3.0 is *all* switches) can be `O(n)` in the number of cases to determine which case matches. This is explicitly true when using object patterns or other patterns that can invoke user code which may have visible side effects. In fact, matching any single case may involve arbitrary computation.

The language doesn't make any promises about how good or bad the performance of pattern matching will be. In practice, the compiler should often be able to tell when the patterns can't have side effects and be able to compile a switch to a jump table or something else efficient. Whether our compilers do that and under what circumstances probably changes over time. I think when Dart 3.0 first shipped, they weren't very efficient, but I imagine they'll optimize more over time.

> Or should, e.g., the following idiom be used if constant time matching (independent of the amount of patterns) is required?
> 
> ```dart
>   final b = const <int, int>{
>     0: 0,
>     1: 1,
>     2: 2,
>     3: 3,
>     4: 3,
>     // ...
>   }[i] ?? 4;
> ```

Well... we don't promise that map key look-up is constant time either. :)

In general, I tend to reason about program performance empirically by measuring and seeing what the actual compilers do instead of relying on claimed guarantees (which may only be true for some compilers, under some circumstances, at certain points in time, for certain uses, etc.).

**Comment by atsansone** [comment]
Based on engineering's take on this, adding performance information in the documentation would not be indicative of real-world experience. Closing this as won't do.
