### ISSUE TITLE
Document that SDK tooling expects Dart files to be UTF-8 encoded

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#5453]
### Page URL

https://dart.dev/tools/sdk.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tools/sdk.md

### Describe the problem

We don't clearly document anywhere what encoding the tools support, resulting in potential confusion by developers (https://github.com/dart-lang/sdk/issues/54523).

While it seems to have been decided to not document this at the specification level (https://github.com/dart-lang/language/issues/2186), we likely should document it at the SDK or tooling level.

### Expected fix

Document somewhere, maybe on the SDK overview or the `dart` tool page that Dart files are expected to be UTF-8 encoded.

**Comment by parlough** [comment]
Do note that some tools within the SDK may have different expectations or support here. If someone works on this, that support should be verified with the relevant teams.

**Comment by eernstg** [comment]
If it is actually useful (say, in order to be able to really quickly parse some libraries that contain a huge number of non-ASCII characters in strings), some tools might add an option like `--encoding utf-16` at some point.

It would be nice if every tool does this in the same way, but it wouldn't be a show-stopper if the analyzer wants `--encoding utf-16` and the CFE wants `--source-encoding UTF16`. I think this means that it can be considered to be a tool specific topic. Hence, if there is no really good place for "rules about all tools" then it would probably still be OK to just document this with every tool separately.

**Comment by parlough** [comment]
I think what we currently have as the [`dart` tool overview](https://dart.dev/tools/dart-tool) page would suffice for now for a location of "rules about all tools". I think(?) it's currently safe to assume and say that all `dart` subcommands expect Dart files to be UTF-8 formatted.

\cc @mit-mit @bkonyi On thoughts about adding a statement like this.

As for the the source encoding CLI option. I'd personally think its use would be pretty niche and likely not worth the implementation effort, but if it's ever added by an individual tool or standardized (preferred), we can document it consistently alongside other flags.

**Comment by mit-mit** [comment]
> It would be nice if every tool does this in the same way

We only have one tool now -- the `dart` tool -- so I strongly suggest we keep that consistent in how it handles encodings across it's subcommands (`dart analyze`, `dart format`, `dart compile`, etc.).
