### ISSUE TITLE
Consider moving brew install instructions to the dart-sdk community package

### ISSUE THREAD

**Issue by seaniepie** [dart-lang/site-www#5499]
### Page URL

https://dart.dev/get-dart/

### Page source

https://github.com/dart-lang/site-www/tree/main/src/get-dart/index.md

### Describe the problem

the brew command should be 
`brew install dart-sdk`
NOT
`brew install dart`
and likewise for upgrade

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by huycozy** [comment]
Here are outputs when executing `brew install` for `dart` and `dart-sdk`:

```console
➜  Desktop brew install dart
==> Fetching dart-lang/dart/dart
==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/2.18.7/sdk/dartsdk-macos-x64-release.zip
############################################################################################################################################## 100.0%
==> Installing dart from dart-lang/dart
==> Caveats
Please note the path to the Dart SDK:
  /usr/local/opt/dart/libexec
==> Summary
🍺  /usr/local/Cellar/dart/2.18.7: 921 files, 497MB, built in 15 seconds
==> Running `brew cleanup dart`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

```console
➜  Desktop brew install dart-sdk
==> Downloading https://ghcr.io/v2/homebrew/core/dart-sdk/manifests/3.2.4
############################################################################################################################################## 100.0%
==> Fetching dart-sdk
==> Downloading https://ghcr.io/v2/homebrew/core/dart-sdk/blobs/sha256:f117c92fd0bacc285c98d527b5ecf17f48b1b5519f4013b4291ef10af1b2afa0
############################################################################################################################################## 100.0%
==> Pouring dart-sdk--3.2.4.sonoma.bottle.tar.gz
🍺  /usr/local/Cellar/dart-sdk/3.2.4: 1,023 files, 561.1MB
==> Running `brew cleanup dart-sdk`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

I'm not sure which one is correct. Finding `dart` on [Homebrew Formulae](https://formulae.brew.sh/), I only see [dart-sdk](https://formulae.brew.sh/formula/dart-sdk#default) there. Labeling the issue for more insights.

**Comment by mit-mit** [comment]
cc @athomas can you comment?

**Comment by athomas** [comment]
Well, these are different packages. One is the one we provide and the other is some community project. They have different features:

`dart-sdk` https://github.com/Homebrew/homebrew-core/blob/c747d12b565608b5867412def730f0429255059f/Formula/d/dart-sdk.rb

- community supported, not maintained by the Dart team.
- builds "from source" (not really, because it depot_tools will use pre-builts).
- only supports main and stable (but you can probably pick other hashes as well).
- will start failing on older releases (depot_tools will stop working for old versions, bottles may push that horizon a bit but seem OS specific).

`dart` https://github.com/dart-lang/homebrew-dart

- maintained by the Dart team (so unless there's a change, this is the official Dart homebrew package).
- same bits that we test because it downloads from dart-archive.
- supports all released versions on all channels.
- will work forever (because dart-archive zips aren't deleted).

If we stop documenting `dart`, we should also stop having that infra.

Personally, I'd use the `dart` package, but homebrew purists might prefer the `dart-sdk` package.

**Comment by mit-mit** [comment]
Thanks for the context Alex. But why did `brew install dart` end up installing 2.18?

**Comment by athomas** [comment]
I suspect the user's tap is busted somehow. Could be a new symptom of homebrew handling the master->main transition poorly. 2.18.7 is from roughly that time.

@seaniepie could you try running `brew update-reset $(brew --repo dart-lang/dart)` and share the output here?

**Comment by seaniepie** [comment]
Will do. Thanks for helping. I came across the problem while installing FlutterFlow dependencies on an Intel Mac and brew said there was no such package called dart. So I did a quick google and it said to get dart-sdk instead. But maybe the update-reset will cure things here.

**Comment by atsansone** [comment]
@seaniepie : Thanks for your assistance here. I'm updating this page in this PR (https://github.com/dart-lang/site-www/pull/5497). I clarified that `dart` is the official brew. We won't be adding the community package at this time. This might change as we investigate methods of installation. Thanks again!

cc: @anderdobo

**Comment by atsansone** [comment]
@seaniepie : Thanks for your assistance here. I'm updating this page in this PR (https://github.com/dart-lang/site-www/pull/5497). I clarified that `dart` is the official brew. We won't be adding the community package at this time. This might change as we investigate methods of installation. Thanks again!

cc: @anderdobo

**Comment by seaniepie** [comment]
This is what I get as a response:
```
Error: /usr/local/Homebrew/Library/Taps/dart-lang/homebrew-dart is not a Git repository!
Usage: brew update-reset [path-to-tap-repository ...]

Fetch and reset Homebrew and all tap repositories (or any specified
repository) using git(1) to their latest origin/HEAD.

Note: this will destroy all your uncommitted or committed changes.
```
