### ISSUE TITLE
Clarify `package:web` migration text

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#5601]
Hey @srujzs! There's a [part](https://dart.dev/interop/js-interop/package-web#migrating-from-dart-html:~:text=that%20it%20annotates.-,Similarly,-%2C%20if%20you%20find) under the [Renames](https://dart.dev/interop/js-interop/package-web#renames) section that I don't quite understand (sorry, missed it during the PR review).

> Similarly, if you find an API with the keyword `native` in `dart:html` that doesn't have an equivalent in `package:web`, check to see if there was a rename with the `@JSName` annotation. `native` is an internal keyword that means the same as `external` in this context.

"...if you find an API with the keyword `native` in `dart:html` that doesn't have an equivalent in `package:web`..." 
- I'm assuming by "if you find" you mean "if the two methods we just mentioned (the `fix` and looking up the definition manually) don't turn up an answer", is that correct?
  - Or, is it more specific, like "if neither of those other methods turned up anything _AND_ the API has the `native` keyword?
- What does it mean for an API to be "_with_ the keyword `native`"? Like, does that mean `native` is literally in the API's name, or in its declaration somewhere? I can't picture it.

"...check to see if there was a rename with the `@JSName` annotation."
- Where do they go to check that? 
- Once they get to the place where they can check, how will they know "...if there was a rename with the `@JSName` annotation"?
- If they find the answer to "...if there was a rename..." is "yes, there was", what do they do now?

I guess I'm having trouble picturing all of this, could you show an example (or make one up) of an API with the `native` keyword and what looking that up would look like, plus what they would see that would confirm an `@JSName` rename? Thank you!

**Comment by srujzs** [comment]
> I'm assuming by "if you find" you mean "if the two methods we just mentioned (the fix and looking up the definition manually) don't turn up an answer", is that correct?

I meant it as part of the second method actually. "If you look up the definition of the declaration/API, and you see that it has a `native` keyword..."

> What does it mean for an API to be "with the keyword native"? Like, does that mean native is literally in the API's name, or in its declaration somewhere? I can't picture it.

That's likely poor wording on my part, perhaps *contains* the keyword `native` in its signature? For example, here's `append` from `dart:html`:

```dart
@JSName('appendChild')
Node append(Node node) native;
```

From a user perspective, I look up the `dart:html` definition of `append` because it doesn't exist in `package:web`. I see that it contains `native` and realize that's equivalent to `external`. What JS member actually gets called depends on either `append`'s name or its rename with `@JSName`. Since it has a rename, I can deduce that calling `append` in `dart:html` actually calls `appendChild`. I then look for an `external` member named `appendChild` and find [this member](https://github.com/dart-lang/web/blob/fa4280c061f0043f1d3c5346ab1495512de4bef2/lib/src/dom/dom.dart#L240).

So to summarize, I'd phrase the steps this way:

1. Notice that a member that exists in `dart:html` doesn't exist in `package:web` and `dart fix` doesn't fix it.
2. Find the `dart:html` definition.
3. If it contains the keyword `native`, because we couldn't find the `package:web` member, it likely is renamed using `@JSName`. So find the JS member that was actually called by looking at the value in that annotation.
4. Find the `package:web` member with the same name as the JS member (there are very few renames in `package:web`, mostly to handle Dart keywords).
5. Use that member instead.

Of course, if it's a Dart method (and hence does not have a `native` keyword), that's a separate issue and a bit more complicated and is addressed in https://dart.dev/interop/js-interop/package-web#non-native-apis.

Let me know if this need more clarification!
