### ISSUE TITLE
[PAGE ISSUE]: 'Asynchronous programming: futures, async, await': main as an asynchronous function?

### ISSUE THREAD

**Issue by dtonhofer** [dart-lang/site-www#5624]
### Page URL

https://dart.dev/codelabs/async-await/

### Page source

https://github.com/dart-lang/site-www/tree/main/./src/content/codelabs/async-await.md

### Describe the problem

At [Working with futures: async and await](https://dart.dev/codelabs/async-await#working-with-futures-async-and-await)

we see that function `main()` is rendered asynchronous:

`Future<void> main() async { ··· }`

but then the call is made:

`print(await createOrderMessage());`

### Expected fix

The `main()` of the example should probably be `createOrderMessage()`.

While the compiler (but maybe not the linter) is apparently happy with an asynchronous main returning a `Future<void>`, it seems also rather unusual.

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by eernstg** [comment]
Drive-by comment from a language perspective:

You can have situations where a top-level function named `main` is called from Dart code. (It may or may not be the same function as the one which is invoked from the runtime in order to run the whole program.) This implies that even though a function named `main` has a special role in a Dart program execution, it _can_ also be just another top-level function.

Hence (and also just for consistency in a broader sense), there's nothing wrong in following all the normal rules about functions when writing the declaration of a top-level function named `main`.

It is true that most `main` functions have return type `void`, even when the body is `async`, but that's basically just breaking the normal rules about good style because "it doesn't matter because no Dart code will ever call this function".

With that in mind it's perfectly fine to use `Future<void>` as the return type of an async `main`. This implies that callers can await the computation performed during an execution of `main`, but the given future will be completed by an object which is of no interest (so the value of `await main(...)` should be ignored and discarded).

With that in mind there's nothing wrong with the following:

```dart
Future<void> main() async {
  ···
  print(await createOrderMessage());
  ···
}
```

> The `main()` of the example should probably be `createOrderMessage()`.

It is of course possible to rename and rewrite functions arbitrarily, but if we just delete the current `main` declaration and rename `createOrderMessage` to `main` then the returned `Future<String>` would be completed and the `String` would be ignored, which is surely not the intended behavior of the program. So I can't really see how a renaming operation like that would be useful.

**Comment by dtonhofer** [comment]
Thank you! Got it!

Yes I was extremely confused when saying:

> The `main()` of the example should probably be `createOrderMessage().`

In retrospect that makes no sense. The issues collapses to "what syntax (consistently) to use for `main() async`".

On the mentioned page, a few lines after 

```
Future<void> main() async {
```

there is an example which just uses

```
void main() async {
```

So that line should be fixed I guess. I have opened an additional issue

https://github.com/dart-lang/site-www/issues/5626

that is hopefully clearer and will reference this one from there.

I reckon this issue can be closed without further delay.

**Comment by eernstg** [comment]
> Thank you! Got it!

Thanks for the kind words!

> So that line should be fixed I guess.

Well, `void main() async {...}` is _extremely_ common, so even though `Future<void> main() async {...}` would be nicer, I don't think that's going to get any traction. ;-)
