### ISSUE TITLE
Code issue in async-await codelab

### ISSUE THREAD

**Issue by MathiasTeagan** [dart-lang/site-www#5663]
### Page URL

https://dart.dev/codelabs/async-await/

### Page source

https://github.com/dart-lang/site-www/tree/main/./src/content/codelabs/async-await.md

### Describe the problem

There isn't true cod in boxes.

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by parlough** [comment]
Hi @MathiasTeagan, thanks for opening the issue! Could you provide more information on what you mean by "There isn't true cod in boxes.", or point on where on the page the issue is. Thanks so much!

**Comment by parlough** [comment]
Ah I see. I think this was caused by https://github.com/dart-lang/site-www/commit/40ec83011969ecc5565b7ef37cca3359d0d73adb (tracked in https://github.com/dart-lang/dart-pad/issues/2893). https://github.com/dart-lang/dart-pad/commit/4d7b092cab6f748e5b8a0abca48ad3b13fae1677 should fix the most common cause of it, so I'll mark this as fixed. If you come across this issue again, please let us know. Thanks again :D
