### ISSUE TITLE
Fix potential contradiction on 'Constructors' page

### ISSUE THREAD

**Issue by Homo-carbonis** [dart-lang/site-www#5738]
### Page URL

https://dart.dev/language/constructors/

### Page source

https://github.com/dart-lang/site-www/tree/main/src/content/language/constructors.md

### Describe the problem

These two sentences appear to be contradictory:
"Subclasses don't inherit constructors from their superclass."
"By default, a constructor in a subclass calls the superclass's unnamed, no-argument constructor."

Surely the subclass must inherit at least the no-name, no-arg constructor in order to call it?

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by eernstg** [comment]
> These two sentences appear to be contradictory:
> "Subclasses don't inherit constructors from their superclass."
> "By default, a constructor in a subclass calls the superclass's unnamed, no-argument constructor."

I don't see a contradiction, but the terminology is somewhat confusing.

A constructor is not an instance method. That is, it is not executed by specifying a receiver and a member name, and then looking up in the receiver which implementation of that member name to run (in other words: a constructor invocation does not use object-oriented dispatch, it is always known statically exactly which piece of code we're calling). This implies that it makes no sense in the first place to talk about a constructor being inherited or not.

What actually happens is that an instance creation expression (say, `C<int>.name(14)`) is executed in several steps: First we detect that it's concerned with the class `C` with actual type arguments`<int>`, and then we allocate the amount of memory needed to hold an instance of `C`. We store the information that this is an object of type `C` and initialize its type arguments to `<int>`. At the end, a reference to the allocated memory will be the value of the instance creation expression.

However, before we obtain the result, all the constructors associated with this instance creation expression are executed, with `this` bound to the newly allocated memory. This causes the freshly allocated memory to be turned into an object, that is, the object is initialized. Those constructors are found by taking the expression itself (yielding `C.name`, which must be the name of a constructor declared by `C`), and following the chain of links from each constructor to a super-constructor (that is, a constructor of the superclass of the current constructor) which is specified at the end of the initializer list of every constructor (`super()` if the developer didn't write anything). We're executing  the initializer list of the constructor `C.name`, then the initializer list of the specified superclass constructor, etc., up to the constructor of `Object`. Next, we execute the bodies of the same constructors, starting from `Object` and going down to `C.name`.

All these invocations are resolved statically (no OO dispatch, no inheritance).

So it's correct to say that "subclasses don't inherit constructors from their superclass", but it is also confusing because the whole notion of inheritance of methods is associated with instance members, and constructors aren't.

It is also correct to say that "by default, a constructor in a subclass calls the superclass's unnamed, no-argument constructor", because this simply means that the initializer list ends in an implicitly added `super()` if no term starting with `super` is given at the end of the initializer list.

We do have a phenomenon which is superficially similar to inheritance: Some constructors are implicitly generated by the compiler such that they will do nothing other than forward to a specific superclass constructor. For example:

```dart
class A { A(); A.name(int i) {...} ... }
mixin M { ... }
class B = A with M;
```

Class `A` has a constructor named `A`. Class `B` is a subclass of `A` which is created by adding the mixin `M` to `A`. The special syntax using `=` has an interesting built-in feature which is not shared by normal class declarations: Class `B` has constructors, even though we haven't written anything, because the compiler adds a constructor to `B` for each constructor of `A`, with the corresponding name. The constructors in `B` are just forwarding constructors, they don't do anything other than calling the constructors in `A` with the same arguments.

In this case this means that `B` has a constructor which works like `B() : super()`, and another one like `B.name(int i) : super.name(i);`. The first one calls `A()`, the second one calls `A.name(i)` (and given that the `B` constructors do not have any initializers, and they do not have any bodies, they don't do anything _other_ than calling that `A` constructor).

> Surely the subclass must inherit at least the no-name, no-arg constructor in order to call it?

No, a constructor can be called as part of the creation of a new object, and that constructor will then call a constructor of the superclass, which is repeated until we reach `Object`, and then we go down again (doing initializer lists on the way up and bodies on the way down). None of those constructors are inherited by any other class than the one where they're declared, but the semantics of object creation is that we're calling a constructor for each class in the chain of superclasses of the newly allocated object.

Constructors aren't like static methods, either, because static methods do not have a binding of `this`, but when it comes to "inheritance" the situation is similar to the following:

```dart
class A {
  static initializer() { Object.Initializer(); ... }
}

class B extends A {
  static initializer() { A.initializer(); ... }
}

class C extends B {
  static initializer() { B.initializer(); ... }
}
```

Here, we're just calling the `initializer` of each class upwards (so we're going to execute the body of `Object.initializer`, then the body of `A.initializer`, etc., just like the bodies of the constructors (and we're ignoring the initializer lists). But the point is that a static method of `C` can call a static method of `B` by just calling it(!), and there's absolutely no need to try to claim that `C` must inherit `B.initializer` in order to be able to call it.
