### ISSUE TITLE
[PAGE ISSUE]: 'constant_identifier_names' Bad Example shows proper style const name

### ISSUE THREAD

**Issue by canewsin** [dart-lang/site-www#5866]
### Page URL

https://dart.dev/tools/linter-rules/constant_identifier_names.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/content/tools/linter-rules/individual-rules.md

### Describe the problem

Bad example shows proper style example as bad one
```
Bad
const kDefaultTimeout = 1000;
```
on flutter site this shown as which is correct
```
Bad
const DefaultTimeout = 1000;
```

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by canewsin** [comment]
https://dart.dev/effective-dart/style#dont-use-prefix-letters, says below is bad but on flutter.dev(can't find right now) below is ok
```
kDefaultTimeout
```

**Comment by parlough** [comment]
The lint and the Effective Dart entry are about creating your own constants. That style of constant is used by Flutter occasionally, I'm assuming due to historical reasons. It's fine to use the ones Flutter provides, but to follow the style guide avoid introducing new constants that use the `kCamelCase` naming scheme.
