### ISSUE TITLE
Update or remove Emulating Functions article

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#600]
The [Emulating Functions article](https://www.dartlang.org/articles/language/emulating-functions) hasn't been updated since 2014. Callable classes will be changing in Dart 2, as described [this announcement](https://groups.google.com/a/dartlang.org/d/msg/misc/hvt6jpiYxsE/ZQsrT67ZAQAJ). 

/cc @eernstg

**Comment by matanlurey** [comment]
Also linked in https://github.com/dart-lang/site-www/issues/562, which states:

> Callable classes:
>   - A class with a call method can still be "called" using the call syntax: o(arguments)
>   - A function can still be called with the ".call" syntax
>   - But if 
>      - you use an object o with static type C
>      - where C has a call method
>      - in a context where a function typed thing is expected
>      - then this will be treated as a tearoff of the call method, instead of just passing the object directly
> 
> There's a good comment on this bug: https://github.com/dart-lang/sdk/issues/32151
> 
> with concrete examples of how Dart 2 will differ from Dart 1

**Comment by eernstg** [comment]
I'll comment on [the article](https://www.dartlang.org/articles/language/emulating-functions) first:

Everything in **The call() method** is **still true**. (1: We do not define 'procedural interface', but no matter how it's defined the rest of the sentence is still OK; 2: it's no longer possible to fully emulate a function object F using an instance of a regular class that declares a `call` method, but it can be done with a function object of the same type as F, so bullet 2 is OK, too).

In **How does it work?**, everything is OK except that the **last sentence** ('The default implementation of noSuchMethod() checks to see whether it was invoked due to an attempt to use call(), and if so issues a helpful error message suggesting you might have wanted to use a closure.') is not true. I don't know whether it has been true at any point, but that wouldn't matter, anyway, so we should just **delete** that sentence.

However we should **add** one more thing to 'How does it work?': If we assign an expression `e` whose type is a class that has a `call` method to a variable (or pass it as a parameter, or return it, or initialize something with it, etc.), and the type of the target is a function type, then `e` is implicitly transformed to `e.call` (which is a tear-off operation that yields a function object).

This breaks the fundamental rule that "type annotations do not change the dynamic semantics", but that's a pervasive property of Dart 2 (for instance `List<int> xs = [];` makes that `[]` behave differently than it would with the declaration `List xs = []`, even in a context where the original declared type is unknown, say, because that list is accessed as `List<Object> ys` somewhere else). So it may well contradict other things that were written for Dart 1, but I don't see any direct contradictions on this page.

Section **Function Types** needs to be changed a lot. But since there are no special rules (we eliminated the special rule which is described here), I think a good choice is to simply **delete that section**.

For **Summary**, I'd suggest something like this:

```
Here is what you need to know in order to define a class that works similarly to a function in Dart:
- Define a class with a method named call.
- Implement the call() method to define what instances of your class do when invoked as functions via the () syntax.
```

But we should definitely **not** recommend that they add `implements Function`. We just discussed that in several contexts, and it doesn't actually provide any advantages (you could say that it never did).

Finally (which may become another issue), we ought to fix the references to class `Invocation` in the section **Interactions ..**: Dart 2 `Invocation` has an extra getter `List<Type> get typeArguments`, so the code example should become:
```dart
noSuchMethod(Invocation invocation) => invocation.memberName == #foo
    ? Function.apply(
        baz,
        invocation.positionalArguments,
        invocation.namedArguments,
        invocation.typeArguments,
      )
    : super.noSuchMethod(invocation);
```
(I used `dartfmt` to make sure the formatting is similar to Dart code that the reader may see elsewhere.)

**Comment by kwalrath** [comment]
Thanks very much for the details, @eernstg.

**Comment by kwalrath** [comment]
@eernstg I'm = working on this now. I'm a bit confused about the last bit of code, where you say to pass `invocation.typeArguments` to `Function.apply`. [apply](https://api.dartlang.org/stable/2.0.0/dart-core/Function/apply.html) takes only 3 arguments, not 4. How should I use `typeArguments`? Thanks!

**Comment by lrhn** [comment]
I believe those type arguments are a mistake. We did consider making `Function.apply` accept type arguments as well, but decided against it, so there is *no way* to invoke a generic function with type arguments in a variadic way, or passing the type parameters on in `noSuchMethod`.
(We never allow you to reify a `Type` object as a run-time type, that would be too expensive for ahead-of-time compilers like Dart2JS).

**Comment by eernstg** [comment]
OK, I hadn't heard that this enhancement had been rejected.
