### ISSUE TITLE
Document "analysis context" and account for workspaces too

### ISSUE THREAD

**Issue by parlough** [dart-lang/site-www#6145]
Related issue: https://github.com/dart-lang/site-www/issues/5891

References relating to multi-option contexts and workspaces:

- https://github.com/dart-lang/sdk/issues/53875
- https://github.com/dart-lang/sdk/issues/53874
- https://github.com/dart-lang/sdk/issues/53876
- https://flutter.dev/go/pub-workspace

**Comment by MaryaBelanger** [comment]
Some notes:

Summary: allows the analyzer to load all of the code across a monorepo as an individual package, as opposed to blown up memory usage analyzing for every different package

How to: `workspace` field in pubspec indicates this is a workspace, so analyzer analyzes globally. 
(Also an IDE configuration option?)

**Comment by MaryaBelanger** [comment]
#### [Customizing static analysis](https://dart.dev/tools/analysis) page

Right after this section might be a good place to caveat that if you enable a workspace, what analysis_options.yaml applies to what packages would be different (?):

<img width="931" alt="image" src="https://github.com/user-attachments/assets/b6689064-0185-4240-a12d-1397761ab0ba">

**Comment by MaryaBelanger** [comment]
#### [Pub workspaces ](https://dart-dev--pr6117-document-workspaces-r9fkahhq.web.app/guides/workspaces)(monorepo support) (not yet published)

It's mentioned early in the page that not using the workspace feature causes bloated analysis contexts. 
Later somewhere it should mention how the analysis context problem changes on pub workspaces are enabled.

Maybe at the end of the "To create a workspace" section, after "Now the file structure looks like this:"

Or maybe a small section titled "Analysis context in a workspace" that briefly explains how one can expect their workspace to be handled by the analyzer, and the benefits of that.

**Comment by MaryaBelanger** [comment]
#### [Performing analysis](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/doc/tutorial/analysis.md) (sdk tutorial, 4 years old)

Does this need updating for analysis context changes?

> An analysis context is a representation of a set of code that should be analyzed using the same sources of metadata (same package_spec.json file, _same analysis options file_, etc.). That set of code typically _corresponds to **a** package_.

-- still true? analysis contexts are wider now, don't necessarily use the same analysis options file (or they do? but it's multiple files now?) Also, can correspond to multiple packages, not just _a_ package

> Each analysis session is associated with a single analysis context...

-- now that the nature of analysis contexts has changed, is this still true?

> `AnalysisContextCollection` 

-- instead of using this, would it be easier to use workspaces? sounds like they address the same goal (or i'm mixing up "files"vs."packages")

Talks a lot about analyzing collections of files; does any of that change/have a better solution now with the changes to analyzer contexts?

**Comment by MaryaBelanger** [comment]
Ok, I've exhausted every lead and it's very clear analysis contexts are an implementation detail that is [not relevant](https://github.com/dart-lang/site-www/pull/6239#discussion_r1866234086) to readers of our site. The doc for analyzer _contributors_ has been updated, and the new pub doc will only refer to the lowered memory burden/improved performance benefits for large repositories using workspaces. The end, closing!
