### ISSUE TITLE
cant run your code examples 

### ISSUE THREAD

**Issue by bavindeveloper** [dart-lang/site-www#6197]
### Page URL

https://dart.dev/resources/dart-cheatsheet

### Page source

https://github.com/dart-lang/site-www/tree/main/src/content/community/index.md

### Describe the problem

cant run any of the code examples in the cheetsheet ,every example have multiple  issues in dart pad 

### Expected fix

provide fixed code for further rufference 

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by MaryaBelanger** [comment]
Hi @bavindeveloper, do you mean the dartpads on the page aren't working, like in this case where the buttons aren't showing?:
<img width="940" alt="image" src="https://github.com/user-attachments/assets/43efe236-3602-45cf-843f-b59a81e84630">

Or do you mean you're looking for the solutions to each of the dartpad exercises? The code in the dartpads intentionally incomplete so that you can solve it yourself. The solutions are hidden below each dartpad in a drop-down that says "**> Solution for ....**". You can see an expanded example below:
<img width="920" alt="image" src="https://github.com/user-attachments/assets/30313b38-a076-4658-82e4-bd00c1dc2b31">
