### ISSUE TITLE
Move/copy webdev installation instructions to site-webdev

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#657]
Currently, developers have to bounce back and forth between webdev.dartlang.org and www.dartlang.org to get started. Instead, they should be able to stay on webdev, even if that means we duplicate content. Implementing this will be easier if we get infrastructure that lets us share files between sites. Once these instructions are VM only, we'll be able to simplify them.

/cc @filiph @anders-sandholm

**Comment by kwalrath** [comment]
We'd need to copy most/all of the following pages:

https://www.dartlang.org/install
https://www.dartlang.org/install/archive
https://www.dartlang.org/install/linux
https://www.dartlang.org/install/mac
https://www.dartlang.org/install/windows

**Comment by chalin** [comment]
Ok, I'll explore options tomorrow.

**Comment by anders-sandholm** [comment]
I'd vote in favor of just copying contents rather than sharing for two reasons. 

1) It allows us to tailor the descriptions/wording to the context / use case at hand (cmd-line or web) although the actual actions / technical steps may be exactly the same. 

2) We may - over time - end up having separate SDKs for core and web.

**Comment by chalin** [comment]
This issue was moved to dart-lang/site-webdev#1471
