### ISSUE TITLE
Add back Who Uses Dart page

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#679]
Looking at analytics from July 29 - August 4, 2019, /community/who-uses-dart is now our top 404.  (It's been in the top 4 ever since we deleted it when switching to dart.dev, and we've dealt with the URLs that preceded it.)

I think I'll add back a bare-bones page that links to the Flutter showcase. I considered also linking to pub.dev or GitHub, but I can't think of a good, helpful way to give readers "who uses Dart" info from those. I considered not adding a page — instead redirecting who-uses-dart to https://flutter.dev/showcase — but that could be confusing.

---------------

Here's the original issue description (which pertained to the [old version of this page](https://web.archive.org/web/20190402200008/www.dartlang.org/community/who-uses-dart)):

> We have a lot of entries, and it might be nice to be able to categorize them. Also, we should consider using a form, instead of requiring PRs.
> 
> @wmleler first thought of categories (see https://github.com/dart-lang/site-www/issues/671#issuecomment-373562298).

**Comment by wmleler** [comment]
I left that comment because just looking at this page, it is difficult to get any general idea of the kinds of things for which Dart is being used. For example, it would be nice to break this page into categories like:
* Google (projects internal to Google that use Dart). Alternatively, put these into the other categories but use some icon or tag to mark Google apps.
* Web (external projects that use Dart for webapps)
* Flutter (mobile apps)
* Other (server-side, embedded systems, etc.)

**Comment by kwalrath** [comment]
Other possibilities:

* Flutter apps (with link to web store)
* Web apps (with link to app)
* Internal apps (no link, but maybe a company logo)
* Other (optional link)

It'd be cool to be able to search for the kinds of Dart usage you're interested in—e.g. Android, iOS, AngularDart, enterprise, ...

**Comment by wmleler** [comment]
That's a great idea.

Adding on that idea: We could have tags for the above, and instead of
showing them as fixed categories, allow people to select the kinds of apps
they are interested in (i.e., search) That would let them filter to show
only the type of apps they are interested in.

That would be good because it would handle companies like AppTree, who have
an app that works both on mobile (Flutter) and web.

**Comment by kwalrath** [comment]
See also the discussion on #1062. 

/cc @filiph

**Comment by parlough** [comment]
This has been added back but is missing useful content and examples. I'm going to close this in favor of https://github.com/dart-lang/site-www/issues/4144 which tracks the work of updating this page and adding further examples.
