### ISSUE TITLE
'Cookbook: Dart by Example' page issue

### ISSUE THREAD

**Issue by Herohtar** [dart-lang/site-www#685]
Per [this SO question](https://stackoverflow.com/questions/49352149/dart-recipe-file-rename-renames-the-file-but-does-not-update-the-path-in-the-o), the [Renaming a file, directory, or symlink](https://www.dartlang.org/dart-vm/dart-by-example#renaming-a-file-directory-or-symlink) example is wrong. The example code is:
```
import 'dart:io';

main() async {
  // Get the system temp directory.
  var systemTempDir = Directory.systemTemp;

  // Create a file.
  var file = await new File('${systemTempDir.path}/foo.txt').create();

  // Prints path ending with `foo.txt`.
  print('The path is ${file.path}');

  // Rename the file.
  await file.rename('${systemTempDir.path}/bar.txt');

  // Prints path ending with `bar.txt`.
  print('The path is ${file.path}');
}
```

It incorrectly says that the original `File` object will have the updated path, when the API for [`rename()`](https://api.dartlang.org/stable/1.24.3/dart-io/File/rename.html) shows that it actually returns a new `File` instance for the renamed file.

The last lines should actually be something like:
```
// Rename the file.
var renamedFile = await file.rename('${systemTempDir.path}/bar.txt');

// Prints path ending with `bar.txt`.
print('The path is ${renamedFile.path}');
```

**Comment by kwalrath** [comment]
Thanks very much for filing this issue.

Unfortunately, we're planning to remove the cookbook, since it's not well tested and has been rotting. That said, the repo it's taken from is open source, and it wouldn't hurt to fix the sample there:

https://github.com/dart-lang/dart-samples/blob/master/dart_io_mini_samples/example/files_directories_and_symlinks/renaming_a_file_directory_or_symlink.dart
