### ISSUE TITLE
Consider referring to or adopting Flutter style rules

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#803]
The Flutter repo follows these style rules:

https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo

These rules include things like [Constructors come first in a class](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo), which came up because a codelab I was modifying had constructors first, and it looked weird to me.

Should we link to these rules (as a group or individually)? Should we consider adopting any of them? Should we favor following them in our general Dart examples?

**Comment by munificent** [comment]
There's a *lot* of rules here to consider. Skimming the list, I see:

* Rules that "Effective Dart" already has (or that were recently added): "Avoid double negatives in APIs"
* Rules that I think would be good to add to "Effective Dart": "Prefer naming the argument to a setter value".
* Rules that I don't think are worth adding them to "Effective Dart" because it seems users mostly do the right thing already: "Prefer specialized functions, methods and constructors"
* Rules that are directly counter to "Effective Dart": "Avoid using 'var'"

So, yeah, we'll have to go through and decide which ones we want to harvest.

**Comment by munificent** [comment]
OK, I went through it. Overall, I think it's a really fantastic guide. The section on documentation is especially good.

But I don't see anything I want to clone into "Effective Dart". A lot of the specific guidance is already there. The specific rules that aren't there are things around formatting where the Flutter guide is in conflict. The stuff that isn't in "Effective Dart" that I like the most is also higher level and generally out of scope.

So I think I'll just leave things as-is and encourage folks to also read the Flutter guide.
