### ISSUE TITLE
Update /resources/books to have info about Dart 2 books

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-www#806]
This is a two parter:

- [x] Let people know that, for now, all books cover Dart 1.x. (See #807)
- [ ] Make code changes so it's easy to list Dart 2 books separately from Dart 1.x books.

I'll handle the first now. @chalin could you handle the second?

**Comment by chalin** [comment]
Certainly. Let's discuss what you have in mind.

**Comment by kwalrath** [comment]
I'm not aware of any Dart 2 books yet, although I've heard some were in the works.

**Comment by cseder** [comment]
This one seems to be available:

[Quick Start Guide to Dart Programming (Apress ©2020)](https://www.apress.com/gp/book/9781484255612)
eBook ISBN: 978-1-4842-5562-9
Softcover ISBN: 978-1-4842-5561-2

Do I need to create a PR or something to get it on the list or do we have a magician around here that takes care of it?

Chris

**Comment by parlough** [comment]
I'll consider this fixed by https://github.com/dart-lang/site-www/commit/b8170dce8632db100e57ff87b8779ec061737212 which added the first Dart 2 book and was followed up by another book which was even updated to support null safety(https://github.com/dart-lang/site-www/commit/938117368222079ac6485a5458c6701e0b4aa6f7).

If anyone has any more Dart 2 books they'd like to see added to the website, feel free to open an issue or a pull request. Thanks!
