### ISSUE TITLE
Example on dartlang.org front page is not very representative

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/site-www#841]
I don't think calculating pi using Monte Carlo is very representative of the client-side programming we are promoting dart for.

It is also using `async*` where `sync*` probably would be more appropriate.

**Comment by kwalrath** [comment]
Good point. Can you think of an example that'd be more appropriate, given that we'd like the code to run in DartPad (and thus can't use packages)? Maybe the code should seem like something a Flutter app and web app might share... something more interesting than widget composition code.

/cc @filiph

**Comment by kwalrath** [comment]
@mit-mit and @maguinis are thinking about the homepage. I'm not sure who'd be responsible for the example, but @mit-mit would know.

**Comment by filiph** [comment]
I had these goals when writing the code:

* use a variety of language/stdlib features
* keep it short
* keep it interesting

FWIW, it's common for programming languages to show off math / physics code instead of the more business-y code that people will be actually writing on their landing pages. golang has Hello World, Conway's Game of Life, Fibonacci, Peano integers, etc. Kotlin has Hello World, OO Hello Word, and asynchronous printing of hearts using coroutines. Swift shows a spiral painter.

I'm not saying the snippet shouldn't be changed — I'd actually like it. But I would not like it to be too much about Flutter, for example, or too mundane (e.g. `class Account`).

**Comment by mit-mit** [comment]
No longer relevant on the redesigned dart.dev
