### ISSUE TITLE
Enabling Dart 2 type system: instructions unclear

### ISSUE THREAD

**Issue by nilsdoehring** [dart-lang/site-www#866]
Location: https://www.dartlang.org/guides/language/analysis-options#enabling-dart-2-semantics

The paragraph linked above explains how to enable Dart 2 semantics by adding adding `strong-mode: true`.

Then, the next paragraph states that one can **optionally** add flags to enable stricter checks than Dart's type system requires (and links to info about Dart 2's type system). But directly below the code block, states that these flags are **required** to enable the Dart 2 type system ~~(which is true in SDK 2.0.0-dev54.0)~~.

**Comment by kwalrath** [comment]
I don't see where it says the flags are required. Are you referring to "The presence of either flag, regardless of value, enables the Dart 2 type system"? Because you could omit those flags (`implicit-*`) and just use `strong-mode: true` to enable the Dart 2 type system.

(Soon this will be moot, as we'll have _only_ Dart 2 semantics. Until then, I want to make sure the docs are correct and clear.)

**Comment by nilsdoehring** [comment]
> Are you referring to "The presence of either flag, regardless of value, enables the Dart 2 type system"?

Yes, that sentence might make the reader question whether "enable Dart 2 semantics" and "enable Dart 2 type system" are two different actions, the former activated by using `strong-mode: true`, the latter by `implicit-*`. I was confused by this at least, and I'm not new to Dart.

**Comment by chalin** [comment]
The section in question has been dropped in #1041
