### ISSUE TITLE
"Return" does not work in ".ForEach()" loop function

### ISSUE THREAD

**Issue by KenarDevs** [dart-lang/site-www#878]
Title is quite accurate.
Here are example that always return 0:
```
int myFunc(String s1){
    int r = 0;
    myExampleStringList.forEach((String s2){
        if(s1==s2) return 2;
    });
    return 0;
}
```

**Comment by chalin** [comment]
This works as intended. It might be more obvious if you write it this way:

```dart
int myFunc(String s1) {
  void f(String s2) {
    if (s1 == s2) return 2; // returns from f
  };
  myExampleStringList.forEach(f);
  return 0; // returns from myFunc
}
```

The `return 2` statement returns from `f`, not from `myFunc`.

(In fact, this code and your original code have a type error, because `forEach()` expects a function returning `void`, so the function argument to `forEach()` must not return any value.)

I hope that this helps.

**Comment by KenarDevs** [comment]
Thank you very much!
