### ISSUE TITLE
Consider adding copy-heading-link-to-clipboard functionality

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#920]
On site-www and site-webdev our page headings are dynamically enhanced so include a link to self:

> <img width="418" alt="screen shot 2018-06-12 at 17 43 22" src="https://user-images.githubusercontent.com/4140793/41318969-3a54da58-6e68-11e8-8d69-c05426cddf0f.png">

Clicking on the link visits the heading. This is a good way to anchor a page at a particular heading.

We've had a request to include a copy-heading-link-to-clipboard functionality. This would be particularly useful if we could also put rich text in the clipboard (i.e., an anchor element with both the URL and the heading text).

Accessing the clipboard in a safe way that works across browsers can be tricky though. It might be nice if such functionality were always visible so that mobile users could access it.

**Comment by chalin** [comment]
Candidate packages:

- https://www.npmjs.com/package/clipboard

**Comment by parlough** [comment]
I'm going to close this as I personally think the current functionality to scroll to that header is more beneficial, especially since copying to clipboard can already be done with the heading anchor by using the browser context menu and/or key bindings.

If anyone feels strongly about this though, please let me know :)
