### ISSUE TITLE
Improve (or drop) Resources page, and link to it from the sidenav

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#929]
From https://github.com/dart-lang/site-www/pull/928#discussion_r195497597:

> At the very least, [the resources page] should include links to everything listed under it in the sidenav.

**Comment by chalin** [comment]
@kwalrath - We could just drop the [Resources page](https://www.dartlang.org/resources) -- site-webdev doesn't have one. What is your preference? If we do drop it then:

- We could add "Books on Dart" to the sidenav, under Resources.
- Drop the Authors? If not, we'd have to mark some as emeritus, and add bios for the new members of the language team. (That seems like a bit much to do atm.)

**Comment by kwalrath** [comment]
Unless we move everything that's currently under resources/, we need to keep the page. If we keep the page, the question becomes whether we want to link to it from the sidenav.

> Background: The Resources page exists on dartlang.org only because the dartlang.org/resources path exists (which it doesn't on webdev.dartlang.org). We made a point of adding index pages to every directory, since people sometimes edit the URL by hand. /resources is the 126th most visited URL on the site, out of ~2000, which (though not large) is kind of impressive for a page with no links to it. People are finding it in a Google search or typing it in or walking up the tree to it. We used to have more under /resources: dart-tips, synonyms, ... Even without those, people are still finding /resources.

About the pages underneath /resources:

* I don't think we want to point to the Books page on the sidenav now — certainly not until we have some books out that cover Dart 2. But we do want to keep the Books page around, for the future.
* I'd be happy not to point to the Authors page. In fact, I was surprised that we did! But we still need to keep it and the few pages that it points to, since they actually get some visits. (Those pages could move, of course.)

But back to the original point, it seems like dartlang.org/resources might be a handy URL to keep around. I'll add the stuff that's in the sidenav to the page, and make it a link.

**Comment by kwalrath** [comment]
Confirmed that https://dart.dev/resources is in the sidenav.
