### ISSUE TITLE
Add "DON'T use a leading underscore for local variables or parameters."

### ISSUE THREAD

**Issue by munificent** [dart-lang/site-www#947]
Privacy only applies to top-level declarations and members, so it's misleading to see a "private" name for a local.

**Comment by lrhn** [comment]
While we are at it, library names are also not subject to privacy, so a library name part starting with `_` is equally misleading.

Import scope prefixes may or may not be *subject* to privacy, but they cannot be made visible outside the library anyway, so effectively it doesn't matter.

More interesting is public static members of private classes. They are not accessible from outside the library in any way. Users disagree on whether that means you shouldn't write `_` in front because it's not necessary, or you should write it to emphasize (redundantly) that they aren't visible. (And any reasoning made about that arguably applies to import scope prefixes too).

In some cases, you want to avoid naming conflict with something else, and using `_foo` instead of `foo` is a simple fix, but then, so is `foo_`, and you probably should find a better name anyway.

**Comment by munificent** [comment]
+1 to all that. (For static members on private classes, I usually omit the underscore because of the fundamental "if all else is equal, prefer brevity" rule.)

**Comment by bencalabrese** [comment]
Friendly ping - is there still a plan to add this?

**Comment by rakudrama** [comment]
I think `_` is a perfectly good name for an _unused_ parameter, and it appears to be a fairly widely used convention.
Perhaps the lint should allow a leading `_` for variables and parameters that are not used, and complain if they are used. This would give us a convention for intentionally unused values.
