### ISSUE TITLE
'Sample Code' page issue

### ISSUE THREAD

**Issue by natebosch** [dart-lang/site-www#954]
From URL: https://www.dartlang.org/samples/

Code is not formatted by dartfmt - can the `prettify dart` process use dartfmt?

**Comment by chalin** [comment]
Why do you have the impression that dartfmt isn't used over the samples? Each sample is excerpt from a source file over which dartfmt is run. We also either run the analyzer, and tests (when available).

We run dartfmt over the sample sources, though possibly not with the default 80 character limit Also, in some cases we force line breaks (so that long lines are better visible on narrow displays). Maybe that is what you are seeing?

cc @kwalrath

**Comment by natebosch** [comment]
Yes the less than 80 character limit is probably what I'm seeing.
