### ISSUE TITLE
Avoid getters and setters of different types

### ISSUE THREAD

**Issue by munificent** [dart-lang/site-www#999]
It's confusing when a getter and setter with the same name have different types. It can be useful sometimes, usually with a setter that takes a more permissive type than the getter, but I think we probably want to encourage users to keep the types in sync.

**Comment by natebosch** [comment]
May soon be covered by an error in CFE which would make it unnecessary to document here.
https://github.com/dart-lang/sdk/issues/33836

If we can't fix it for Dart 2 because it's breaking we can consider documenting it, though it would still be covered by a Warning in analyzer so might not be worth it.

**Comment by munificent** [comment]
This is an error now, so there's no need to give style guidance on it.
